(() => {
"use strict";
if(window.__kpAlbumNext)return;
window.__kpAlbumNext=true;
const VERSION="6.0",STORAGE="krakowPocketCoop",PLAYER="krakowPlayer";
const $=(s,r=document)=>r.querySelector(s),active=a=>(Array.isArray(a)?a:[]).filter(x=>x&&!x.deletedAt),parse=v=>{try{return JSON.parse(v||"{}")}catch{return null}},now=()=>new Date().toISOString(),read=()=>parse(localStorage.getItem(STORAGE))||{};
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const time=x=>{const v=x&&typeof x==="object"?(x.updatedAt||x.deletedAt||x.completedAt||x.verifiedAt||x.ts||0):x,n=new Date(v||0).getTime();return Number.isFinite(n)?n:0};
function hash(data=""){const s=String(data),step=Math.max(1,Math.floor(s.length/700));let h=2166136261>>>0;for(let i=0;i<s.length;i+=step){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}h^=s.length;return(h>>>0).toString(36)}
function mergeRecords(a=[],b=[]){const m=new Map();for(const x of [...(Array.isArray(a)?a:[]),...(Array.isArray(b)?b:[])]){if(!x?.id)continue;const p=m.get(x.id);if(!p||time(x)>=time(p))m.set(x.id,{...x})}return[...m.values()]}
function recordFromEvidence(id,e){if(!e?.photo)return null;const fp=hash(e.photo);return{id:`history-${id}-${fp}`,missionId:id,title:e.title||e.place||"Recuerdo de la misión",place:e.place||"",photo:e.photo,comment:e.comment||"",by:e.by||e.player||e.completedBy||"Ambos",verified:e.verified===true,distance:Number.isFinite(+e.distance)?Math.round(+e.distance):null,extra:!!(e.extra||e.bonus),completedAt:e.completedAt||e.verifiedAt||e.updatedAt||now(),updatedAt:e.updatedAt||e.completedAt||now(),photoHash:fp,source:"mission-history"}}
let lastEvidence=JSON.parse(JSON.stringify(read().missionEvidence||{}));
function archiveReplacedEvidence(){
 const s=read(),cur=s.missionEvidence||{},extra=[];
 for(const [id,old] of Object.entries(lastEvidence||{})){const n=cur[id];if(!old?.photo||!n?.photo||hash(old.photo)===hash(n.photo))continue;const loser=time(n)>=time(old)?old:n,r=recordFromEvidence(id,loser);if(r)extra.push(r)}
 lastEvidence=JSON.parse(JSON.stringify(cur));if(!extra.length)return false;
 const before=s.albumPhotos||[],next=mergeRecords(before,extra);if(JSON.stringify(before)===JSON.stringify(next))return false;
 s.albumPhotos=next;s.updatedAt=now();try{localStorage.setItem(STORAGE,JSON.stringify(s));window.dispatchEvent(new CustomEvent("kp:album-photos-local",{detail:{count:extra.length}}));window.dispatchEvent(new CustomEvent("kp:statechange",{detail:{source:"album-history"}}));nudgeSync();return true}catch{return false}
}
function primaryHashes(s){return new Set(Object.values(s.missionEvidence||{}).filter(x=>x?.photo).map(x=>hash(x.photo)))}
function projected(){const s=read(),e={...(s.missionEvidence||{})},seen=primaryHashes(s);for(const p of active(s.albumPhotos)){if(!p?.photo)continue;const fp=p.photoHash||hash(p.photo);if(seen.has(fp))continue;seen.add(fp);e[`album-${p.id}`]={id:`album-${p.id}`,title:p.title||p.place||"Recuerdo del viaje",place:p.place||"Cracovia",photo:p.photo,comment:p.comment||"Un momento más de nuestro viaje.",by:p.by||"Ambos",verified:p.verified===true,distance:Number.isFinite(+p.distance)?Math.round(+p.distance):null,extra:!!p.extra,bonus:!!p.extra,completedAt:p.completedAt||p.createdAt||p.updatedAt||now(),updatedAt:p.updatedAt||p.createdAt||now()}}return{...s,missionEvidence:e}}
function withState(state,fn){const prev=Storage.prototype.getItem;Storage.prototype.getItem=function(k){if(this===localStorage&&k===STORAGE)return JSON.stringify(state);return prev.call(this,k)};try{return fn()}finally{Storage.prototype.getItem=prev}}
function original(){return window.__kpAlbumNextOriginal||window.KP_ALBUM_V5}
function html(){const api=original();if(!api?.html)return"";let out=withState(projected(),()=>api.html());const css='<style data-kp-album-multi="1">@media screen{.photo-button img,.photo-card:nth-child(4n+1) .photo-button img,.photo-card:nth-child(4n+4) .photo-button img{aspect-ratio:auto!important;height:auto!important;max-height:78svh!important;object-fit:contain!important;background:#ebe5dc!important}}@media print{.photo-button img,.photo-card:nth-child(4n+1) .photo-button img,.photo-card:nth-child(4n+4) .photo-button img{aspect-ratio:auto!important;object-fit:contain!important;max-height:92mm!important}}</style>';return out.replace('</head>',css+'</head>').replace('data-kp-album-v5="1"','data-kp-album-v5="1" data-kp-album-multi="1"')}
function count(){return Object.values(projected().missionEvidence||{}).filter(x=>typeof x?.photo==="string"&&x.photo.startsWith("data:image/")).length}
function sig(){const s=read();return JSON.stringify({e:Object.entries(s.missionEvidence||{}).map(([id,x])=>[id,x?.updatedAt,x?.photo?.length,x?.title]),a:active(s.albumPhotos).map(x=>[x.id,x.updatedAt,x.photo?.length,x.title,x.deletedAt]),m:active(s.memories).map(x=>[x.id,x.updatedAt||x.ts,x.title,x.note])})}
let dialog=null,frame=null,monitor=0,lastSig="";
function ensureViewer(){dialog=document.getElementById("kpAlbumV5Dialog");if(!dialog){dialog=document.createElement("dialog");dialog.id="kpAlbumV5Dialog";dialog.innerHTML='<div class="kp-v5-shell"><header><div><div class="smart-kicker">ÁLBUM DIGITAL</div><strong>Kraków · Ismael & Laura</strong></div><div class="kp-v5-head-actions"><button id="kpAlbumV5ShareTop" type="button">↗</button><button id="kpAlbumV5Close" type="button">✕</button></div></header><iframe id="kpAlbumV5Frame" title="Álbum digital de Cracovia"></iframe><footer><button id="kpAlbumV6AddViewer" type="button">＋ Fotos</button><button id="kpAlbumV5Download" type="button">⬇ HTML</button><button id="kpAlbumV5Pdf" type="button">📄 PDF</button><button id="kpAlbumV5Share" type="button">↗ Compartir</button></footer></div>';document.body.appendChild(dialog);dialog.addEventListener("close",()=>{document.documentElement.classList.remove("kp-album-v5-open");clearInterval(monitor);monitor=0})}frame=document.getElementById("kpAlbumV5Frame");return dialog}
function refresh(preserve=true){if(!dialog?.open||!frame)return false;const d=frame.contentDocument;if(d?.querySelector("#storyMode.open,#lightbox.open"))return false;const y=preserve?frame.contentWindow?.scrollY||0:0;frame.addEventListener("load",()=>{try{frame.contentWindow.scrollTo(0,y);setTimeout(()=>frame.contentWindow.scrollTo(0,y),50)}catch{}},{once:true});frame.srcdoc=html();lastSig=sig();return true}
function open(){ensureViewer();frame.srcdoc=html();lastSig=sig();document.documentElement.classList.add("kp-album-v5-open");if(!dialog.open)dialog.showModal();clearInterval(monitor);monitor=setInterval(()=>{if(!dialog?.open)return;const s=sig();if(s!==lastSig)refresh(true)},1000);return true}
function file(){try{return new File([html()],`Krakow_Pocket_Album_${new Date().toISOString().slice(0,10)}.html`,{type:"text/html;charset=utf-8"})}catch{return null}}
function download(){const f=file();if(!f)return false;const a=document.createElement("a"),url=URL.createObjectURL(f);a.href=url;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return true}
async function share(){const f=file();if(!f)return false;try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){await navigator.share({title:"Kraków · Ismael & Laura",text:"Nuestro álbum digital de Cracovia",files:[f]});return true}}catch(e){if(e?.name==="AbortError")return true}return download()}
async function print(){if(!dialog?.open)open();const start=Date.now();while(!frame?.contentDocument?.querySelector('[data-kp-album-v5="1"]')&&Date.now()-start<3500)await new Promise(r=>setTimeout(r,40));if(!frame?.contentDocument?.querySelector('[data-kp-album-v5="1"]'))return false;try{frame.contentWindow.focus();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));frame.contentWindow.print();return true}catch{return false}}
function loadImage(f){return new Promise((res,rej)=>{const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);res(i)};i.onerror=e=>{URL.revokeObjectURL(u);rej(e)};i.src=u})}
function jpeg(i,max,q){const iw=i.naturalWidth||i.width,ih=i.naturalHeight||i.height,k=Math.min(1,max/Math.max(iw,ih)),w=Math.max(1,Math.round(iw*k)),h=Math.max(1,Math.round(ih*k)),c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d",{alpha:false});x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(i,0,0,w,h);return{data:c.toDataURL("image/jpeg",q),width:w,height:h}}
async function compress(f){const i=await loadImage(f);let o=jpeg(i,1280,.76);if(o.data.length>145000)o=jpeg(i,1120,.70);if(o.data.length>125000)o=jpeg(i,960,.67);if(o.data.length>110000)o=jpeg(i,820,.64);if(o.data.length>95000)o=jpeg(i,720,.61);return o}
let addDialog=null;
function options(){const D=window.KP_DATA||{quests:[],pois:[]};return'<option value="">Sin asociar a una misión</option>'+(D.quests||[]).map(q=>{const p=D.pois.find(x=>x.id===q.poi);return`<option value="${esc(q.poi)}">${esc(p?.emoji||"📍")} ${esc(p?.name||q.title||q.poi)}</option>`}).join("")}
function ensureAdd(){if(addDialog?.isConnected)return addDialog;addDialog=document.createElement("dialog");addDialog.id="kpAlbumV6AddDialog";addDialog.innerHTML=`<div class="kp-album-add-shell"><div class="row start"><div><div class="smart-kicker">ÁLBUM COMPARTIDO</div><h2>Añadir fotos</h2><p class="small">Puedes elegir varias. Ninguna sustituye a las anteriores.</p></div><button class="kp-album-add-close" type="button">✕</button></div><label class="kp-album-file">📷 Elegir fotos<input id="kpAlbumV6Files" type="file" accept="image/*" multiple></label><div class="field"><span>Misión opcional</span><select id="kpAlbumV6Mission">${options()}</select></div><div class="field"><span>Título opcional</span><input id="kpAlbumV6Title" placeholder="Ej. Atardecer junto al Vístula"></div><div class="field"><span>Lugar opcional</span><input id="kpAlbumV6Place" placeholder="Cracovia"></div><div class="field"><span>Comentario opcional</span><textarea id="kpAlbumV6Comment" rows="2"></textarea></div><button class="btn green full" id="kpAlbumV6Save" type="button" disabled>Guardar fotos</button><div class="small" id="kpAlbumV6Status"></div><div id="kpAlbumV6Manage"></div></div>`;document.body.appendChild(addDialog);$(".kp-album-add-close",addDialog).onclick=()=>addDialog.close();$("#kpAlbumV6Files",addDialog).onchange=()=>{$("#kpAlbumV6Save",addDialog).disabled=!$("#kpAlbumV6Files",addDialog).files?.length};$("#kpAlbumV6Save",addDialog).onclick=savePhotos;manage();return addDialog}
function manage(){if(!addDialog?.isConnected)return;const h=$("#kpAlbumV6Manage",addDialog),list=active(read().albumPhotos).filter(x=>x.source==="album-extra").sort((a,b)=>time(b)-time(a)).slice(0,12);h.innerHTML=list.length?'<div class="smart-kicker" style="margin-top:16px">FOTOS AÑADIDAS</div>'+list.map(x=>`<div class="kp-album-manage-row"><img src="${x.photo}" alt=""><span><b>${esc(x.title||x.place||"Foto")}</b><small>${esc(x.by||"Ambos")}</small></span><button type="button" data-del="${esc(x.id)}">✕</button></div>`).join(""):"";h.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removePhoto(b.dataset.del))}
function openAdd(){ensureAdd();manage();if(!addDialog.open)addDialog.showModal()}
function removePhoto(id){const s=read(),p=(s.albumPhotos||[]).find(x=>x.id===id);if(!p)return;p.deletedAt=now();p.updatedAt=p.deletedAt;s.updatedAt=now();try{localStorage.setItem(STORAGE,JSON.stringify(s));window.dispatchEvent(new CustomEvent("kp:album-photos-local"));window.dispatchEvent(new CustomEvent("kp:statechange",{detail:{source:"album-delete"}}));nudgeSync();manage();patch()}catch{}}
function nudgeSync(){try{document.getElementById("dailyTarget")?.dispatchEvent(new Event("change",{bubbles:true}))}catch{}}
async function savePhotos(){const input=$("#kpAlbumV6Files",addDialog),files=[...(input.files||[])];if(!files.length)return;const st=$("#kpAlbumV6Status",addDialog),btn=$("#kpAlbumV6Save",addDialog);btn.disabled=true;const missionId=$("#kpAlbumV6Mission",addDialog).value,title=$("#kpAlbumV6Title",addDialog).value.trim(),place=$("#kpAlbumV6Place",addDialog).value.trim(),comment=$("#kpAlbumV6Comment",addDialog).value.trim(),D=window.KP_DATA||{pois:[]},poi=D.pois.find(x=>x.id===missionId),who=localStorage.getItem(PLAYER)||"Ismael";try{const out=[];for(let i=0;i<files.length;i++){st.textContent=`Preparando ${i+1}/${files.length}…`;const o=await compress(files[i]),stamp=now(),fp=hash(o.data);out.push({id:`photo-${Date.now().toString(36)}-${i}-${fp}`,missionId,title:title?(files.length>1?`${title} · ${i+1}`:title):(poi?.name||place||"Recuerdo del viaje"),place:place||poi?.name||"Cracovia",photo:o.data,comment,by:who,verified:false,createdAt:stamp,completedAt:stamp,updatedAt:stamp,photoWidth:o.width,photoHeight:o.height,photoHash:fp,source:"album-extra"})}const s=read();s.albumPhotos=mergeRecords(s.albumPhotos||[],out);s.updatedAt=now();localStorage.setItem(STORAGE,JSON.stringify(s));window.dispatchEvent(new CustomEvent("kp:album-photos-local",{detail:{count:out.length}}));window.dispatchEvent(new CustomEvent("kp:statechange",{detail:{source:"album-add"}}));nudgeSync();st.textContent=`✓ ${out.length} foto${out.length===1?"":"s"} guardada${out.length===1?"":"s"} para los dos.`;input.value="";$("#kpAlbumV6Title",addDialog).value="";$("#kpAlbumV6Comment",addDialog).value="";manage();patch();if(dialog?.open)refresh(true)}catch(e){st.textContent="No se pudieron guardar. Prueba con menos fotos o elimina alguna añadida.";btn.disabled=false}}
function styles(){if(document.getElementById("kpAlbumNextStyles"))return;const s=document.createElement("style");s.id="kpAlbumNextStyles";s.textContent='#kpAlbumV5Card .kp-album-next-note{margin-top:9px;padding:9px 11px;border-radius:13px;background:rgba(82,125,57,.11);font-size:12px}#kpAlbumV5Card .kp-v5-buttons{grid-template-columns:1fr 1fr!important}#kpAlbumV6Add{grid-column:1/-1}#kpAlbumV5Dialog .kp-v5-shell>footer{grid-template-columns:repeat(4,1fr)!important}#kpAlbumV6AddDialog{border:0;padding:0;background:transparent;width:100%;height:100%;max-width:none;max-height:none}#kpAlbumV6AddDialog::backdrop{background:#1b120ddb;backdrop-filter:blur(8px)}.kp-album-add-shell{position:fixed;left:12px;right:12px;bottom:max(12px,env(safe-area-inset-bottom));max-width:620px;margin:auto;max-height:88dvh;overflow:auto;padding:18px;border-radius:24px;background:#f7edd9;border:2px solid #6d432b;color:#3d271c}.kp-album-add-close{width:44px;height:44px;border:2px solid #6d432b;border-radius:14px;background:#fff4d4}.kp-album-file{min-height:54px;margin:13px 0;display:flex;align-items:center;justify-content:center;border:2px dashed #8f6546;border-radius:16px;background:#fff8e8;font-weight:900}.kp-album-file input{position:absolute;opacity:0;width:1px;height:1px}.kp-album-add-shell .field{margin-top:10px}.kp-album-add-shell .field>span{display:block;font-size:12px;font-weight:800;margin-bottom:5px}.kp-album-add-shell input,.kp-album-add-shell select,.kp-album-add-shell textarea{width:100%;min-height:44px;border:1px solid #b99875;border-radius:12px;background:#fff;padding:10px;font:inherit}.kp-album-manage-row{display:grid;grid-template-columns:48px 1fr 40px;align-items:center;gap:9px;margin-top:8px;padding:7px;border-radius:12px;background:#fff8e8}.kp-album-manage-row img{width:48px;height:48px;object-fit:cover;border-radius:9px}.kp-album-manage-row b,.kp-album-manage-row small{display:block}.kp-album-manage-row button{width:38px;height:38px;border:0;border-radius:10px;background:#ead8c3}@media(max-width:420px){#kpAlbumV5Card .kp-v5-buttons{grid-template-columns:1fr!important}#kpAlbumV6Add{grid-column:auto}#kpAlbumV5Dialog .kp-v5-shell>footer{grid-template-columns:repeat(4,1fr)!important}#kpAlbumV5Dialog .kp-v5-shell>footer button{font-size:10px!important}}';document.head.appendChild(s)}
function patchCard(){const c=document.getElementById("kpAlbumV5Card");if(!c)return;const b=c.querySelector(".kp-v5-buttons");if(b&&!document.getElementById("kpAlbumV6Add")){const x=document.createElement("button");x.id="kpAlbumV6Add";x.className="btn secondary";x.type="button";x.textContent="＋ Añadir fotos al álbum";b.appendChild(x)}if(!c.querySelector(".kp-album-next-note")){const n=document.createElement("div");n.className="kp-album-next-note";n.textContent="📸 Podéis guardar varias fotos del mismo lugar sin que una sustituya a otra.";(b||c).insertAdjacentElement("beforebegin",n)}const p=c.querySelector(".row.start .pill"),n=count(),text=`${n} foto${n===1?"":"s"}`;if(p&&p.textContent!==text)p.textContent=text}
function apis(){if(!window.__kpAlbumNextOriginal&&window.KP_ALBUM_V5)window.__kpAlbumNextOriginal={...window.KP_ALBUM_V5};if(!window.__kpAlbumNextOriginal?.html)return false;window.KP_ALBUM_V5={...window.KP_ALBUM_V5,version:"5.0",albumModelVersion:VERSION,html,open,download,share,print,file,stateSignature:sig,multiPhoto:true,verticalPhotosUncropped:true,preservesSupersededEvidence:true};window.KP_ALBUM_EXPERIENCE={...(window.KP_ALBUM_EXPERIENCE||{}),version:"5.0",albumModelVersion:VERSION,html,open,download,share,print,file,multiPhoto:true};if(window.KP_MISSION_PROOF){window.KP_MISSION_PROOF.openAlbum=open;window.KP_MISSION_PROOF.downloadAlbum=download}return true}
function patch(){styles();apis();patchCard()}
document.addEventListener("click",e=>{const id=e.target.closest?.("button")?.id||"";if(id==="kpAlbumV5Open"){e.preventDefault();e.stopImmediatePropagation();open()}else if(id==="kpAlbumV5QuickShare"||id==="kpAlbumV5Share"||id==="kpAlbumV5ShareTop"){e.preventDefault();e.stopImmediatePropagation();share()}else if(id==="kpAlbumV5Download"){e.preventDefault();e.stopImmediatePropagation();download()}else if(id==="kpAlbumV5Pdf"){e.preventDefault();e.stopImmediatePropagation();print()}else if(id==="kpAlbumV5Close"){e.preventDefault();e.stopImmediatePropagation();document.getElementById("kpAlbumV5Dialog")?.close()}else if(id==="kpAlbumV6Add"||id==="kpAlbumV6AddViewer"){e.preventDefault();e.stopImmediatePropagation();openAdd()}},true);
function boot(){archiveReplacedEvidence();patch();new MutationObserver(()=>patch()).observe(document.body,{childList:true,subtree:true});["kp:mission-evidence-local","kp:mission-evidence-sync","kp:album-photos-sync","kp:album-photos-local","kp:statechange","storage","pageshow"].forEach(t=>window.addEventListener(t,()=>{archiveReplacedEvidence();patch();if(dialog?.open)setTimeout(()=>refresh(true),80)}));setInterval(()=>{archiveReplacedEvidence();patch()},2500);window.KP_ALBUM_NEXT={version:VERSION,multiPhoto:true,open,add:openAdd,html,download,print,share,photoCount:count,archiveReplacedEvidence}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
