(() => {
"use strict";
const D=window.KP_DATA,TRIP=D.trip,STORAGE="krakowPocketCoop",PLAYER_KEY="krakowPlayer",VERSION="7.1.0";
const CLOUD={url:"https://ahzmwkztlakejmrvgcdm.supabase.co",key:["sb","publishable","sf-RddHTp5jdFCQOfRBBsQ","PZGKOlxJ"].join("_"),code:"WAWEL-ISMAEL-LAURA",secret:["krakow","2026"].join("")};
const QUEST_IDS=new Set(D.quests.map(q=>q.poi));
const $=id=>document.getElementById(id),$$=(sel,root=document)=>[...root.querySelectorAll(sel)];
const nowIso=()=>new Date().toISOString();
const uid=(prefix="x")=>`${prefix}-${Date.now().toString(36)}-${globalThis.crypto&&typeof crypto.randomUUID==="function"?crypto.randomUUID():Math.random().toString(36).slice(2)}`;
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const eur=n=>`${Number(n||0).toFixed(2).replace(".",",")} €`;
const dateKey=value=>{const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return"";return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const dateTimeLabel=iso=>{const d=new Date(iso);return Number.isNaN(d.getTime())?"fecha desconocida":new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(d)};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const stamp=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)?n:0};
const hav=(a,b)=>{const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),la1=rad(a.lat),la2=rad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
const safeClone=v=>{try{if(typeof structuredClone==="function")return structuredClone(v)}catch{}return JSON.parse(JSON.stringify(v))};
function parseState(raw){try{return JSON.parse(raw||"{}")}catch{return{}}}
function hasState(v){return!!v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length>0}
function applyMissionStatus(s){const generic=(s.visited||[]).filter(id=>!QUEST_IDS.has(id)),mission=[];for(const id of QUEST_IDS){if(s.missionStatus?.[id]?.done)mission.push(id)}s.visited=[...new Set([...generic,...mission])];return s}
function normalizeState(input,{fresh=false}={}){const s=input&&typeof input==="object"&&!Array.isArray(input)?input:{};if(!Array.isArray(s.visited))s.visited=[];if(!Array.isArray(s.budget))s.budget=[0,0,0];if(!Array.isArray(s.expenses))s.expenses=[];if(!Array.isArray(s.memories))s.memories=[];if(!s.config||typeof s.config!=="object"||Array.isArray(s.config))s.config={};if(!s.missionStatus||typeof s.missionStatus!=="object"||Array.isArray(s.missionStatus))s.missionStatus={};if(!Number.isFinite(+s.config.dailyTarget))s.config.dailyTarget=TRIP.dailyTarget;if(!Number.isFinite(+s.config.fixedPaid))s.config.fixedPaid=TRIP.fixedPaid;const migrationStamp=s.updatedAt||"1970-01-01T00:00:00.000Z";if(!s.configUpdatedAt)s.configUpdatedAt=migrationStamp;for(const id of s.visited){if(QUEST_IDS.has(id)&&!s.missionStatus[id])s.missionStatus[id]={done:true,updatedAt:migrationStamp}}if(fresh&&!s.updatedAt)s.updatedAt=nowIso();return applyMissionStatus(s)}
let state=normalizeState(parseState(localStorage.getItem(STORAGE)),{fresh:true});
if(!state.expenses.some(x=>x&&String(x.id||"").startsWith("legacy-day-"))){state.budget.forEach((amount,i)=>{if(+amount>0)state.expenses.push({id:`legacy-day-${i}`,amount:+amount,category:"other",note:"Importado de la versión anterior",by:"Ambos",ts:`2026-08-${String(11+i).padStart(2,"0")}T12:00:00+02:00`,updatedAt:state.updatedAt})})}
let currentPlayer=localStorage.getItem(PLAYER_KEY)==="Laura"?"Laura":"Ismael",map=null,userPos=null,userMarker=null,watchId=null,markers=new Map(),mapFilter="all",geocodeStarted=false,syncTimer=null,pushTimer=null,syncing=false,syncQueued=false,lastSyncAt=null,activeRecommendation=null,reloading=false;
const isMissionDone=id=>state.missionStatus?.[id]?!!state.missionStatus[id].done:state.visited.includes(id),isVisited=id=>QUEST_IDS.has(id)?isMissionDone(id):state.visited.includes(id),activeExpenses=()=>state.expenses.filter(x=>x&&!x.deletedAt),activeMemories=()=>state.memories.filter(x=>x&&!x.deletedAt),totalSpent=()=>activeExpenses().reduce((s,x)=>s+(+x.amount||0),0),missionScore=()=>D.quests.filter(q=>isMissionDone(q.poi)).reduce((s,q)=>s+q.points,0),completedMissions=()=>D.quests.filter(q=>isMissionDone(q.poi)).length,tripDayIndex=(d=new Date())=>D.days.findIndex(x=>x.date===dateKey(d));
const emitRender=()=>window.dispatchEvent(new CustomEvent("kp:render",{detail:{version:VERSION}}));
function persistOnly(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function saveLocal({push=true,touch=true}={}){if(touch)state.updatedAt=nowIso();applyMissionStatus(state);persistOnly();renderAll();if(push)scheduleSync()}
function scheduleSync(){clearTimeout(pushTimer);pushTimer=setTimeout(()=>syncCloud(false),550)}
function toast(message,ms=2300){const t=$("toast");if(!t)return;t.textContent=message;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),ms)}
function setMission(id,done,{silent=false}={}){if(!QUEST_IDS.has(id)||isMissionDone(id)===!!done)return false;state.missionStatus[id]={done:!!done,updatedAt:nowIso()};saveLocal();if(!silent)toast(done?`+${D.quests.find(q=>q.poi===id)?.points||0} escamas 🐉`:"Misión desmarcada");return true}
function markVisited(id){if(QUEST_IDS.has(id))return setMission(id,true);if(state.visited.includes(id))return false;state.visited.push(id);saveLocal();return true}
function undoLastMission(){const ops=Object.entries(state.missionStatus||{}).filter(([id,op])=>QUEST_IDS.has(id)&&op?.done).sort((a,b)=>stamp(b[1].updatedAt)-stamp(a[1].updatedAt));if(!ops.length){toast("No hay misiones completadas que deshacer");return false}return setMission(ops[0][0],false)}
function resetMissions(){if(!completedMissions()){toast("Las misiones ya están a cero");return false}if(!confirm("¿Reiniciar las 12 misiones? Los gastos y recuerdos no se borrarán."))return false;const ts=nowIso();for(const id of QUEST_IDS)state.missionStatus[id]={done:false,updatedAt:ts};saveLocal();toast("Misiones reiniciadas");return true}
function fmtCountdown(ms){if(ms<=0)return"Ahora";const mins=Math.floor(ms/60000),days=Math.floor(mins/1440),hours=Math.floor((mins%1440)/60),m=mins%60;if(days>0)return`${days}d ${hours}h`;if(hours>0)return`${hours}h ${m}m`;return`${m} min`}
function phaseInfo(now=new Date()){const outbound=new Date(TRIP.outbound),start=new Date(TRIP.start),end=new Date(TRIP.end),ret=new Date(TRIP.returnArrive);if(now<new Date(TRIP.stationTarget))return{key:"prep",label:"Preparando Cracovia",title:`Faltan ${fmtCountdown(new Date(TRIP.stationTarget)-now)} para salir hacia Zachodnia`,text:"Hoy compensa preparar mochila, agua y desayuno. La aventura de Cracovia empieza mañana.",day:-1};if(now<outbound)return{key:"station",label:"Día de salida",title:`Bus en ${fmtCountdown(outbound-now)}`,text:"Prioridad: llegar a Warszawa Zachodnia sin prisas.",day:-1};if(now<start)return{key:"transit",label:"En ruta",title:`Cracovia en ${fmtCountdown(start-now)}`,text:"Guardad energía. Al llegar, la primera ruta será Old Town + Wawel.",day:0};const idx=tripDayIndex(now);if(idx>=0&&now<end){const day=D.days[idx];if(idx===2&&now>=new Date("2026-08-13T18:30:00+02:00"))return{key:"return",label:"Modo regreso",title:`Bus en ${fmtCountdown(new Date(TRIP.returnDepart)-now)}`,text:"Nada de rutas largas: toca acercarse a Kraków MDA y dejar margen.",day:idx};return{key:"trip",label:`Día ${idx+1} de 3`,title:day.title,text:day.note,day:idx}}if(now<ret)return{key:"return",label:"Volviendo a Varsovia",title:`Casa en ${fmtCountdown(ret-now)}`,text:"La aventura termina al llegar. Los recuerdos y gastos siguen guardados.",day:2};return{key:"done",label:"Aventura completada",title:"Cracovia ya es parte del viaje",text:"Podéis seguir abriendo el diario, los recuerdos y las estadísticas cuando queráis.",day:2}}
function elapsedTripDays(now=new Date()){const idx=tripDayIndex(now);if(now<new Date(TRIP.start))return 0;if(idx>=0)return idx+1;if(now>new Date(TRIP.end))return 3;return 0}
function targetStats(){const target=+state.config.dailyTarget||21,spent=totalSpent(),elapsed=elapsedTripDays(),targetToDate=target*(elapsed||(new Date()<new Date(TRIP.start)?3:1)),wholeTarget=target*3;return{target,spent,elapsed,targetToDate,wholeTarget,marginToDate:targetToDate-spent,wholeMargin:wholeTarget-spent}}
function renderTimeline(){const idx=tripDayIndex(new Date());$("tripTimeline").innerHTML=D.days.map((day,i)=>`<div class="timeline-day ${i===idx?"current":""}"><div class="day-badge"><span>${esc(day.short.split(" ")[0])}</span><strong>${esc(day.short.split(" ")[1])}</strong></div><div><strong>${esc(day.title)}</strong><div class="small">${esc(day.plan)}</div></div><span class="pill ${i===idx?"green":"gold"}">${i===idx?"hoy":`día ${i+1}`}</span></div>`).join("")}
function renderHome(){const total=D.quests.length,done=completedMissions(),pct=Math.round(done/total*100),stats=targetStats();$("homeSpent").textContent=eur(stats.spent);$("homeMargin").textContent=stats.wholeMargin>=0?eur(stats.wholeMargin):`−${eur(Math.abs(stats.wholeMargin))}`;$("homeMission").textContent=`${done}/${total}`;$("adventureRing").style.setProperty("--p",pct);$("adventureRing").dataset.label=`${pct}%`;$("adventureRing").setAttribute("aria-label",`Progreso de la aventura: ${pct}%`);$("homeMarginLabel").textContent=stats.wholeMargin>=0?"margen del plan":"sobre el objetivo";renderRecommendation(false)}
const poiById=id=>D.pois.find(p=>p.id===id);
function scoreCandidate(p,opts){let score=0,dist=null,ph=phaseInfo(),day=ph.day>=0?D.days[ph.day]:null;if(day&&day.districts.includes(p.district))score+=30;if(!isVisited(p.id))score+=16;if(p.costLevel===0)score+=12;if(opts.mood==="free"&&p.costLevel===0)score+=24;if(opts.mood==="food"&&["food","shop"].includes(p.category))score+=35;if(opts.mood==="rest"&&["rest","walk"].includes(p.category))score+=30;if(opts.mood==="history"&&p.category==="history")score+=28;if(opts.work&&p.duration<=35)score+=18;if(p.duration>opts.minutes)score-=45;if(userPos&&Number.isFinite(p.lat)){dist=hav(userPos,p);score+=clamp(18-dist*8,-35,18)}const budget=targetStats();if(budget.marginToDate<0&&p.costLevel>0)score-=28;if(budget.marginToDate<0&&p.costLevel===0)score+=15;return{score,dist}}
function getRecommendation(){const ph=phaseInfo();if(["prep","station"].includes(ph.key))return{emoji:"🚌",title:"Primero: llegar bien al bus",text:"No compensa empezar nada nuevo. Preparad agua/desayuno y usad la ruta a Warszawa Zachodnia con margen.",action:"Ver ruta a Zachodnia",query:TRIP.stationWarsaw};if(ph.key==="transit")return{emoji:"🧳",title:"Guardad energía",text:"Al llegar a Kraków MDA, id a la base y empezad por el norte del casco antiguo. No hace falta correr.",action:"Ver Kraków MDA",query:TRIP.stationKrakow};if(ph.key==="return")return{emoji:"🚌",title:"Kraków MDA manda ahora",text:"Con el bus cerca, cualquier parada nueva debe acercaros a la estación o poder abandonarse fácilmente.",action:"Ir a Kraków MDA",query:TRIP.stationKrakow};const minutes=+$("freeTime")?.value||60,mood=$("mood")?.value||"explore",work=$("workMode")?.checked||false;let candidates=D.pois.filter(p=>!["base","bus"].includes(p.category));if(mood==="food")candidates=candidates.filter(p=>["food","shop"].includes(p.category));if(mood==="free")candidates=candidates.filter(p=>p.costLevel===0);if(mood==="rest")candidates=candidates.filter(p=>["rest","walk","history"].includes(p.category));if(mood==="history")candidates=candidates.filter(p=>p.category==="history");if(work)candidates=candidates.filter(p=>p.duration<=60&&p.category!=="museum");const ranked=candidates.map(p=>({p,...scoreCandidate(p,{minutes,mood,work})})).sort((a,b)=>b.score-a.score),best=ranked[0]||{p:poiById("rynek"),dist:null},p=best.p,distance=best.dist!=null?(best.dist<1?`${Math.round(best.dist*1000)} m`:`${best.dist.toFixed(1)} km`):null,budget=targetStats(),why=[];if(distance)why.push(`a ${distance}`);if(p.costLevel===0)why.push("gratis");if(!isVisited(p.id))why.push("aún pendiente");if(work)why.push("compatible con trabajo");if(budget.marginToDate<0&&p.costLevel===0)why.push("protege el presupuesto");return{emoji:p.emoji,title:p.name,text:`${p.story} ${why.length?`Ahora encaja porque es ${why.join(", ")}.`:""}`,action:"Ver en mapa",poi:p}}
function renderRecommendation(force=true){if(!$("recommendation"))return;activeRecommendation=getRecommendation();const r=activeRecommendation;$("recEmoji").textContent=r.emoji;$("recTitle").textContent=r.title;$("recText").textContent=r.text;$("recAction").textContent=r.action||"Abrir";$("recSecondary").hidden=!r.poi;if(force)toast("✨ Recomendación actualizada")}
function refreshRecommendation(force=false){renderRecommendation(force);emitRender()}
function openRecommendation(){const r=activeRecommendation||getRecommendation();if(r.poi){openPanel("mapPanel");focusPoi(r.poi.id)}else if(r.query)openMapUrl(mapsSearch(r.query))}
function renderStories(){const ids=["florian","rynek","maria","maius","wawel","dragon","szeroka","bernatek","ghetto","podmuseum"],items=ids.map(id=>poiById(id)).filter(Boolean);$("storyList").innerHTML=items.map((p,i)=>{const discovered=isVisited(p.id);return`<article class="card"><div class="row"><div><div class="smart-kicker">Historia ${i+1}</div><h3>${p.emoji} ${esc(p.name)}</h3></div>${discovered?'<span class="pill green">descubierto</span>':""}</div><p class="small">${esc(p.story)}</p><div class="grid2"><button type="button" class="btn secondary small-btn story-open" data-poi="${p.id}">Leer</button><button type="button" class="btn ghost small-btn story-map" data-poi="${p.id}">Ir allí</button></div></article>`}).join("");$$('.story-open').forEach(b=>b.onclick=()=>openStory(b.dataset.poi));$$('.story-map').forEach(b=>b.onclick=()=>{openPanel("mapPanel");focusPoi(b.dataset.poi)})}
function renderMemories(){const list=activeMemories().slice().sort((a,b)=>stamp(b.ts)-stamp(a.ts));$("memoryCount").textContent=`${list.length} recuerdo${list.length===1?"":"s"}`;$("memoryList").innerHTML=list.length?list.map(m=>`<article class="memory"><div class="row start"><div><div class="meta">${esc(dateTimeLabel(m.ts))} · ${esc(m.by||"Ambos")}${m.place?` · ${esc(m.place)}`:""}</div><strong>${esc(m.title||"Un momento")}</strong></div><button type="button" class="trash memory-delete" data-id="${esc(m.id)}" aria-label="Borrar recuerdo">✕</button></div>${m.note?`<div class="small memory-note">${esc(m.note)}</div>`:""}</article>`).join(""):'<div class="empty">Todavía no habéis guardado ningún recuerdo. Una frase basta.</div>';$$('.memory-delete').forEach(b=>b.onclick=()=>deleteMemory(b.dataset.id))}
function addMemory(e){e.preventDefault();const title=$("memoryTitle").value.trim(),note=$("memoryNote").value.trim(),place=$("memoryPlace").value.trim();if(!title&&!note){toast("Escribe una frase para guardar el recuerdo");return}state.memories.push({id:uid("mem"),title:title||"Un momento",note,place,by:currentPlayer,ts:nowIso(),updatedAt:nowIso()});$("memoryTitle").value="";$("memoryNote").value="";$("memoryPlace").value="";saveLocal();toast("📖 Recuerdo guardado para los dos")}
function deleteMemory(id){const m=state.memories.find(x=>x.id===id);if(!m)return;m.deletedAt=nowIso();m.updatedAt=m.deletedAt;saveLocal();toast("Recuerdo eliminado")}
function categoryTotals(){const totals={};activeExpenses().forEach(x=>totals[x.category]=(totals[x.category]||0)+(+x.amount||0));return totals}
function renderBudget(){const stats=targetStats(),expenses=activeExpenses().slice().sort((a,b)=>stamp(b.ts)-stamp(a.ts));$("budgetToday").textContent=eur(activeExpenses().filter(x=>dateKey(x.ts)===dateKey(new Date())).reduce((s,x)=>s+(+x.amount||0),0));$("budgetTotal").textContent=eur(stats.spent);$("budgetMargin").textContent=stats.wholeMargin>=0?eur(stats.wholeMargin):`−${eur(Math.abs(stats.wholeMargin))}`;$("budgetFixed").textContent=eur(+state.config.fixedPaid||0);$("budgetTargetText").textContent=`Objetivo conjunto: ${eur(stats.target)} al día · ${eur(stats.wholeTarget)} en los 3 días.`;$("budgetMessage").textContent=stats.wholeMargin>=0?`Quedan ${eur(stats.wholeMargin)} del objetivo variable total. Lo que no gastéis un día queda disponible para los siguientes.`:`Habéis superado el objetivo variable en ${eur(Math.abs(stats.wholeMargin))}. Es una referencia, no una obligación.`;const pct=stats.wholeTarget?clamp(stats.spent/stats.wholeTarget*100,0,100):0,bar=$("budgetBar");bar.style.width=`${pct}%`;bar.classList.toggle("over-budget",stats.spent>stats.wholeTarget);const totals=categoryTotals(),max=Math.max(1,...Object.values(totals));$("categoryBars").innerHTML=Object.entries(D.expenseCategories).map(([key,label])=>{const val=totals[key]||0;return`<div class="cat-row"><span>${label}</span><div class="cat-track"><i style="width:${val/max*100}%"></i></div><strong>${val?eur(val):"—"}</strong></div>`}).join("");$("expenseList").innerHTML=expenses.length?expenses.slice(0,18).map(x=>`<div class="expense"><div><strong>${esc(D.expenseCategories[x.category]||D.expenseCategories.other)}</strong><div class="small">${esc(x.note||dateTimeLabel(x.ts))} · ${esc(x.by||"Ambos")}</div></div><div class="expense-amount">${eur(x.amount)}</div><button type="button" class="trash expense-delete" data-id="${esc(x.id)}" aria-label="Borrar gasto">✕</button></div>`).join(""):'<div class="empty">Aún no habéis registrado gastos variables.</div>';$$('.expense-delete').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.id))}
function addExpense(e){e.preventDefault();const raw=$("expenseAmount").value.trim().replace(/\s/g,"").replace(",","."),amount=+raw;if(!Number.isFinite(amount)||amount<=0){toast("Introduce un importe válido");return}state.expenses.push({id:uid("exp"),amount:+amount.toFixed(2),category:$("expenseCategory").value,note:$("expenseNote").value.trim(),by:currentPlayer,ts:nowIso(),updatedAt:nowIso()});$("expenseAmount").value="";$("expenseNote").value="";saveLocal();toast(`💰 ${eur(amount)} añadido al gasto conjunto`)}
function deleteExpense(id){const x=state.expenses.find(e=>e.id===id);if(!x)return;x.deletedAt=nowIso();x.updatedAt=x.deletedAt;saveLocal();toast("Gasto eliminado")}
function showMapFallback(){const el=$("map");if(!el)return;el.classList.add("map-unavailable");el.textContent=navigator.onLine?"El mapa no se ha podido cargar. Las rutas y lugares siguen disponibles desde las fichas.":"Mapa no disponible sin conexión. El resto de la aventura sigue funcionando sin red."}
function initMap(){if(map)return;if(!window.L){showMapFallback();return}const el=$("map");if(el){el.classList.remove("map-unavailable");el.textContent=""}map=L.map("map",{zoomControl:false}).setView([50.0617,19.9373],14);L.control.zoom({position:"topright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);addPoiMarkers();updateNear();if(!geocodeStarted){geocodeStarted=true;geocodeMissing()}}
function iconFor(p){return L.divIcon({className:"",html:`<div class="marker ${isVisited(p.id)?"done":""}">${p.emoji}</div>`,iconSize:[36,36],iconAnchor:[18,18]})}
function markerVisible(p){if(mapFilter==="all")return true;if(mapFilter==="free")return p.costLevel===0;if(mapFilter==="pending")return!isVisited(p.id);return p.category===mapFilter}
function addPoiMarkers(){if(!map)return;D.pois.forEach(p=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return;let m=markers.get(p.id);if(!m){m=L.marker([p.lat,p.lon],{icon:iconFor(p)});m.bindPopup(`<b>${p.emoji} ${esc(p.name)}</b><br><span class="kp-popup-meta">${esc(p.cost)} · ${p.duration} min</span><br><button type="button" data-open-poi="${p.id}" class="kp-map-popup-btn">Ver historia</button>`);m.on("popupopen",e=>{const btn=e.popup.getElement()?.querySelector("[data-open-poi]");if(btn)btn.onclick=()=>openStory(p.id)});markers.set(p.id,m)}else m.setIcon(iconFor(p));if(markerVisible(p)){if(!map.hasLayer(m))m.addTo(map)}else if(map.hasLayer(m))map.removeLayer(m)})}
async function geocodeMissing(){let cache={};try{cache=JSON.parse(localStorage.getItem("kpGeoCache")||"{}")}catch{}for(const p of D.pois.filter(x=>!Number.isFinite(x.lat)||!Number.isFinite(x.lon))){if(cache[p.id]){p.lat=cache[p.id].lat;p.lon=cache[p.id].lon;addPoiMarkers();continue}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(p.mapsQuery)}`,{headers:{"Accept-Language":"es"}});if(!r.ok)continue;const j=await r.json();if(j[0]){p.lat=+j[0].lat;p.lon=+j[0].lon;cache[p.id]={lat:p.lat,lon:p.lon};localStorage.setItem("kpGeoCache",JSON.stringify(cache));addPoiMarkers()}}catch{}await new Promise(r=>setTimeout(r,1100))}updateNear()}
function focusPoi(id){initMap();const p=poiById(id);if(!p)return;if(map&&Number.isFinite(p.lat)){map.setView([p.lat,p.lon],16);setTimeout(()=>markers.get(id)?.openPopup(),220)}else openMapUrl(mapsSearch(p.mapsQuery))}
function locate(){if(!navigator.geolocation){toast("Este navegador no ofrece ubicación");return}$("locateBtn").disabled=true;$("locateBtn").textContent="Buscando…";if(watchId!=null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(pos=>{userPos={lat:pos.coords.latitude,lon:pos.coords.longitude};initMap();if(map&&window.L){if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([userPos.lat,userPos.lon],{icon:L.divIcon({className:"",html:'<div class="loc-dot"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map).bindPopup("📍 Estáis aquí")}$("locateBtn").disabled=false;$("locateBtn").textContent="✓ Ubicación activa";$("privacyGps").textContent="GPS activo solo en este dispositivo; la posición no se sincroniza.";updateNear();refreshRecommendation(false)},()=>{$("locateBtn").disabled=false;$("locateBtn").textContent="📍 Activar ubicación";toast("Safari necesita permiso de ubicación")},{enableHighAccuracy:true,maximumAge:15000,timeout:12000})}
function updateNear(){if(!$("nearList"))return;let list=D.pois.filter(p=>Number.isFinite(p.lat)&&!["base","bus"].includes(p.category));if(userPos)list=list.map(p=>({...p,_dist:hav(userPos,p)})).sort((a,b)=>a._dist-b._dist);else{const idx=phaseInfo().day,districts=idx>=0?D.days[idx].districts:["old"];list=list.sort((a,b)=>(districts.includes(b.district)?1:0)-(districts.includes(a.district)?1:0))}$("nearList").innerHTML=list.slice(0,7).map(p=>`<article class="poi"><div class="row start"><div><div class="poi-name">${p.emoji} ${esc(p.name)}</div><div class="small">${esc(p.cost)} · ${p.duration} min</div></div><div class="distance">${p._dist!=null?(p._dist<1?`${Math.round(p._dist*1000)} m`:`${p._dist.toFixed(1)} km`):esc(p.district)}</div></div><div class="grid2 compact-top-sm"><button type="button" class="btn secondary small-btn near-story" data-poi="${p.id}">Historia</button><button type="button" class="btn ghost small-btn near-go" data-poi="${p.id}">Ver ruta</button></div></article>`).join("");$$('.near-story').forEach(b=>b.onclick=()=>openStory(b.dataset.poi));$$('.near-go').forEach(b=>b.onclick=()=>openDirections(poiById(b.dataset.poi)))}
const mapsSearch=query=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
function openMapUrl(url){if(url&&url!=="#")location.assign(url)}
function openDirections(p){if(!p)return;if(userPos&&Number.isFinite(p.lat))openMapUrl(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(userPos.lat+","+userPos.lon)}&destination=${encodeURIComponent(p.lat+","+p.lon)}&travelmode=walking`);else openMapUrl(mapsSearch(p.mapsQuery))}
function openStory(id){const p=poiById(id),dialog=$("storyDialog");if(!p||!dialog)return;$("storyDialogTitle").textContent=`${p.emoji} ${p.name}`;$("storyDialogText").textContent=p.story;$("storyDialogMeta").textContent=`${p.cost} · ${p.duration} min · ${D.categories[p.category]?.label||p.category}`;$("storyGo").onclick=()=>openDirections(p);const discovered=isVisited(id);$("storyMark").textContent=discovered?"✓ Descubierto":"Marcar descubierto";$("storyMark").disabled=discovered;$("storyMark").onclick=()=>{if(!isVisited(id)){markVisited(id);toast("✨ Lugar descubierto")}dialog.close()};if(dialog.open)dialog.close();dialog.showModal()}
function setMapFilter(filter){mapFilter=filter;$$('.chip[data-filter]').forEach(c=>{const active=c.dataset.filter===filter;c.classList.toggle("active",active);c.setAttribute("aria-pressed",String(active))});addPoiMarkers();updateNear()}
function renderMapFilters(){const filters=[["all","Todo"],["free","🆓 Gratis"],["history","🏛️ Historia"],["food","🍲 Comer"],["rest","🌿 Pausa"],["pending","✨ Pendientes"]];$("mapFilters").innerHTML=filters.map(([key,label])=>`<button type="button" class="chip ${key==="all"?"active":""}" aria-pressed="${key==="all"}" data-filter="${key}">${label}</button>`).join("");$$('.chip[data-filter]').forEach(c=>c.onclick=()=>setMapFilter(c.dataset.filter))}
function openPanel(id){if(!$(id))return;$$('.tab').forEach(x=>x.classList.toggle("active",x.dataset.panel===id));$$('.panel').forEach(x=>x.classList.toggle("active",x.id===id));history.replaceState(null,"",id==="home"?location.pathname:`?tab=${encodeURIComponent(id)}`);requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:"auto"}));if(id==="mapPanel"){initMap();setTimeout(()=>map?.invalidateSize(),120);updateNear()}emitRender()}
function renderDiarySegment(which){$$('.segment button').forEach(x=>{const active=x.dataset.diary===which;x.classList.toggle("active",active);x.setAttribute("aria-pressed",String(active))});$$('.subpanel').forEach(x=>x.classList.toggle("active",x.id===`diary-${which}`))}
function setValueIfIdle(id,value){const el=$(id);if(el&&document.activeElement!==el&&String(el.value)!==String(value))el.value=value}
function openSettings(){const dialog=$("settingsSheet");if(!dialog)return;renderSettings();if(!dialog.open)dialog.showModal()}
function renderSettings(){setValueIfIdle("playerSelect",currentPlayer);setValueIfIdle("dailyTarget",+state.config.dailyTarget||21);setValueIfIdle("fixedPaid",+state.config.fixedPaid||0);$("settingsVersion").textContent=`Kraków Pocket · v${VERSION}`;$("syncCode").textContent=CLOUD.code;$("lastSync").textContent=lastSyncAt?`Última sincronización: ${dateTimeLabel(lastSyncAt)}`:navigator.onLine?"Todavía conectando…":"Sin conexión; los cambios se guardan localmente."}
function renderAll(){renderHome();renderTimeline();renderStories();renderMemories();renderBudget();renderSettings();addPoiMarkers();emitRender()}
function mergeRecords(local=[],remote=[]){const m=new Map();for(const item of [...remote,...local]){if(!item?.id)continue;const prev=m.get(item.id);if(!prev||stamp(item.updatedAt||item.ts)>=stamp(prev.updatedAt||prev.ts))m.set(item.id,item)}return[...m.values()]}
function mergeMissionStatus(a={},b={}){const out={};for(const src of [a,b])for(const [id,op] of Object.entries(src||{})){if(!QUEST_IDS.has(id)||!op)continue;const prev=out[id];if(!prev||stamp(op.updatedAt)>=stamp(prev.updatedAt))out[id]={done:!!op.done,updatedAt:op.updatedAt||"1970-01-01T00:00:00.000Z"}}return out}
function mergeState(remote){const local=normalizeState(safeClone(state),{fresh:true}),r=normalizeState(safeClone(remote)),localConfigNewer=stamp(local.configUpdatedAt)>=stamp(r.configUpdatedAt),out={...r,...local};out.missionStatus=mergeMissionStatus(r.missionStatus,local.missionStatus);out.expenses=mergeRecords(local.expenses,r.expenses);out.memories=mergeRecords(local.memories,r.memories);out.config=localConfigNewer?(local.config||{}):(r.config||local.config||{});out.configUpdatedAt=localConfigNewer?local.configUpdatedAt:r.configUpdatedAt;out.budget=Array.isArray(local.budget)?local.budget:(r.budget||[]);out.visited=[...new Set([...(r.visited||[]).filter(id=>!QUEST_IDS.has(id)),...(local.visited||[]).filter(id=>!QUEST_IDS.has(id))])];out.updatedAt=new Date(Math.max(stamp(local.updatedAt),stamp(r.updatedAt))||Date.now()).toISOString();return applyMissionStatus(out)}
function stateSignature(s){const n=normalizeState(safeClone(s)),sortById=a=>[...(a||[])].sort((x,y)=>String(x?.id||"").localeCompare(String(y?.id||"")));return JSON.stringify({visited:[...(n.visited||[])].sort(),missionStatus:n.missionStatus||{},expenses:sortById(n.expenses),memories:sortById(n.memories),config:n.config||{},configUpdatedAt:n.configUpdatedAt||"",budget:n.budget||[]})}
function syncUi(mode,msg){const ok=mode==="ok",busy=mode==="busy";$("syncDot").className=`sync-dot ${ok?"ok":busy?"busy":""}`;$("syncText").textContent=ok?"sincronizados":busy?"sincronizando…":"sin conexión";$("settingsSync").textContent=ok?"☁️ partida compartida":busy?"☁️ conectando":"☁️ sin conexión";$("settingsSync").className=`pill ${ok?"green":busy?"gold":"red"}`;if(msg)$("syncHelp").textContent=msg}
async function rpc(name,body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${CLOUD.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":CLOUD.key},body:JSON.stringify(body),signal:controller.signal}),text=await r.text();if(!r.ok){let detail=text;try{const j=JSON.parse(text);detail=j.message||j.error||text}catch{}throw new Error(`HTTP ${r.status}: ${detail||"Error de Supabase"}`)}return text?JSON.parse(text):null}catch(e){if(e?.name==="AbortError")throw new Error("Tiempo de espera agotado");throw e}finally{clearTimeout(timeout)}}
async function syncCloud(manual=false){if(!navigator.onLine){syncUi("error","Sin conexión. Los cambios se guardan en este iPhone y se enviarán al volver la red.");return}if(syncing){syncQueued=true;return}syncing=true;syncUi("busy",manual?"Reconectando…":"Sincronizando la partida…");try{const before=stateSignature(state),raw=await rpc("adventure_get",{p_code:CLOUD.code,p_secret:CLOUD.secret}),remoteOk=hasState(raw),remote=remoteOk?normalizeState(raw):null,merged=remoteOk?mergeState(remote):normalizeState(safeClone(state),{fresh:true}),mergedSig=stateSignature(merged);if(!remoteOk||stateSignature(remote)!==mergedSig)await rpc("adventure_put",{p_code:CLOUD.code,p_secret:CLOUD.secret,p_state:merged});if(before!==mergedSig){state=merged;persistOnly();renderAll()}lastSyncAt=nowIso();syncUi("ok","Los cambios de ambos iPhone se actualizan automáticamente.");renderSettings();if(manual)toast("☁️ Sincronización activa")}catch(e){console.error("Kraków Pocket sync",e);syncUi("error",`No se pudo sincronizar: ${e.message||e}`)}finally{syncing=false;if(syncQueued){syncQueued=false;setTimeout(()=>syncCloud(false),80)}}
async function startSync(manual=false){clearInterval(syncTimer);await syncCloud(manual);syncTimer=setInterval(()=>{if(document.visibilityState==="visible")syncCloud(false)},5000)}
function buildSummary(){const memories=activeMemories().slice().sort((a,b)=>stamp(b.ts)-stamp(a.ts)),lines=["Kraków Pocket · Ismael + Laura",`Misiones: ${completedMissions()}/${D.quests.length} · ${missionScore()} escamas`,`Gasto variable: ${eur(totalSpent())}`,`Recuerdos guardados: ${memories.length}`];if(memories.length){lines.push("","Últimos recuerdos:");memories.slice(0,5).forEach(m=>lines.push(`• ${m.title||"Recuerdo"}${m.place?` · ${m.place}`:""}${m.note?`: ${m.note}`:""}`))}lines.push("",`${location.origin}${location.pathname}`);return lines.join("\n")}
async function shareSummary(){const text=buildSummary();try{if(navigator.share){await navigator.share({title:"Kraków Pocket · nuestro viaje",text});return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);toast("Resumen copiado al portapapeles");return}prompt("Copia vuestro resumen:",text)}catch(e){if(e?.name!=="AbortError")prompt("Copia vuestro resumen:",text)}}
function registerPwa(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.register("./sw.js").then(reg=>{const banner=$("updateBanner"),button=$("applyUpdate");const hide=()=>{if(banner)banner.classList.remove("show")},show=()=>{if(banner)banner.classList.add("show");if(button){button.disabled=false;button.textContent="Actualizar"}},activate=()=>{if(!reg.waiting)return;if(button){button.disabled=true;button.textContent="Actualizando…"}reg.waiting.postMessage({type:"SKIP_WAITING"})};button?.addEventListener("click",activate);const inspect=()=>reg.waiting&&navigator.serviceWorker.controller?show():hide();inspect();reg.addEventListener("updatefound",()=>{const worker=reg.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed")inspect()})});navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloading)return;reloading=true;hide();setTimeout(()=>location.reload(),80)});reg.update().catch(()=>{});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")reg.update().catch(()=>{})})}).catch(()=>{})}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$("closeSettings").onclick=()=>$("settingsSheet").close();$("storyClose").onclick=()=>$("storyDialog").close();$("locateBtn").onclick=locate;$("recommendBtn").onclick=()=>refreshRecommendation(true);$("recAction").onclick=openRecommendation;$("recSecondary").onclick=()=>activeRecommendation?.poi&&openStory(activeRecommendation.poi.id);$("quickMap").onclick=()=>openPanel("mapPanel");$("quickExpense").onclick=()=>{openPanel("budget");setTimeout(()=>$("expenseAmount")?.focus({preventScroll:true}),150)};$("quickMemory").onclick=()=>{openPanel("diary");renderDiarySegment("memories");setTimeout(()=>$("memoryTitle")?.focus({preventScroll:true}),150)};$("quickRest").onclick=()=>{$("mood").value="rest";refreshRecommendation(true)};$("freeTime").onchange=()=>refreshRecommendation(false);$("mood").onchange=()=>refreshRecommendation(false);$("workMode").onchange=()=>refreshRecommendation(true);$("expenseForm").onsubmit=addExpense;$("memoryForm").onsubmit=addMemory;$$('.segment button').forEach(b=>b.onclick=()=>renderDiarySegment(b.dataset.diary));$("refreshNear").onclick=updateNear;$("playerSelect").onchange=e=>{currentPlayer=e.target.value==="Laura"?"Laura":"Ismael";localStorage.setItem(PLAYER_KEY,currentPlayer);renderAll();toast(`Este iPhone: ${currentPlayer}`)};$("dailyTarget").onchange=e=>{state.config.dailyTarget=Math.max(0,+e.target.value||21);state.configUpdatedAt=nowIso();saveLocal()};$("fixedPaid").onchange=e=>{state.config.fixedPaid=Math.max(0,+e.target.value||0);state.configUpdatedAt=nowIso();saveLocal()};$("reconnectCloud").onclick=()=>startSync(true);$("homeMapBtn").onclick=()=>openMapUrl(mapsSearch(TRIP.baseWarsaw));$("zachodniaBtn").onclick=()=>openMapUrl(mapsSearch(TRIP.stationWarsaw));$("shareSummary").onclick=shareSummary;window.addEventListener("online",()=>{startSync(false);if($("mapPanel")?.classList.contains("active")&&!map)initMap()});window.addEventListener("offline",()=>syncUi("error","Sin conexión. La partida sigue funcionando y se sincronizará después."));window.addEventListener("pageshow",()=>{if(navigator.onLine)syncCloud(false)});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&navigator.onLine)syncCloud(false)})}
function init(){bind();renderMapFilters();renderDiarySegment("stories");renderAll();const requested=new URLSearchParams(location.search).get("tab");if(requested&&$(requested))openPanel(requested);startSync(false);registerPwa();setInterval(()=>{if(document.visibilityState!=="visible")return;renderHome();renderTimeline();emitRender()},30000)}
window.KP_APP={version:VERSION,getState:()=>safeClone(state),getPlayer:()=>currentPlayer,isMissionDone,setMission,undoLastMission,resetMissions,openPanel,openStory,openSettings,shareSummary,refresh:renderAll};
document.addEventListener("DOMContentLoaded",init,{once:true});
})();