(() => {
"use strict";
const D=window.KP_DATA,TRIP=D.trip,STORAGE="krakowPocketCoop",PLAYER_KEY="krakowPlayer",VERSION=D.version;
const CLOUD={url:"https://ahzmwkztlakejmrvgcdm.supabase.co",key:"sb_publishable_sf-RddHTp5jdFCQOfRBBsQ_PZGKOIxJ",code:"WAWEL-ISMAEL-LAURA",secret:"krakow2026"};
const $=id=>document.getElementById(id),$$=(sel,root=document)=>[...root.querySelectorAll(sel)];
const nowIso=()=>new Date().toISOString();
const uid=(prefix="x")=>`${prefix}-${Date.now().toString(36)}-${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}`;
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const eur=n=>`${Number(n||0).toFixed(2).replace(".",",")} €`;
const dateKey=value=>{const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return"";return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const dateTimeLabel=iso=>new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hav=(a,b)=>{const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),la1=rad(a.lat),la2=rad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))};
let state;try{state=JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{state={}}
if(!Array.isArray(state.visited))state.visited=[];if(!Array.isArray(state.budget))state.budget=[0,0,0];if(!Array.isArray(state.expenses))state.expenses=[];if(!Array.isArray(state.memories))state.memories=[];if(!state.config)state.config={};
if(!Number.isFinite(+state.config.dailyTarget))state.config.dailyTarget=TRIP.dailyTarget;if(!Number.isFinite(+state.config.fixedPaid))state.config.fixedPaid=TRIP.fixedPaid;if(!state.updatedAt)state.updatedAt=nowIso();
if(!state.expenses.some(x=>x&&String(x.id||"").startsWith("legacy-day-"))){state.budget.forEach((amount,i)=>{if(+amount>0)state.expenses.push({id:`legacy-day-${i}`,amount:+amount,category:"other",note:"Importado de la versión anterior",by:"Ambos",ts:`2026-08-${String(11+i).padStart(2,"0")}T12:00:00+02:00`,updatedAt:state.updatedAt})})}
let currentPlayer=localStorage.getItem(PLAYER_KEY)||"Ismael",map=null,userPos=null,userMarker=null,watchId=null,markers=new Map(),mapFilter="all",syncTimer=null,pushTimer=null,syncing=false,lastSyncAt=null,activeRecommendation=null;
const activeExpenses=()=>state.expenses.filter(x=>x&&!x.deletedAt),activeMemories=()=>state.memories.filter(x=>x&&!x.deletedAt),totalSpent=()=>activeExpenses().reduce((s,x)=>s+(+x.amount||0),0),missionScore=()=>D.quests.filter(q=>state.visited.includes(q.poi)).reduce((s,q)=>s+q.points,0),completedMissions=()=>D.quests.filter(q=>state.visited.includes(q.poi)).length,tripDayIndex=(d=new Date())=>D.days.findIndex(x=>x.date===dateKey(d));
function persistState(){localStorage.setItem(STORAGE,JSON.stringify(state));try{const saved=JSON.parse(localStorage.getItem(STORAGE)||"{}");if(saved&&typeof saved==="object")state=saved}catch{}}
function saveLocal({push=true,touch=true}={}){if(touch)state.updatedAt=nowIso();persistState();renderAll();if(push)schedulePush()}
function schedulePush(){clearTimeout(pushTimer);pushTimer=setTimeout(()=>pushCloud().catch(()=>{}),650)}
function toast(message,ms=2300){const t=$("toast");if(!t)return;t.textContent=message;t.style.display="block";clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display="none",ms)}
function fmtCountdown(ms){if(ms<=0)return"Ahora";const mins=Math.floor(ms/60000),days=Math.floor(mins/1440),hours=Math.floor((mins%1440)/60),m=mins%60;if(days>0)return`${days}d ${hours}h`;if(hours>0)return`${hours}h ${m}m`;return`${m} min`}
function phaseInfo(now=new Date()){const outbound=new Date(TRIP.outbound),start=new Date(TRIP.start),end=new Date(TRIP.end),ret=new Date(TRIP.returnArrive);if(now<new Date(TRIP.stationTarget))return{key:"prep",label:"Preparando Cracovia",title:`Faltan ${fmtCountdown(new Date(TRIP.stationTarget)-now)} para salir hacia Zachodnia`,text:"Hoy compensa preparar mochila, agua y desayuno. La aventura de Cracovia empieza mañana.",day:-1};if(now<outbound)return{key:"station",label:"Día de salida",title:`Bus en ${fmtCountdown(outbound-now)}`,text:"Prioridad: llegar a Warszawa Zachodnia sin prisas.",day:-1};if(now<start)return{key:"transit",label:"En ruta",title:`Cracovia en ${fmtCountdown(start-now)}`,text:"Guardad energía. Al llegar, la primera ruta será Old Town + Wawel.",day:0};const idx=tripDayIndex(now);if(idx>=0&&now<end){const day=D.days[idx];if(idx===2&&now>=new Date("2026-08-13T18:30:00+02:00"))return{key:"return",label:"Modo regreso",title:`Bus en ${fmtCountdown(new Date(TRIP.returnDepart)-now)}`,text:"Nada de rutas largas: toca acercarse a Kraków MDA y dejar margen.",day:idx};return{key:"trip",label:`Día ${idx+1} de 3`,title:day.title,text:day.note,day:idx}}if(now<ret)return{key:"return",label:"Volviendo a Varsovia",title:`Casa en ${fmtCountdown(ret-now)}`,text:"La aventura termina al llegar. Los recuerdos y gastos siguen guardados.",day:2};return{key:"done",label:"Aventura completada",title:"Cracovia ya es parte del viaje",text:"Podéis seguir abriendo el diario, los recuerdos y las estadísticas cuando queráis.",day:2}}
function elapsedTripDays(now=new Date()){const idx=tripDayIndex(now);if(now<new Date(TRIP.start))return 0;if(idx>=0)return idx+1;if(now>new Date(TRIP.end))return 3;return 0}
function targetStats(){const target=+state.config.dailyTarget||21,spent=totalSpent(),elapsed=elapsedTripDays(),targetToDate=target*(elapsed||(new Date()<new Date(TRIP.start)?3:1)),wholeTarget=target*3;return{target,spent,elapsed,targetToDate,wholeTarget,marginToDate:targetToDate-spent,wholeMargin:wholeTarget-spent}}
function renderHero(){const ph=phaseInfo();$("phaseLabel").textContent=ph.label;$("heroTitle").textContent=ph.title;$("heroSub").textContent=ph.text;$("heroScore").textContent=`${missionScore()} 🐉`;$("heroSpend").textContent=eur(totalSpent());$("heroTarget").textContent=`${(+state.config.dailyTarget||21).toFixed(0)} €/día`;$("heroPlayer").textContent=currentPlayer==="Laura"?"🔎 Laura":"🧭 Ismael";$("heroSync").textContent=lastSyncAt?"☁️ juntos":"☁️ conectando"}
function renderTimeline(){const idx=tripDayIndex(new Date());$("tripTimeline").innerHTML=D.days.map((day,i)=>`<div class="timeline-day ${i===idx?"current":""}"><div class="day-badge"><span>${esc(day.short.split(" ")[0])}</span><strong>${esc(day.short.split(" ")[1])}</strong></div><div><strong>${esc(day.title)}</strong><div class="small">${esc(day.plan)}</div></div><span class="pill ${i===idx?"green":"gold"}">${i===idx?"hoy":`día ${i+1}`}</span></div>`).join("")}
function renderHome(){const total=D.quests.length,done=completedMissions(),pct=Math.round(done/total*100),stats=targetStats();$("homeSpent").textContent=eur(stats.spent);$("homeMargin").textContent=stats.wholeMargin>=0?eur(stats.wholeMargin):`−${eur(Math.abs(stats.wholeMargin))}`;$("homeMission").textContent=`${done}/${total}`;$("adventureRing").style.setProperty("--p",pct);$("adventureRing").dataset.label=`${pct}%`;$("homeMarginLabel").textContent=stats.wholeMargin>=0?"margen del plan":"sobre el objetivo";renderRecommendation(false)}
const poiById=id=>D.pois.find(p=>p.id===id),questByPoi=id=>D.quests.find(q=>q.poi===id);
function scoreCandidate(p,opts){let score=0;const ph=phaseInfo(),dayIdx=ph.day,day=dayIdx>=0?D.days[dayIdx]:null;if(day&&day.districts.includes(p.district))score+=30;if(!state.visited.includes(p.id))score+=16;if(p.costLevel===0)score+=12;if(opts.mood==="free"&&p.costLevel===0)score+=24;if(opts.mood==="food"&&["food","shop"].includes(p.category))score+=35;if(opts.mood==="rest"&&["rest","walk"].includes(p.category))score+=30;if(opts.mood==="history"&&p.category==="history")score+=28;if(opts.work&&p.duration<=35)score+=18;if(p.duration>opts.minutes)score-=45;if(userPos&&Number.isFinite(p.lat)){const dist=hav(userPos,p);p._dist=dist;score+=clamp(18-dist*8,-35,18)}const budget=targetStats();if(budget.marginToDate<0&&p.costLevel>0)score-=28;if(budget.marginToDate<0&&p.costLevel===0)score+=15;return score}
function getRecommendation(){const ph=phaseInfo();if(["prep","station"].includes(ph.key))return{emoji:"🚌",title:"Primero: llegar bien al bus",text:"No compensa empezar nada nuevo. Preparad agua/desayuno y usad la ruta a Warszawa Zachodnia con margen.",action:"Ver ruta a Zachodnia",query:TRIP.stationWarsaw};if(ph.key==="transit")return{emoji:"🧳",title:"Guardad energía",text:"Al llegar a Kraków MDA, id a la base y empezad por el norte del casco antiguo. No hace falta correr.",action:"Ver Kraków MDA",query:TRIP.stationKrakow};if(ph.key==="return")return{emoji:"🚌",title:"Kraków MDA manda ahora",text:"Con el bus cerca, cualquier parada nueva debe acercaros a la estación o poder abandonarse fácilmente.",action:"Ir a Kraków MDA",query:TRIP.stationKrakow};const minutes=+$("freeTime")?.value||60,mood=$("mood")?.value||"explore",work=$("workMode")?.checked||false;let candidates=D.pois.filter(p=>!["base","bus"].includes(p.category));if(mood==="food")candidates=candidates.filter(p=>["food","shop"].includes(p.category));if(mood==="free")candidates=candidates.filter(p=>p.costLevel===0);if(mood==="rest")candidates=candidates.filter(p=>["rest","walk","history"].includes(p.category));if(mood==="history")candidates=candidates.filter(p=>p.category==="history");if(work)candidates=candidates.filter(p=>p.duration<=60&&p.category!=="museum");candidates.forEach(p=>p._score=scoreCandidate(p,{minutes,mood,work}));candidates.sort((a,b)=>b._score-a._score);const p=candidates[0]||poiById("rynek"),distance=p._dist!=null?(p._dist<1?`${Math.round(p._dist*1000)} m`:`${p._dist.toFixed(1)} km`):null,budget=targetStats();let why=[];if(distance)why.push(`a ${distance}`);if(p.costLevel===0)why.push("gratis");if(!state.visited.includes(p.id))why.push("aún pendiente");if(work)why.push("compatible con trabajo");if(budget.marginToDate<0&&p.costLevel===0)why.push("protege el presupuesto");return{emoji:p.emoji,title:p.name,text:`${p.story} ${why.length?`Ahora encaja porque es ${why.join(", ")}.`:""}`,action:"Ver en mapa",poi:p}}
function renderRecommendation(force=true){if(!$("recommendation"))return;activeRecommendation=getRecommendation();const r=activeRecommendation;$("recEmoji").textContent=r.emoji;$("recTitle").textContent=r.title;$("recText").textContent=r.text;$("recAction").textContent=r.action||"Abrir";$("recSecondary").style.display=r.poi?"block":"none";if(force)toast("✨ Recomendación actualizada")}
function openRecommendation(){const r=activeRecommendation||getRecommendation();if(r.poi){openPanel("mapPanel");focusPoi(r.poi.id)}else if(r.query)window.open(mapsSearch(r.query),"_blank")}
function renderQuests(){const total=D.quests.length,done=completedMissions();$("questCount").textContent=`${done} / ${total}`;$("questBar").style.width=`${done/total*100}%`;$("questList").innerHTML=D.quests.map((q,i)=>{const p=poiById(q.poi),isDone=state.visited.includes(q.poi);return`<article class="card quest ${isDone?"done":""}"><div class="row start"><div><div class="smart-kicker">Misión ${i+1} · 🤝 juntos</div><h3>${p.emoji} ${esc(q.title)}</h3></div><span class="quest-points">+${q.points}</span></div><p class="small">${esc(q.text)}</p><div class="grid2"><button class="btn secondary small-btn q-context" data-poi="${p.id}">Contexto</button><button class="btn ${isDone?"secondary":"green"} small-btn q-done" data-poi="${p.id}">${isDone?"✓ Completada":"Completar"}</button></div></article>`}).join("");$$('.q-context').forEach(b=>b.onclick=()=>openStory(b.dataset.poi));$$('.q-done').forEach(b=>b.onclick=()=>{const id=b.dataset.poi;if(state.visited.includes(id))return;state.visited.push(id);saveLocal();toast(`+${questByPoi(id)?.points||0} escamas 🐉`)})}
function renderStories(){const ids=["florian","rynek","maria","maius","wawel","dragon","szeroka","bernatek","ghetto","podmuseum"];$("storyList").innerHTML=ids.map((id,i)=>{const p=poiById(id),done=state.visited.includes(id);return`<article class="card"><div class="row"><div><div class="smart-kicker">Historia ${i+1}</div><h3>${p.emoji} ${esc(p.name)}</h3></div>${done?'<span class="pill green">descubierto</span>':""}</div><p class="small">${esc(p.story)}</p><div class="grid2"><button class="btn secondary small-btn story-open" data-poi="${id}">Leer</button><button class="btn ghost small-btn story-map" data-poi="${id}">Ir allí</button></div></article>`}).join("");$$('.story-open').forEach(b=>b.onclick=()=>openStory(b.dataset.poi));$$('.story-map').forEach(b=>b.onclick=()=>{openPanel("mapPanel");focusPoi(b.dataset.poi)})}
function renderMemories(){const list=activeMemories().slice().sort((a,b)=>new Date(b.ts)-new Date(a.ts));$("memoryCount").textContent=`${list.length} recuerdo${list.length===1?"":"s"}`;$("memoryList").innerHTML=list.length?list.map(m=>`<article class="memory"><div class="row start"><div><div class="meta">${esc(dateTimeLabel(m.ts))} · ${esc(m.by||"Ambos")}${m.place?` · ${esc(m.place)}`:""}</div><strong>${esc(m.title||"Un momento")}</strong></div><button class="trash memory-delete" data-id="${esc(m.id)}" aria-label="Borrar">✕</button></div>${m.note?`<div class="small" style="margin-top:5px">${esc(m.note)}</div>`:""}</article>`).join(""):'<div class="empty">Todavía no habéis guardado ningún recuerdo. Una frase basta.</div>';$$('.memory-delete').forEach(b=>b.onclick=()=>deleteMemory(b.dataset.id))}
function addMemory(e){e.preventDefault();const title=$("memoryTitle").value.trim(),note=$("memoryNote").value.trim(),place=$("memoryPlace").value.trim();if(!title&&!note){toast("Escribe una frase para guardar el recuerdo");return}state.memories.push({id:uid("mem"),title:title||"Un momento",note,place,by:currentPlayer,ts:nowIso(),updatedAt:nowIso()});$("memoryTitle").value="";$("memoryNote").value="";$("memoryPlace").value="";saveLocal();toast("📖 Recuerdo guardado para los dos")}
function deleteMemory(id){const m=state.memories.find(x=>x.id===id);if(!m)return;m.deletedAt=nowIso();m.updatedAt=m.deletedAt;saveLocal();toast("Recuerdo eliminado")}
function categoryTotals(){const totals={};activeExpenses().forEach(x=>totals[x.category]=(totals[x.category]||0)+(+x.amount||0));return totals}
function renderBudget(){const stats=targetStats(),expenses=activeExpenses().slice().sort((a,b)=>new Date(b.ts)-new Date(a.ts));$("budgetToday").textContent=eur(activeExpenses().filter(x=>dateKey(x.ts)===dateKey(new Date())).reduce((s,x)=>s+(+x.amount||0),0));$("budgetTotal").textContent=eur(stats.spent);$("budgetMargin").textContent=stats.wholeMargin>=0?eur(stats.wholeMargin):`−${eur(Math.abs(stats.wholeMargin))}`;$("budgetFixed").textContent=eur(+state.config.fixedPaid||0);$("budgetTargetText").textContent=`Objetivo conjunto: ${eur(stats.target)} al día · ${eur(stats.wholeTarget)} en los 3 días.`;$("budgetMessage").textContent=stats.wholeMargin>=0?`Quedan ${eur(stats.wholeMargin)} del objetivo variable total. Lo que no gastéis un día queda disponible para los siguientes.`:`Habéis superado el objetivo variable en ${eur(Math.abs(stats.wholeMargin))}. Es una referencia, no una obligación.`;const pct=stats.wholeTarget?clamp(stats.spent/stats.wholeTarget*100,0,100):0;$("budgetBar").style.width=`${pct}%`;$("budgetBar").style.background=stats.spent>stats.wholeTarget?"var(--danger)":"linear-gradient(90deg,var(--green),var(--gold))";const totals=categoryTotals(),max=Math.max(1,...Object.values(totals));$("categoryBars").innerHTML=Object.entries(D.expenseCategories).map(([key,label])=>{const val=totals[key]||0;return`<div class="cat-row"><span>${label}</span><div class="cat-track"><i style="width:${val/max*100}%"></i></div><strong>${val?eur(val):"—"}</strong></div>`}).join("");$("expenseList").innerHTML=expenses.length?expenses.slice(0,18).map(x=>`<div class="expense"><div><strong>${esc(D.expenseCategories[x.category]||D.expenseCategories.other)}</strong><div class="small">${esc(x.note||dateTimeLabel(x.ts))} · ${esc(x.by||"Ambos")}</div></div><div class="expense-amount">${eur(x.amount)}</div><button class="trash expense-delete" data-id="${esc(x.id)}" aria-label="Borrar gasto">✕</button></div>`).join(""):'<div class="empty">Aún no habéis registrado gastos variables.</div>';$$('.expense-delete').forEach(b=>b.onclick=()=>deleteExpense(b.dataset.id))}
function addExpense(e){e.preventDefault();const raw=$("expenseAmount").value.replace(",","."),amount=+raw;if(!Number.isFinite(amount)||amount<=0){toast("Introduce un importe válido");return}state.expenses.push({id:uid("exp"),amount:+amount.toFixed(2),category:$("expenseCategory").value,note:$("expenseNote").value.trim(),by:currentPlayer,ts:nowIso(),updatedAt:nowIso()});$("expenseAmount").value="";$("expenseNote").value="";saveLocal();toast(`💰 ${eur(amount)} añadido al gasto conjunto`)}
function deleteExpense(id){const x=state.expenses.find(e=>e.id===id);if(!x)return;x.deletedAt=nowIso();x.updatedAt=x.deletedAt;saveLocal();toast("Gasto eliminado")}
function initMap(){if(map||!window.L)return;map=L.map("map",{zoomControl:false}).setView([50.0617,19.9373],14);L.control.zoom({position:"topright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);addPoiMarkers();updateNear();geocodeMissing()}
function iconFor(p){const done=state.visited.includes(p.id);return L.divIcon({className:"",html:`<div class="marker ${done?"done":""}">${p.emoji}</div>`,iconSize:[36,36],iconAnchor:[18,18]})}
function markerVisible(p){if(mapFilter==="all")return true;if(mapFilter==="free")return p.costLevel===0;if(mapFilter==="pending")return!state.visited.includes(p.id);return p.category===mapFilter}
function addPoiMarkers(){if(!map)return;D.pois.forEach(p=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return;let m=markers.get(p.id);if(!m){m=L.marker([p.lat,p.lon],{icon:iconFor(p)});m.bindPopup(`<b>${p.emoji} ${esc(p.name)}</b><br><span style="font-size:12px">${esc(p.cost)} · ${p.duration} min</span><br><button type="button" data-open-poi="${p.id}" style="margin-top:7px;min-height:36px;border:0;border-radius:10px;background:#741c2b;color:#fff;padding:7px 10px">Ver historia</button>`);m.on("popupopen",e=>{const btn=e.popup.getElement()?.querySelector("[data-open-poi]");if(btn)btn.onclick=()=>openStory(p.id)});markers.set(p.id,m)}else m.setIcon(iconFor(p));if(markerVisible(p)){if(!map.hasLayer(m))m.addTo(map)}else if(map.hasLayer(m))map.removeLayer(m)})}
async function geocodeMissing(){const cache=JSON.parse(localStorage.getItem("kpGeoCache")||"{}");for(const p of D.pois.filter(x=>!Number.isFinite(x.lat)||!Number.isFinite(x.lon))){if(cache[p.id]){p.lat=cache[p.id].lat;p.lon=cache[p.id].lon;addPoiMarkers();continue}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(p.mapsQuery)}`,{headers:{"Accept-Language":"es"}}),j=await r.json();if(j[0]){p.lat=+j[0].lat;p.lon=+j[0].lon;cache[p.id]={lat:p.lat,lon:p.lon};localStorage.setItem("kpGeoCache",JSON.stringify(cache));addPoiMarkers()}}catch{}await new Promise(r=>setTimeout(r,1100))}updateNear()}
function focusPoi(id){initMap();const p=poiById(id);if(!p)return;if(Number.isFinite(p.lat)){map.setView([p.lat,p.lon],16);setTimeout(()=>markers.get(id)?.openPopup(),220)}else window.open(mapsSearch(p.mapsQuery),"_blank")}
function locate(){if(!navigator.geolocation){toast("Este navegador no ofrece ubicación");return}$("locateBtn").disabled=true;$("locateBtn").textContent="Buscando…";if(watchId!=null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(pos=>{userPos={lat:pos.coords.latitude,lon:pos.coords.longitude};initMap();if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([userPos.lat,userPos.lon],{icon:L.divIcon({className:"",html:'<div class="loc-dot"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map).bindPopup("📍 Estáis aquí");$("locateBtn").disabled=false;$("locateBtn").textContent="✓ Ubicación activa";$("privacyGps").textContent="GPS activo solo en este dispositivo; la posición no se sincroniza.";updateNear();renderRecommendation(false)},()=>{$("locateBtn").disabled=false;$("locateBtn").textContent="📍 Activar ubicación";toast("Safari necesita permiso de ubicación")},{enableHighAccuracy:true,maximumAge:15000,timeout:12000})}
function updateNear(){if(!$("nearList"))return;let list=D.pois.filter(p=>Number.isFinite(p.lat)&&!["base","bus"].includes(p.category));if(userPos)list=list.map(p=>({...p,_dist:hav(userPos,p)})).sort((a,b)=>a._dist-b._dist);else{const idx=phaseInfo().day,districts=idx>=0?D.days[idx].districts:["old"];list=list.sort((a,b)=>(districts.includes(b.district)?1:0)-(districts.includes(a.district)?1:0))}$("nearList").innerHTML=list.slice(0,7).map(p=>`<article class="poi"><div class="row start"><div><div class="poi-name">${p.emoji} ${esc(p.name)}</div><div class="small">${esc(p.cost)} · ${p.duration} min</div></div><div class="distance">${p._dist!=null?(p._dist<1?`${Math.round(p._dist*1000)} m`:`${p._dist.toFixed(1)} km`):esc(p.district)}</div></div><div class="grid2" style="margin-top:8px"><button class="btn secondary small-btn near-story" data-poi="${p.id}">Historia</button><button class="btn ghost small-btn near-go" data-poi="${p.id}">Ver ruta</button></div></article>`).join("");$$('.near-story').forEach(b=>b.onclick=()=>openStory(b.dataset.poi));$$('.near-go').forEach(b=>b.onclick=()=>openDirections(poiById(b.dataset.poi)))}
function openDirections(p){if(!p)return;if(userPos&&Number.isFinite(p.lat))window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(userPos.lat+","+userPos.lon)}&destination=${encodeURIComponent(p.lat+","+p.lon)}&travelmode=walking`,"_blank");else window.open(mapsSearch(p.mapsQuery),"_blank")}
const mapsSearch=query=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
function openStory(id){const p=poiById(id);if(!p)return;$("storyDialogTitle").textContent=`${p.emoji} ${p.name}`;$("storyDialogText").textContent=p.story;$("storyDialogMeta").textContent=`${p.cost} · ${p.duration} min · ${D.categories[p.category]?.label||p.category}`;$("storyGo").onclick=()=>openDirections(p);$("storyMark").textContent=state.visited.includes(id)?"✓ Descubierto":"Marcar descubierto";$("storyMark").onclick=()=>{if(!state.visited.includes(id)){state.visited.push(id);saveLocal();toast("✨ Lugar descubierto")}$("storyDialog").close()};$("storyDialog").showModal()}
function setMapFilter(filter){mapFilter=filter;$$('.chip[data-filter]').forEach(c=>c.classList.toggle("active",c.dataset.filter===filter));addPoiMarkers();updateNear()}
function renderMapFilters(){const filters=[["all","Todo"],["free","🆓 Gratis"],["history","🏛️ Historia"],["food","🍲 Comer"],["rest","🌿 Pausa"],["pending","✨ Pendientes"]];$("mapFilters").innerHTML=filters.map(([key,label])=>`<button class="chip ${key==="all"?"active":""}" data-filter="${key}">${label}</button>`).join("");$$('.chip[data-filter]').forEach(c=>c.onclick=()=>setMapFilter(c.dataset.filter))}
function openPanel(id){$$('.tab').forEach(x=>x.classList.toggle("active",x.dataset.panel===id));$$('.panel').forEach(x=>x.classList.toggle("active",x.id===id));history.replaceState(null,"",id==="home"?location.pathname:`?tab=${encodeURIComponent(id)}`);if(id==="mapPanel"){initMap();setTimeout(()=>map?.invalidateSize(),120);updateNear()}if(id==="budget")setTimeout(()=>$("expenseAmount")?.focus({preventScroll:true}),150)}
function renderDiarySegment(which){$$('.segment button').forEach(x=>x.classList.toggle("active",x.dataset.diary===which));$$('.subpanel').forEach(x=>x.classList.toggle("active",x.id===`diary-${which}`))}
function renderSettings(){$("playerSelect").value=currentPlayer;$("dailyTarget").value=+state.config.dailyTarget||21;$("fixedPaid").value=+state.config.fixedPaid||0;$("settingsVersion").textContent=`Kraków Pocket ${VERSION}`;$("syncCode").textContent=CLOUD.code;$("lastSync").textContent=lastSyncAt?`Última sincronización: ${dateTimeLabel(lastSyncAt)}`:"Todavía conectando…"}
function renderAll(){renderHero();renderHome();renderTimeline();renderQuests();renderStories();renderMemories();renderBudget();renderSettings();addPoiMarkers()}
function recordTime(item){const n=new Date(item?.updatedAt||item?.deletedAt||item?.completedAt||item?.verifiedAt||item?.ts||0).getTime();return Number.isFinite(n)?n:0}
function mergeRecords(local=[],remote=[]){const m=new Map();[...remote,...local].forEach(item=>{if(!item||!item.id)return;const prev=m.get(item.id);if(!prev||recordTime(item)>=recordTime(prev))m.set(item.id,item)});return[...m.values()]}
function mergeObjectRecords(local={},remote={}){const out={};for(const src of [remote,local])for(const [id,item] of Object.entries(src||{})){if(!item||typeof item!=="object")continue;const prev=out[id];if(!prev||recordTime(item)>=recordTime(prev))out[id]=item}return out}
function mergeState(remote){if(!remote||typeof remote!=="object")return state;const local=state,localNewer=new Date(local.updatedAt||0)>=new Date(remote.updatedAt||0);return{...remote,...local,visited:[...new Set([...(remote.visited||[]),...(local.visited||[])])],expenses:mergeRecords(local.expenses||[],remote.expenses||[]),memories:mergeRecords(local.memories||[],remote.memories||[]),albumPhotos:mergeRecords(local.albumPhotos||[],remote.albumPhotos||[]),missionEvidence:mergeObjectRecords(local.missionEvidence||{},remote.missionEvidence||{}),missionStatus:mergeObjectRecords(local.missionStatus||{},remote.missionStatus||{}),discoveryStatus:mergeObjectRecords(local.discoveryStatus||{},remote.discoveryStatus||{}),profilePhotos:mergeObjectRecords(local.profilePhotos||{},remote.profilePhotos||{}),config:localNewer?(local.config||{}):(remote.config||local.config||{}),updatedAt:localNewer?(local.updatedAt||nowIso()):(remote.updatedAt||local.updatedAt||nowIso())}}
function syncUi(mode,msg){const ok=mode==="ok",busy=mode==="busy";$("syncDot").className=`sync-dot ${ok?"ok":busy?"busy":""}`;$("syncText").textContent=ok?"sincronizados":busy?"sincronizando…":"sin conexión";$("settingsSync").textContent=ok?"☁️ partida compartida":busy?"☁️ conectando":"☁️ sin conexión";$("settingsSync").className=`pill ${ok?"green":busy?"gold":"red"}`;if(msg)$("syncHelp").textContent=msg;renderHero()}
async function rpc(name,body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${CLOUD.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":CLOUD.key},body:JSON.stringify(body),signal:controller.signal}),text=await r.text();if(!r.ok){let detail=text;try{const j=JSON.parse(text);detail=j.message||j.error||text}catch{}throw new Error(`HTTP ${r.status}: ${detail||"Error de Supabase"}`)}return text?JSON.parse(text):null}catch(e){if(e?.name==="AbortError")throw new Error("Tiempo de espera agotado");throw e}finally{clearTimeout(timeout)}}
async function pullCloud(){if(syncing)return;syncing=true;syncUi("busy");try{const remote=await rpc("adventure_get",{p_code:CLOUD.code,p_secret:CLOUD.secret});state=mergeState(remote);persistState();lastSyncAt=nowIso();syncUi("ok","Los cambios de ambos iPhone se actualizan automáticamente.");renderAll()}catch(e){console.error("Kraków Pocket sync pull",e);syncUi("error",`No se pudo sincronizar: ${e.message||e}`)}finally{syncing=false}}
async function pushCloud(){if(syncing)return;syncing=true;syncUi("busy");try{let remote=null;try{remote=await rpc("adventure_get",{p_code:CLOUD.code,p_secret:CLOUD.secret})}catch{}state=mergeState(remote);persistState();await rpc("adventure_put",{p_code:CLOUD.code,p_secret:CLOUD.secret,p_state:state});persistState();lastSyncAt=nowIso();syncUi("ok","Aventura compartida sincronizada.");renderAll()}catch(e){console.error("Kraków Pocket sync push",e);syncUi("error",`No se pudo sincronizar: ${e.message||e}`)}finally{syncing=false}}
async function startSync(manual=false){clearInterval(syncTimer);if(manual)syncUi("busy","Reconectando…");await pullCloud();syncTimer=setInterval(()=>pullCloud(),5000);if(manual&&lastSyncAt)toast("☁️ Sincronización activa")}
function registerPwa(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.register("./sw.js").then(reg=>{reg.update().catch(()=>{});const showUpdate=()=>{$("updateBanner").style.display="flex";$("applyUpdate").onclick=()=>reg.waiting?.postMessage({type:"SKIP_WAITING"})};if(reg.waiting)showUpdate();reg.addEventListener("updatefound",()=>{const worker=reg.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)showUpdate()})});navigator.serviceWorker.addEventListener("controllerchange",()=>location.reload())}).catch(()=>{})}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$("openSettings").onclick=()=>{$("settingsSheet").showModal();renderSettings()};$("closeSettings").onclick=()=>$("settingsSheet").close();$("storyClose").onclick=()=>$("storyDialog").close();$("locateBtn").onclick=locate;$("recommendBtn").onclick=()=>renderRecommendation(true);$("recAction").onclick=openRecommendation;$("recSecondary").onclick=()=>activeRecommendation?.poi&&openStory(activeRecommendation.poi.id);$("quickMap").onclick=()=>openPanel("mapPanel");$("quickExpense").onclick=()=>openPanel("budget");$("quickMemory").onclick=()=>{openPanel("diary");renderDiarySegment("memories");setTimeout(()=>$("memoryTitle")?.focus(),150)};$("quickRest").onclick=()=>{$("mood").value="rest";renderRecommendation(true)};$("freeTime").onchange=()=>renderRecommendation(false);$("mood").onchange=()=>renderRecommendation(false);$("workMode").onchange=()=>renderRecommendation(true);$("expenseForm").onsubmit=addExpense;$("memoryForm").onsubmit=addMemory;$$('.segment button').forEach(b=>b.onclick=()=>renderDiarySegment(b.dataset.diary));$("refreshNear").onclick=updateNear;$("playerSelect").onchange=e=>{currentPlayer=e.target.value;localStorage.setItem(PLAYER_KEY,currentPlayer);renderAll();toast(`Este iPhone: ${currentPlayer}`)};$("dailyTarget").onchange=e=>{state.config.dailyTarget=Math.max(0,+e.target.value||21);saveLocal()};$("fixedPaid").onchange=e=>{state.config.fixedPaid=Math.max(0,+e.target.value||0);saveLocal()};$("reconnectCloud").onclick=()=>startSync(true);$("homeMapBtn").onclick=()=>window.open(mapsSearch(TRIP.baseWarsaw),"_blank");$("zachodniaBtn").onclick=()=>window.open(mapsSearch(TRIP.stationWarsaw),"_blank")}
function init(){bind();renderMapFilters();renderAll();initMap();const requested=new URLSearchParams(location.search).get("tab");if(requested&&$(requested))openPanel(requested);startSync(false);registerPwa();setInterval(()=>{renderHero();renderHome()},30000)}
document.addEventListener("DOMContentLoaded",init);
})();
