(() => {
"use strict";
const GAME="./assets/game-art.svg",CHARS="./assets/characters.svg";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let game=null,chars=null,frame=0,ready=false;
function parseSprite(text){const doc=new DOMParser().parseFromString(text,"image/svg+xml"),defs=doc.querySelector("defs")?.innerHTML||"",symbols=new Map();doc.querySelectorAll("symbol[id]").forEach(s=>symbols.set(s.id,{viewBox:s.getAttribute("viewBox")||"0 0 180 180",html:s.innerHTML}));return{defs,symbols}}
async function load(url){const r=await fetch(url,{cache:"force-cache"});if(!r.ok)throw new Error(`${url}: ${r.status}`);return parseSprite(await r.text())}
function inline(pack,id,cls){const s=pack?.symbols.get(id);if(!s)return"";return `<svg data-kp-inline="${id}" class="${cls}" viewBox="${s.viewBox}" aria-hidden="true" focusable="false"><defs>${pack.defs}</defs>${s.html}</svg>`}
function player(){return localStorage.getItem("krakowPlayer")==="Laura"?"Laura":"Ismael"}
function patchCharacters(){const who=player(),portraitId=who==="Laura"?"char-laura-v3-portrait":"char-ismael-v3-portrait",portrait=$("#kpGameHud .kp-game-portrait");if(portrait&&!portrait.querySelector(`svg[data-kp-inline="${portraitId}"]`)){const html=inline(chars,portraitId,"kp-character-asset");if(html)portrait.innerHTML=html}const couple=$$("#kpGameHub .kp-couple-art"),ids=["char-ismael-v3-chibi","char-laura-v3-chibi"];couple.forEach((el,i)=>{const id=ids[i];if(!id||el.querySelector(`svg[data-kp-inline="${id}"]`))return;const html=inline(chars,id,"kp-character-asset");if(html)el.innerHTML=html});const npc=$("#kpGameHub .kp-hub-avatar");if(npc&&!npc.querySelector('svg[data-kp-inline="npc-dragon-v2"]')){const html=inline(chars,"npc-dragon-v2","kp-npc-asset");if(html)npc.innerHTML=html}}
function patchLandmarks(){$$('#kpQuestWorld .kp-world-node[data-pixel-poi]').forEach(n=>{const id=n.dataset.pixelPoi,target=n.querySelector('.kp-landmark-art');if(!target||target.querySelector(`svg[data-kp-inline="landmark-${CSS.escape(id)}"]`))return;const html=inline(game,`landmark-${id}`,"kp-landmark-svg");if(html)target.innerHTML=html})}
const NAV={home:"nav-home",mapPanel:"nav-map",quests:"nav-quests",diary:"nav-diary",budget:"nav-budget"};
function patchNavigation(){$$('.tab[data-panel]').forEach(t=>{const id=NAV[t.dataset.panel],b=t.querySelector('b');if(!b||!id||b.querySelector(`svg[data-kp-inline="${id}"]`))return;const html=inline(game,id,"kp-asset-svg");if(html)b.innerHTML=`<span class="kp-nav-art">${html}</span>`});$$('#kpGameHub .kp-hub-place[data-go]').forEach(b=>{const id=NAV[b.dataset.go],target=b.querySelector('.building');if(!target||!id||target.querySelector(`svg[data-kp-inline="${id}"]`))return;const html=inline(game,id,"kp-asset-svg");if(html)target.innerHTML=html})}
function patch(){frame=0;if(!ready)return;patchCharacters();patchLandmarks();patchNavigation();document.documentElement.classList.add("kp-inline-art-ready")}
function schedule(){if(!frame)frame=requestAnimationFrame(patch)}
function scrollPanelTop(){requestAnimationFrame(()=>{window.scrollTo({top:0,left:0,behavior:"auto"});document.scrollingElement?.scrollTo?.({top:0,left:0,behavior:"auto"})})}
function bind(){const observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",e=>{if(e.target.closest?.('.tab[data-panel],#kpGameHub [data-go],#quickMap,#quickExpense,#quickMemory'))setTimeout(scrollPanelTop,20)},true);window.addEventListener("storage",schedule);window.addEventListener("pageshow",schedule);window.addEventListener("orientationchange",()=>setTimeout(schedule,120),{passive:true});Promise.all([load(GAME),load(CHARS)]).then(([g,c])=>{game=g;chars=c;ready=true;schedule()}).catch(err=>{console.warn("Kraków Pocket inline art fallback",err);document.documentElement.classList.add("kp-inline-art-failed")})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();