(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",$=s=>document.querySelector(s),esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,num=n=>Number(n||0).toFixed(2).replace(".",",");
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const poi=id=>D.pois.find(x=>x.id===id),quest=id=>D.quests.find(x=>x.poi===id),active=a=>(a||[]).filter(x=>x&&!x.deletedAt);
const todayIndex=()=>D.days.findIndex(x=>x.date===dateKey(new Date())),score=s=>D.quests.filter(q=>(s.visited||[]).includes(q.poi)).reduce((a,q)=>a+(+q.points||0),0);
const todaySpend=s=>{const key=dateKey(new Date());return active(s.expenses).filter(x=>dateKey(new Date(x.ts))===key).reduce((a,x)=>a+(+x.amount||0),0)},totalSpend=s=>active(s.expenses).reduce((a,x)=>a+(+x.amount||0),0);
function routeForNow(s){const idx=todayIndex();if(idx===0)return{label:"Ruta de hoy",title:"Primer contacto · Old Town + Wawel",ids:["mda","w94","florian","rynek","maria","maius","wawel","dragon"]};if(idx===1)return{label:"Ruta de hoy",title:"Kazimierz → Vístula → Podgórze",ids:["szeroka","placnowy","bernatek","ghetto","planty"]};if(idx===2){const pending=D.pois.filter(p=>p.days?.includes(3)&&!["base","bus","shop","food"].includes(p.category)&&!(s.visited||[]).includes(p.id)).slice(0,4).map(p=>p.id);return{label:"Día flexible",title:"Pendientes sin correr + regreso",ids:[...pending,"mda"]}}return new Date()<new Date(D.trip.start)?{label:"Mañana en Cracovia",title:"Llegada → centro histórico → Wawel",ids:["mda","w94","florian","rynek","wawel","dragon"]}:{label:"Aventura guardada",title:"Vuestros lugares de Cracovia",ids:["rynek","wawel","dragon","szeroka","ghetto"]}}
const stopUrl=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.mapsQuery||`${p.lat},${p.lon}`)}`;
function routeUrl(ids){const ps=ids.map(poi).filter(Boolean);if(ps.length<2)return ps[0]?stopUrl(ps[0]):"#";const q=p=>p.mapsQuery||`${p.lat},${p.lon}`,origin=q(ps[0]),destination=q(ps.at(-1)),waypoints=ps.slice(1,-1).map(q).join("|");return`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=walking${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:""}`}
function ensureShell(){if(!$("#kpRouteCard")){const el=document.createElement("article");el.id="kpRouteCard";el.className="card kp-route-card";$("#home .quick-grid")?.insertAdjacentElement("afterend",el)}if(!$("#kpDistrictCard")){const el=document.createElement("article");el.id="kpDistrictCard";el.className="card kp-district-card";$("#adventureRing")?.closest("article")?.insertAdjacentElement("afterend",el)}if(!$("#kpShareCard")){const el=document.createElement("article");el.id="kpShareCard";el.className="card kp-share-card";$("#diary-memories form#memoryForm")?.closest("article")?.insertAdjacentElement("afterend",el)}if(!$("#kpOffline")){const el=document.createElement("div");el.id="kpOffline";el.className="kp-offline";el.textContent="📴 Sin conexión · la app sigue disponible";document.body.appendChild(el)}}
function renderRoute(s){const host=$("#kpRouteCard");if(!host)return;const r=routeForNow(s),visited=s.visited||[],ps=r.ids.map(poi).filter(Boolean),track=ps.filter(p=>!["base","bus"].includes(p.category)),done=track.filter(p=>visited.includes(p.id)).length,target=+(s.config?.dailyTarget||D.trip.dailyTarget||21),spent=todaySpend(s),next=track.find(p=>!visited.includes(p.id));host.innerHTML=`<div class="row start"><div><div class="smart-kicker">${esc(r.label)}</div><h2>${esc(r.title)}</h2></div><span class="pill ${spent<=target?"green":"red"}">Hoy ${num(spent)}<span class="kp-unit">€</span> / ${num(target)}<span class="kp-unit">€</span></span></div><div class="kp-route-progress"><i style="width:${track.length?Math.round(done/track.length*100):0}%"></i></div><div class="kp-route-steps">${ps.map(p=>{const logistical=["base","bus"].includes(p.category),isDone=visited.includes(p.id);return`<button class="kp-route-step ${isDone?"done":""}" data-stop="${p.id}"><span class="kp-step-dot">${isDone?"✓":p.emoji}</span><span><b>${esc(p.name)}</b><small>${isDone?"hecho":logistical?"logística de la ruta":`${p.duration||20} min · ${esc(p.cost)}`}</small></span></button>`}).join("")}</div><div class="kp-route-actions"><button class="btn secondary" id="kpRouteOpen">🗺️ Abrir ruta</button>${next?`<button class="btn" id="kpNextMission">${quest(next.id)?"🧩 Siguiente misión":"📍 Siguiente parada"}</button>`:""}</div>`;$("#kpRouteOpen").onclick=()=>window.open(routeUrl(r.ids),"_blank");if(next&&$("#kpNextMission"))$("#kpNextMission").onclick=()=>window.open(stopUrl(next),"_blank");host.querySelectorAll("[data-stop]").forEach(b=>b.onclick=()=>{const p=poi(b.dataset.stop);if(p)window.open(stopUrl(p),"_blank")})}
function renderDistricts(s){const host=$("#kpDistrictCard");if(!host)return;const defs=[{id:"old",name:"Old Town",emoji:"🏰"},{id:"wawel",name:"Wawel",emoji:"🐉"},{id:"kazimierz",name:"Kazimierz",emoji:"✡️"},{id:"podgorze",name:"Podgórze",emoji:"🌉"}],visited=s.visited||[];host.innerHTML=`<div class="row"><div><div class="smart-kicker">Mapa de aventura</div><h2>Barrios que ya son vuestros</h2></div><span class="pill gold">${score(s)} 🐉</span></div><div class="kp-district-grid">${defs.map(d=>{const pts=D.pois.filter(p=>p.district===d.id&&["history","game","walk","rest","museum"].includes(p.category)),done=pts.filter(p=>visited.includes(p.id)).length,pct=pts.length?Math.round(done/pts.length*100):0;return`<div class="kp-district"><div class="row"><span>${d.emoji} <b>${esc(d.name)}</b></span><span class="kp-percent">${pct}<span>%</span></span></div><div class="kp-mini-track"><i style="width:${pct}%"></i></div><small>${done} de ${pts.length} descubiertos</small></div>`}).join("")}</div>`}
function summary(s){const memories=active(s.memories).sort((a,b)=>new Date(b.ts)-new Date(a.ts)),done=D.quests.filter(q=>(s.visited||[]).includes(q.poi)).length,lines=["Kraków Pocket · Ismael + Laura",`Misiones: ${done}/${D.quests.length} · ${score(s)} escamas`,`Gasto variable: ${num(totalSpend(s))}€`,`Recuerdos guardados: ${memories.length}`];if(memories.length){lines.push("","Últimos recuerdos:");memories.slice(0,5).forEach(m=>lines.push(`• ${m.title||"Recuerdo"}${m.place?` · ${m.place}`:""}${m.note?`: ${m.note}`:""}`))}lines.push("",`${location.origin}${location.pathname}`);return lines.join("\n")}
async function share(){const text=summary(read());try{if(navigator.share){await navigator.share({title:"Kraków Pocket · nuestro viaje",text});return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);alert("Resumen copiado al portapapeles.");return}prompt("Copia vuestro resumen:",text)}catch(e){if(e?.name!=="AbortError")prompt("Copia vuestro resumen:",text)}}
function renderShare(s){const host=$("#kpShareCard");if(!host)return;const memories=active(s.memories).length,done=D.quests.filter(q=>(s.visited||[]).includes(q.poi)).length;host.innerHTML=`<div class="row start"><div><div class="smart-kicker">Vuestro viaje, guardado</div><h2>Resumen de la aventura</h2><p class="small">${memories} recuerdos · ${done}/${D.quests.length} misiones · ${num(totalSpend(s))}<span class="kp-unit">€</span> variables</p></div><span class="kp-recap-mark">✦</span></div><button class="btn full" id="kpShareSummary">↗️ Compartir / guardar resumen</button>`;$("#kpShareSummary").onclick=share}
function renderNetwork(){$("#kpOffline")?.classList.toggle("show",!navigator.onLine)}
let lastSig="";function renderExtras(){ensureShell();const s=read(),sig=JSON.stringify({v:s.visited,e:s.expenses,m:s.memories,c:s.config,d:dateKey(new Date())});if(sig!==lastSig){lastSig=sig;renderRoute(s);renderDistricts(s);renderShare(s)}renderNetwork()}
window.addEventListener("online",renderExtras);window.addEventListener("offline",renderNetwork);window.addEventListener("storage",renderExtras);window.addEventListener("kp:statechange",renderExtras);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",renderExtras,{once:true});else renderExtras();setInterval(renderExtras,30000);

/* Mission status adapter: supports undo/reset without reloads. */
const CLOUD={url:"https://ahzmwkztlakejmrvgcdm.supabase.co",key:"sb_publishable_sf-RddHTp5jdFCQOfRBBsQ_PZGKOlxJ",code:"WAWEL-ISMAEL-LAURA",secret:"krakow2026"},qIds=new Set(D.quests.map(q=>q.poi)),time=v=>{const n=new Date(v||0).getTime();return Number.isFinite(n)?n:0},now=()=>new Date().toISOString();
function applyStatus(s,status){const v=new Set(s.visited||[]);for(const [id,op] of Object.entries(status||{})){if(!qIds.has(id))continue;if(op?.done)v.add(id);else v.delete(id)}s.visited=[...v];s.missionStatus=status;return s}
function normalize(s){s=s&&typeof s==="object"?s:{};if(!Array.isArray(s.visited))s.visited=[];if(!Array.isArray(s.expenses))s.expenses=[];if(!Array.isArray(s.memories))s.memories=[];if(!s.config||typeof s.config!=="object")s.config={};if(!s.missionStatus||typeof s.missionStatus!=="object"||Array.isArray(s.missionStatus))s.missionStatus={};for(const id of s.visited)if(qIds.has(id)&&!s.missionStatus[id])s.missionStatus[id]={done:true,updatedAt:s.updatedAt||"1970-01-01T00:00:00.000Z"};return applyStatus(s,s.missionStatus)}
function mergeStatus(a={},b={}){const out={};for(const src of [a,b])for(const [id,op] of Object.entries(src||{})){if(!qIds.has(id)||!op)continue;const prev=out[id];if(!prev||time(op.updatedAt)>=time(prev.updatedAt))out[id]={done:!!op.done,updatedAt:op.updatedAt||"1970-01-01T00:00:00.000Z"}}return out}
function mergeRecords(a=[],b=[]){const m=new Map();for(const item of [...b,...a]){if(!item?.id)continue;const prev=m.get(item.id);if(!prev||time(item.updatedAt||item.ts)>=time(prev.updatedAt||prev.ts))m.set(item.id,item)}return[...m.values()]}
function write(s,{event=true}={}){s=normalize(s);localStorage.setItem(STORAGE,JSON.stringify(s));if(event){window.dispatchEvent(new CustomEvent("kp:statechange",{detail:{source:"missions"}}));window.dispatchEvent(new Event("storage"))}return s}
async function rpc(name,body){const c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{const r=await fetch(`${CLOUD.url}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":CLOUD.key},body:JSON.stringify(body),signal:c.signal}),text=await r.text();if(!r.ok)throw new Error(text||`HTTP ${r.status}`);return text?JSON.parse(text):null}finally{clearTimeout(tm)}}
function mergeState(local,remote,status){local=normalize(local);remote=normalize(remote);const out={...remote,...local,expenses:mergeRecords(local.expenses,remote.expenses),memories:mergeRecords(local.memories,remote.memories),config:local.config||remote.config||{},budget:Array.isArray(local.budget)?local.budget:(remote.budget||[]),missionStatus:status,updatedAt:now()};return applyStatus(out,status)}
const effective=(s,id)=>normalize(s).missionStatus[id]?!!normalize(s).missionStatus[id].done:(s.visited||[]).includes(id),flash=text=>{const t=$("#toast");if(t){t.textContent=text;t.style.display="block";clearTimeout(t._kpMissionTimer);t._kpMissionTimer=setTimeout(()=>t.style.display="none",2400)}};
async function pushState(local){if(!navigator.onLine)return local;try{const remote=normalize(await rpc("adventure_get",{p_code:CLOUD.code,p_secret:CLOUD.secret})||{}),status=mergeStatus(remote.missionStatus,local.missionStatus),out=mergeState(local,remote,status);await rpc("adventure_put",{p_code:CLOUD.code,p_secret:CLOUD.secret,p_state:out});write(out);return out}catch(e){console.warn("Kraków Pocket mission sync",e);return local}}
function completedSorted(s){s=normalize(s);return D.quests.filter(q=>effective(s,q.poi)).sort((a,b)=>time(s.missionStatus[b.poi]?.updatedAt)-time(s.missionStatus[a.poi]?.updatedAt))}
function renderMissionControls(){const s=normalize(read()),done=D.quests.filter(q=>effective(s,q.poi));document.querySelectorAll(".q-done[data-poi]").forEach(b=>{const isDone=effective(s,b.dataset.poi);b.textContent=isDone?"📷 Cambiar foto":"✓ Completar";b.classList.toggle("green",!isDone);b.classList.toggle("secondary",isDone);b.closest(".quest")?.classList.toggle("done",isDone)});const count=$("#questCount");if(count)count.textContent=`${done.length} / ${D.quests.length}`;const bar=$("#questBar");if(bar)bar.style.width=`${D.quests.length?done.length/D.quests.length*100:0}%`;const home=$("#homeMission");if(home)home.textContent=`${done.length}/${D.quests.length}`;const ring=$("#adventureRing");if(ring){const pct=Math.round(done.length/Math.max(1,D.quests.length)*100);ring.style.setProperty("--p",pct);ring.dataset.label=`${pct}%`}const header=count?.closest("article");if(!header)return;let box=$("#kpMissionManage");if(!box){box=document.createElement("div");box.id="kpMissionManage";box.className="grid2";box.style.marginTop="10px";header.appendChild(box)}const sorted=completedSorted(s);if(!sorted.length){box.style.display="none";return}box.style.display="grid";box.innerHTML='<button class="btn ghost small-btn" id="kpUndoMission">↩ Deshacer última</button><button class="btn secondary small-btn" id="kpResetMissions">Reiniciar misiones</button>';$("#kpUndoMission").onclick=()=>change([sorted[0].poi],false,`↩ ${sorted[0].title} vuelve a estar pendiente`);$("#kpResetMissions").onclick=()=>{if(confirm("¿Marcar todas las misiones como pendientes?"))change(sorted.map(q=>q.poi),false,"↩ Misiones reiniciadas")}}
async function change(ids,isDone,message){const s=normalize(read()),stamp=now();for(const id of ids)s.missionStatus[id]={done:!!isDone,updatedAt:stamp};s.updatedAt=stamp;const local=write(s);renderMissionControls();flash(message);await pushState(local);renderMissionControls()}
let reconciling=false;async function reconcile(){if(reconciling||!navigator.onLine)return;reconciling=true;try{const local=normalize(read()),remote=normalize(await rpc("adventure_get",{p_code:CLOUD.code,p_secret:CLOUD.secret})||{}),status=mergeStatus(remote.missionStatus,local.missionStatus),merged=mergeState(local,remote,status);write(merged);const remoteComparable=JSON.stringify({v:remote.visited,m:remote.missionStatus}),mergedComparable=JSON.stringify({v:merged.visited,m:merged.missionStatus});if(remoteComparable!==mergedComparable)await rpc("adventure_put",{p_code:CLOUD.code,p_secret:CLOUD.secret,p_state:merged});renderMissionControls()}catch(e){console.warn("Kraków Pocket mission reconcile",e)}finally{reconciling=false}}
document.addEventListener("click",e=>{const b=e.target.closest?.(".q-done[data-poi]");if(!b)return;const s=normalize(read()),id=b.dataset.poi,isDone=effective(s,id);if(isDone){const proof=s.missionEvidence?.[id],api=window.KP_MISSION_PROOF;if(proof?.verified===true&&typeof proof.photo==="string"&&proof.photo.startsWith("data:image/")&&api?.replaceCompletedPhoto&&typeof api.open==="function"){e.preventDefault();e.stopImmediatePropagation();api.open(id,{replace:true});return}return}e.preventDefault();e.stopImmediatePropagation();const q=D.quests.find(x=>x.poi===id);change([id],true,`✓ ${q?.title||"Misión"} completada`)},true);
function initMissions(){renderMissionControls();setTimeout(reconcile,1600);setInterval(reconcile,30000);window.addEventListener("kp:statechange",renderMissionControls);window.addEventListener("storage",renderMissionControls)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initMissions,{once:true});else initMissions();
window.KP_ENHANCEMENTS={version:"7.1",reloadFree:true,completedMissionPhotoReplacement:true};
})();