(() => {
"use strict";
const D=window.KP_DATA,APP=window.KP_APP;if(!D||!APP)return;
const $=s=>document.querySelector(s);
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const POS={florian:[17,14],maria:[50,14],planty:[82,14],maius:[18,37],tomasza:[50,37],szeroka:[82,37],dragon:[18,60],bernatek:[50,60],placnowy:[82,60],wawel:[18,82],rynek:[50,82],ghetto:[82,82]};
const CHEERS={florian:["¡La ciudad os deja pasar!","La puerta medieval ha decidido que sois gente de fiar. De momento."],rynek:["¡Ojos de explorador desbloqueados!","Rynek: 0 · Ismael y Laura: 1. Habéis visto algo que el otro casi se pierde."],maria:["¡Hejnał localizado!","El trompetista invisible aprueba vuestra capacidad para mirar hacia arriba."],maius:["¡Secreto universitario descubierto!","Copérnico probablemente estaría orgulloso. O al menos ligeramente impresionado."],wawel:["¡Territorio real conquistado!","Sin corona, sin caballo y aun así habéis llegado a Wawel. Nada mal."],dragon:["¡ESCAMA LEGENDARIA!","El Dragón de Wawel os reconoce oficialmente como pareja aventurera. No incluye inmunidad al fuego."],szeroka:["¡Kazimierz os cuenta sus capas!","Habéis hecho lo difícil: mirar el barrio en vez de simplemente atravesarlo."],placnowy:["¡Economía de mercado dominada!","Comparar precios antes de comprar: más escamas y menos posibilidades de turistada."],bernatek:["¡Puente entre mundos cruzado!","Un barrio detrás, otro delante y vosotros dos en medio. Cinematográfico."],ghetto:["Misión de memoria completada","Aquí no toca bromear demasiado. Gracias por parar, mirar y dedicarle tiempo al lugar."],tomasza:["¡Maestros del złoty!","Comer caliente sin destruir el presupuesto: habilidad épica desbloqueada."],planty:["¡Descanso profesional!","Habéis completado una misión haciendo… nada. Planty estaría orgulloso."]};
const poi=id=>D.pois.find(p=>p.id===id),quest=id=>D.quests.find(q=>q.poi===id),state=()=>APP.getState(),done=id=>APP.isMissionDone(id),completed=()=>D.quests.filter(q=>done(q.poi)).length,score=()=>D.quests.filter(q=>done(q.poi)).reduce((a,q)=>a+(+q.points||0),0),spent=()=>state().expenses.filter(x=>x&&!x.deletedAt).reduce((a,x)=>a+(+x.amount||0),0);
let chromeSig="",hubSig="",questSig="",navReady=false,lastMissionTrigger=null;

function currentObjective(){const title=$("#recTitle")?.textContent?.trim(),text=$("#recText")?.textContent?.trim(),emoji=$("#recEmoji")?.textContent?.trim()||"✨";if(title&&title!=="Calculando…"&&title!=="Calculando...")return[emoji,title,text||"La siguiente parte de la aventura os espera."];const q=D.quests.find(x=>!done(x.poi));return q?["📜",q.title,q.text]:["🐉","Aventura principal completada","Habéis conseguido todas las escamas de Wawel."]}
function ensureChrome(){const app=$(".app"),content=$(".content");if(!app||!content)return;let hud=$("#kpGameHud");if(!hud){hud=document.createElement("header");hud.id="kpGameHud";app.insertBefore(hud,content)}let objective=$("#kpGameObjective");if(!objective){objective=document.createElement("section");objective.id="kpGameObjective";objective.setAttribute("role","status");objective.setAttribute("aria-live","polite");app.insertBefore(objective,content)}const banner=$("#updateBanner");if(banner&&banner.parentElement!==app)app.insertBefore(banner,content)}
function chromeSignature(){const o=currentObjective();return JSON.stringify([APP.getPlayer(),score(),spent().toFixed(2),completed(),o[0],o[1],o[2]])}
function renderChrome(force=false){ensureChrome();const sig=chromeSignature();if(!force&&sig===chromeSig)return false;chromeSig=sig;const hud=$("#kpGameHud"),player=APP.getPlayer();if(hud){hud.innerHTML=`<div class="kp-game-brand"><div class="kp-game-portrait" data-character-role="portrait" aria-label="${player}"></div><div class="kp-game-logo"><strong>Kraków Pocket</strong><span>Aventura para dos</span></div><button type="button" class="kp-game-settings" id="kpGameSettings" aria-label="Menú de partida">⚙️</button></div><div class="kp-game-resources"><div class="kp-game-resource"><b>🐉 ${score()}</b><span>Escamas</span></div><div class="kp-game-resource"><b>${spent().toFixed(2).replace('.',',')} €</b><span>Monedas</span></div><div class="kp-game-resource"><b>${completed()}/${D.quests.length}</b><span>Misiones</span></div></div>`;$("#kpGameSettings").onclick=()=>APP.openSettings()}const o=currentObjective(),obj=$("#kpGameObjective");if(obj)obj.innerHTML=`<div class="kp-objective-icon" aria-hidden="true">${o[0]}</div><div class="kp-objective-copy"><b>${esc(o[1])}</b><span>${esc(o[2]||"")}</span></div><div class="kp-objective-count">📋 ${completed()}/${D.quests.length}</div>`;return true}

function gameMessage(){const n=completed();if(n>=D.quests.length)return["Dragón de Wawel","¡Habéis reunido todas las escamas! Cracovia ya es territorio de aventureros."];if(n>=9)return["Dragón de Wawel","Os quedan muy pocas escamas. Wawel empieza a considerar seriamente vuestra candidatura a leyenda."];if(n>=6)return["Guardián del viaje","Ya habéis superado la mitad. Las mejores misiones aparecen cuando miráis alrededor."];return["Dragón de Wawel",n?`Lleváis ${n} de ${D.quests.length} misiones. Hay otra escama escondida ahí fuera.`:"Toda aventura empieza con una puerta. Buscad el primer ! y empezad a mirar Cracovia como jugadores."]}
function ensureHub(){const home=$("#home");if(!home||$("#kpGameHub"))return;const h=document.createElement("section");h.id="kpGameHub";h.setAttribute("aria-label","Aldea de Kraków Pocket");home.insertBefore(h,home.firstChild)}
function renderHub(force=false){ensureHub();const host=$("#kpGameHub");if(!host)return false;const n=completed(),msg=gameMessage(),sig=JSON.stringify([n,msg[0],msg[1]]);if(!force&&sig===hubSig)return false;hubSig=sig;const pending=D.quests.length-n;host.innerHTML=`<div class="kp-hub-frame"><div class="kp-hub-world"><button type="button" class="kp-hub-place base" data-go="home"><span class="building"></span><small>Base</small></button><button type="button" class="kp-hub-place quests" data-go="quests"><span class="building"></span>${pending?'<span class="alert" aria-hidden="true">!</span>':''}<small>Encargos</small></button><button type="button" class="kp-hub-place map" data-go="mapPanel"><span class="building"></span><small>Mapa</small></button><button type="button" class="kp-hub-place diary" data-go="diary"><span class="building"></span><small>Crónica</small></button><button type="button" class="kp-hub-place budget" data-go="budget"><span class="building"></span><small>Bolsa</small></button><div class="kp-hub-couple" aria-label="Ismael y Laura"><span class="kp-couple-art" data-character-role="ismael" aria-label="Ismael"></span><span class="kp-couple-art" data-character-role="laura" aria-label="Laura"></span></div></div><div class="kp-hub-dialog"><div class="kp-hub-avatar" data-character-role="npc"></div><div><div class="kp-hub-speaker">${msg[0]}</div><div class="kp-hub-message">${msg[1]}</div><div class="kp-hub-hint">Toca un edificio para entrar · ${n}/${D.quests.length} misiones</div></div></div></div>`;host.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>APP.openPanel(b.dataset.go));return true}

function closeMissionDialog(){const sheet=$("#kpQuestDialog");sheet?.classList.remove("show");sheet?.setAttribute("aria-hidden","true");if(lastMissionTrigger?.isConnected)lastMissionTrigger.focus?.({preventScroll:true});lastMissionTrigger=null}
function ensureQuestUI(){const panel=$("#quests");if(!panel)return;if(!$("#kpQuestWorld")){const world=document.createElement("div");world.id="kpQuestWorld";panel.appendChild(world)}if(!$("#kpQuestDialog")){const sheet=document.createElement("div");sheet.id="kpQuestDialog";sheet.className="kp-pixel-dialog";sheet.setAttribute("role","dialog");sheet.setAttribute("aria-modal","false");sheet.setAttribute("aria-hidden","true");sheet.innerHTML='<div class="kp-pixel-portrait" aria-hidden="true">🐉</div><div><div class="kp-pixel-name" id="kpPixelName"></div><div class="kp-pixel-text" id="kpPixelText"></div><div class="kp-pixel-actions"><button type="button" id="kpPixelClose">Cerrar</button><button type="button" id="kpPixelContext">Contexto</button><button type="button" id="kpPixelDone">Completar</button></div></div>';document.body.appendChild(sheet);$("#kpPixelClose").onclick=closeMissionDialog}if(!$("#kpQuestWin")){const win=document.createElement("div");win.id="kpQuestWin";win.className="kp-quest-win";win.setAttribute("role","dialog");win.setAttribute("aria-modal","true");win.setAttribute("aria-hidden","true");win.innerHTML='<div class="kp-win-card"><div class="kp-win-icon" id="kpWinIcon" aria-hidden="true">🐉</div><div class="kp-win-kicker">MISIÓN COMPLETADA</div><div class="kp-win-title" id="kpWinTitle"></div><div class="kp-win-text" id="kpWinText"></div><div class="kp-win-reward" id="kpWinReward"></div><div class="kp-win-milestone" id="kpWinMilestone"></div><button type="button" id="kpWinClose">Seguir la aventura</button></div>';document.body.appendChild(win);const close=()=>{win.classList.remove("show");win.setAttribute("aria-hidden","true")};$("#kpWinClose").onclick=close;win.onclick=e=>{if(e.target===win)close()}}}
function questSignature(){return D.quests.map(q=>done(q.poi)?1:0).join("")}
function renderQuestWorld(force=false){ensureQuestUI();const host=$("#kpQuestWorld");if(!host)return false;const sig=questSignature();if(!force&&sig===questSig)return false;questSig=sig;const finished=completed();host.innerHTML=`<div class="kp-world-frame"><div class="kp-world-top"><div><div class="kp-world-kicker">Kraków Quest</div><div class="kp-world-title">Las Escamas de Wawel</div></div><div class="kp-world-score"><span>🐉 ${score()}</span><small>${finished}/${D.quests.length} misiones</small></div></div><div class="kp-world-map" role="group" aria-label="Mapa ilustrado de encargos de Cracovia">${D.quests.map(q=>{const p=poi(q.poi),xy=POS[q.poi]||[50,50],isDone=done(q.poi),label=`${p?.name||q.title}${isDone?", completada":""}`;return `<button type="button" class="kp-world-node ${isDone?"done":""}" data-pixel-poi="${q.poi}" aria-label="${esc(label)}" style="left:${xy[0]}%;top:${xy[1]}%"><span class="kp-node-icon"><span class="kp-landmark-art" data-landmark="${q.poi}"></span></span><span class="kp-node-badge" aria-hidden="true">${isDone?"★":"!"}</span><small>${esc(p?.name||q.title)}</small></button>`}).join("")}</div><div class="kp-world-tip">Toca un lugar con <b>!</b> para abrir su misión. Las completadas quedan marcadas con ★.<div class="kp-world-controls"><button type="button" id="kpGameUndoMission">↩ Deshacer última</button><button type="button" id="kpGameResetMissions">Reiniciar misiones</button></div></div></div>`;host.querySelectorAll("[data-pixel-poi]").forEach(b=>b.onclick=()=>openMission(b.dataset.pixelPoi,b));$("#kpGameUndoMission").onclick=()=>APP.undoLastMission();$("#kpGameResetMissions").onclick=()=>APP.resetMissions();$("#kpGameUndoMission").disabled=!finished;$("#kpGameResetMissions").disabled=!finished;return true}
function openMission(id,trigger=null,focus=true){const q=quest(id),p=poi(id),sheet=$("#kpQuestDialog");if(!q||!sheet)return;lastMissionTrigger=trigger||lastMissionTrigger;sheet.dataset.poi=id;const isDone=done(id);$("#kpPixelName").textContent=`${p?.name||"Cracovia"} · +${q.points} 🐉`;$("#kpPixelText").textContent=q.text;sheet.querySelector(".kp-pixel-portrait").textContent=p?.emoji||"🐉";const d=$("#kpPixelDone");d.textContent=isDone?"✓ Completada":"Completar";d.disabled=isDone;d.onclick=()=>{closeMissionDialog();if(!done(id)&&APP.setMission(id,true))setTimeout(()=>showCelebration(id),120)};$("#kpPixelContext").onclick=()=>{closeMissionDialog();APP.openStory(id)};sheet.classList.add("show");sheet.setAttribute("aria-hidden","false");if(focus)setTimeout(()=>d.focus({preventScroll:true}),30)}
function showCelebration(id){const q=quest(id),p=poi(id),win=$("#kpQuestWin");if(!q||!win)return;const finished=completed(),copy=CHEERS[id]||["¡Misión superada!","Cracovia acaba de entregaros otra pequeña victoria."],milestones={3:"🌱 Tres misiones. Ya no sois turistas: sois aprendices de dragón.",6:"⚔️ Mitad de la aventura. El dragón empieza a ponerse nervioso.",9:"👑 Nueve misiones. Wawel ya debería ir preparando vuestro retrato.",12:"🏆 ¡LAS 12 ESCAMAS! Cracovia completada. El Dragón de Wawel acepta la derrota."};$("#kpWinIcon").textContent=p?.emoji||"🐉";$("#kpWinTitle").textContent=copy[0];$("#kpWinText").textContent=copy[1];$("#kpWinReward").textContent=`+${q.points} 🐉 · ${score()} escamas · ${finished}/${D.quests.length}`;const m=$("#kpWinMilestone");m.textContent=milestones[finished]||"";m.hidden=!milestones[finished];win.classList.add("show");win.setAttribute("aria-hidden","false");setTimeout(()=>$("#kpWinClose")?.focus({preventScroll:true}),30);navigator.vibrate?.([35,45,35])}
function ensureNav(){const labels={home:"Aldea",mapPanel:"Mapa",quests:"Encargos",diary:"Crónica",budget:"Bolsa"},ready=[...document.querySelectorAll('.tab[data-panel]')].length===5&&[...document.querySelectorAll('.tab[data-panel] b[data-nav-art]')].length===5;if(navReady&&ready)return;for(const [id,label] of Object.entries(labels)){const t=$(`.tab[data-panel="${id}"]`);if(t)t.innerHTML=`<b data-nav-art="${id}" aria-hidden="true"></b>${label}`}navReady=true}
function refresh(force=false){document.documentElement.classList.add("kp-game");const openPoi=$("#kpQuestDialog.show")?.dataset.poi||"";renderChrome(force);renderHub(force);const questChanged=renderQuestWorld(force);ensureNav();if(questChanged&&openPoi&&quest(openPoi)){lastMissionTrigger=$(`#kpQuestWorld [data-pixel-poi="${openPoi}"]`)||null;openMission(openPoi,lastMissionTrigger,false)}window.dispatchEvent(new Event("kp:game-render"))}
function bind(){refresh(true);window.addEventListener("kp:render",()=>refresh(false));window.addEventListener("pageshow",()=>refresh(true));document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if($("#kpQuestDialog.show")){closeMissionDialog();return}const win=$("#kpQuestWin.show");if(win){win.classList.remove("show");win.setAttribute("aria-hidden","true")}})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();