(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",PLAYER="krakowPlayer",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const score=s=>D.quests.filter(q=>done(s,q.poi)).reduce((a,q)=>a+(+q.points||0),0);
const completed=s=>D.quests.filter(q=>done(s,q.poi)).length;
const spent=s=>activeExpenses(s).reduce((a,x)=>a+(+x.amount||0),0);
const poi=id=>D.pois.find(p=>p.id===id),quest=id=>D.quests.find(q=>q.poi===id);
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const POS={florian:[17,14],maria:[50,14],planty:[82,14],maius:[18,37],tomasza:[50,37],szeroka:[82,37],dragon:[18,60],bernatek:[50,60],placnowy:[82,60],wawel:[18,82],rynek:[50,82],ghetto:[82,82]};
const CHEERS={florian:["¡La ciudad os deja pasar!","La puerta medieval ha decidido que sois gente de fiar. De momento."],rynek:["¡Ojos de explorador desbloqueados!","Rynek: 0 · Ismael y Laura: 1. Habéis visto algo que el otro casi se pierde."],maria:["¡Hejnał localizado!","El trompetista invisible aprueba vuestra capacidad para mirar hacia arriba."],maius:["¡Secreto universitario descubierto!","Copérnico probablemente estaría orgulloso. O al menos ligeramente impresionado."],wawel:["¡Territorio real conquistado!","Sin corona, sin caballo y aun así habéis llegado a Wawel. Nada mal."],dragon:["¡ESCAMA LEGENDARIA!","El Dragón de Wawel os reconoce oficialmente como pareja aventurera. No incluye inmunidad al fuego."],szeroka:["¡Kazimierz os cuenta sus capas!","Habéis hecho lo difícil: mirar el barrio en vez de simplemente atravesarlo."],placnowy:["¡Economía de mercado dominada!","Comparar precios antes de comprar: más escamas y menos posibilidades de turistada."],bernatek:["¡Puente entre mundos cruzado!","Un barrio detrás, otro delante y vosotros dos en medio. Cinematográfico."],ghetto:["Misión de memoria completada","Aquí no toca bromear demasiado. Gracias por parar, mirar y dedicarle tiempo al lugar."],tomasza:["¡Maestros del złoty!","Comer caliente sin destruir el presupuesto: habilidad épica desbloqueada."],planty:["¡Descanso profesional!","Habéis completado una misión haciendo… nada. Planty estaría orgulloso."]};

const svg=b=>`<svg class="kp-art" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${b}</svg>`;
const W="#5b3927",DARK="#33241c",ASH="#b8b1a4",HAIR="#3a2b28";
function person(who){const hair=who==="Ismael"?ASH:HAIR,shirt=who==="Ismael"?"#6d7f49":"#9c604a";return svg(`<defs><linearGradient id="s${who}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffd4aa"/><stop offset="1" stop-color="#e9a977"/></linearGradient></defs><ellipse cx="60" cy="108" rx="29" ry="7" fill="#3a281c" opacity=".16"/><path d="M31 102q1-27 14-36l15-7 16 7q13 10 13 36z" fill="#6d4b31" stroke="${W}" stroke-width="4"/><path d="M42 73h36v29H42z" fill="${shirt}" stroke="${W}" stroke-width="3"/><circle cx="60" cy="47" r="25" fill="url(#s${who})" stroke="${W}" stroke-width="4"/><path d="M35 48q0-31 25-32 26 0 29 27-10-7-18-8-10-8-19-3-8-2-17 16z" fill="${hair}" stroke="${W}" stroke-width="4"/><path d="M37 38q10-15 23-18M43 34q11-11 25-14M56 32q11-8 24-6" fill="none" stroke="${who==="Ismael"?"#d5d0c5":"#51413b"}" stroke-width="3" stroke-linecap="round"/><ellipse cx="50" cy="49" rx="4" ry="5" fill="#2a211d"/><ellipse cx="70" cy="49" rx="4" ry="5" fill="#2a211d"/><circle cx="51" cy="47" r="1.3" fill="#fff"/><circle cx="71" cy="47" r="1.3" fill="#fff"/><path d="M52 61q8 5 16 0" fill="none" stroke="#a65f4f" stroke-width="2.5" stroke-linecap="round"/>`)}
function building(c1="#d7b47d",c2="#6c7180"){return svg(`<ellipse cx="60" cy="106" rx="42" ry="7" fill="#3d2c1e" opacity=".14"/><path d="M17 53 60 20l43 33v44H17z" fill="${c1}" stroke="${W}" stroke-width="4"/><path d="M12 53 60 15l48 38" fill="none" stroke="${c2}" stroke-width="9" stroke-linejoin="round"/><rect x="52" y="72" width="16" height="25" fill="#74513a"/><rect x="28" y="60" width="12" height="14" fill="#6d91a3"/><rect x="80" y="60" width="12" height="14" fill="#6d91a3"/>`)}
function castle(){return svg(`<ellipse cx="60" cy="106" rx="45" ry="7" fill="#4b3322" opacity=".16"/><path d="M18 96V46h23V29h38v17h23v50z" fill="#ddd5c1" stroke="${W}" stroke-width="4"/><path d="M12 47 29 25l17 22M74 47 91 25l17 22M44 29 60 12l16 17" fill="#b8493a" stroke="${W}" stroke-width="4"/><rect x="53" y="69" width="14" height="27" rx="3" fill="#75503a"/>`)}
function basilica(){return svg(`<ellipse cx="60" cy="107" rx="42" ry="7" fill="#3f2d21" opacity=".14"/><rect x="25" y="50" width="70" height="48" fill="#c87848" stroke="${W}" stroke-width="4"/><rect x="27" y="25" width="22" height="58" fill="#b75f38" stroke="${W}" stroke-width="4"/><rect x="70" y="18" width="23" height="65" fill="#ae5936" stroke="${W}" stroke-width="4"/><path d="M24 25 38 8l14 17M67 18 81 2l15 16" fill="#506f65" stroke="${W}" stroke-width="4"/><circle cx="82" cy="44" r="6" fill="#f2e3b9" stroke="${W}" stroke-width="3"/>`)}
function tree(){return svg(`<ellipse cx="60" cy="105" rx="43" ry="8" fill="#3d2b1d" opacity=".14"/><rect x="57" y="66" width="8" height="30" fill="#745034"/><circle cx="60" cy="49" r="31" fill="#5e9347" stroke="${W}" stroke-width="4"/><circle cx="39" cy="59" r="20" fill="#72a957"/><circle cx="82" cy="59" r="20" fill="#79af59"/><circle cx="58" cy="28" r="17" fill="#88ba65"/>`)}
function dragon(){return svg(`<ellipse cx="57" cy="104" rx="42" ry="7" fill="#3d2b1e" opacity=".16"/><path d="M29 87q-8-31 16-48 18-12 36-3-10 4-12 13 22 3 21 22-1 23-28 29-22 4-33-13z" fill="#68a84e" stroke="${W}" stroke-width="4"/><path d="M45 44 33 24l20 10M54 39 48 17l18 15" fill="#d7b748" stroke="${W}" stroke-width="3"/><circle cx="72" cy="46" r="4" fill="#251d19"/><path d="M80 54q19 1 28 12-14 0-23 8" fill="#f19a3e" stroke="#a85b2d" stroke-width="3"/>`)}
function bridge(){return svg(`<ellipse cx="60" cy="101" rx="44" ry="6" fill="#402d20" opacity=".15"/><path d="M10 74q20-34 50 0 30-34 50 0" fill="none" stroke="#5f3b28" stroke-width="9"/><path d="M10 74h100" stroke="#8c5f38" stroke-width="8"/><path d="M22 56v35M60 50v41M98 56v35" stroke="#3f2c21" stroke-width="4"/>`)}
function bowl(){return svg(`<ellipse cx="60" cy="102" rx="41" ry="7" fill="#3f2d20" opacity=".13"/><path d="M21 58q5-28 39-28t39 28z" fill="#f6ead0" stroke="${W}" stroke-width="4"/><ellipse cx="60" cy="73" rx="39" ry="18" fill="#ddd3bf" stroke="${W}" stroke-width="4"/><path d="M35 51q10 14 20 3 11 12 25-2" fill="none" stroke="#6ba157" stroke-width="7"/>`)}
function bagel(){return svg(`<ellipse cx="60" cy="101" rx="37" ry="7" fill="#39291e" opacity=".13"/><ellipse cx="60" cy="58" rx="38" ry="30" fill="#c88945" stroke="${W}" stroke-width="5"/><ellipse cx="60" cy="58" rx="14" ry="11" fill="#f6e8c5" stroke="#87542e" stroke-width="4"/>`)}
function chairs(){return svg(`<ellipse cx="60" cy="106" rx="39" ry="7" fill="#3d2a1e" opacity=".14"/><path d="M27 25v68M76 25v68M27 52h49M20 93h22M63 93h26" stroke="#6b4c35" stroke-width="9" stroke-linecap="round"/>`)}
const ART={florian:castle(),maria:basilica(),planty:tree(),maius:building("#d9bd88","#697583"),tomasza:bowl(),szeroka:building("#d7a06b","#a64b37"),dragon:dragon(),bernatek:bridge(),placnowy:bagel(),wawel:castle(),rynek:building("#d4c5a2","#806c53"),ghetto:chairs()};
function navArt(id){const art={home:building("#efc77d","#9c4636"),mapPanel:svg(`<path d="M13 20 40 14l22 8 45-7v78l-45 9-22-9-27 6z" fill="#8fc5a2" stroke="${W}" stroke-width="5"/><path d="M40 14v79M62 22v80" stroke="#fff0c5" stroke-width="3"/>`),quests:svg(`<path d="M28 13h64v92H28z" fill="#f2dfab" stroke="${W}" stroke-width="6"/><path d="M37 32h44M37 48h39M37 64h43M37 80h32" stroke="#a17b50" stroke-width="5"/>`),diary:svg(`<path d="M10 25q22-10 48 4v72q-24-15-48-4zM110 25q-22-10-48 4v72q24-15 48-4z" fill="#f8e8bb" stroke="${W}" stroke-width="5"/>`),budget:svg(`<path d="M28 39q4-22 32-22t32 22l8 61H20z" fill="#9d6439" stroke="${W}" stroke-width="6"/>`)};return art[id]||""}

function worldSvg(){let flowers="";for(let i=0;i<48;i++){const x=(i*173)%960+20,y=(i*257)%1180+30,c=["#f3d866","#fff0c8","#e69374","#d889b0"][i%4];flowers+=`<g transform="translate(${x} ${y})" opacity=".75"><circle r="3.2" fill="${c}"/><circle cx="6" cy="2" r="2.4" fill="${c}"/><path d="M2 5v13" stroke="#4f7d42" stroke-width="2"/></g>`}return `<svg class="kp-world-art" viewBox="0 0 1000 1260" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="grass" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#b6db84"/><stop offset=".55" stop-color="#95c36b"/><stop offset="1" stop-color="#7eae5c"/></linearGradient><linearGradient id="river" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#68b5d0"/><stop offset=".45" stop-color="#8cd3e8"/><stop offset="1" stop-color="#56a5c2"/></linearGradient></defs><rect width="1000" height="1260" fill="url(#grass)"/><path d="M650-40C610 165 718 270 651 440S541 756 605 924s40 255-12 376" fill="none" stroke="#d9c578" stroke-width="142"/><path d="M650-40C610 165 718 270 651 440S541 756 605 924s40 255-12 376" fill="none" stroke="url(#river)" stroke-width="118"/><g fill="none" stroke="#d7b66c" stroke-width="54" stroke-linecap="round"><path d="M40 170C220 215 345 190 490 250S785 320 960 265"/><path d="M85 470C285 430 415 500 520 555S770 650 935 600"/><path d="M70 790C205 745 365 770 500 850S760 905 945 835"/><path d="M170 1130C315 1070 470 1020 605 1050S820 1150 950 1110"/><path d="M270 80C240 280 315 400 286 615S245 990 315 1200"/></g><g>${flowers}</g>${worldTrees()}</svg>`}
function worldTrees(){const pts=[[75,110,42],[905,125,55],[95,360,50],[878,380,44],[118,685,55],[900,725,52],[100,1000,44],[850,1020,50],[420,90,30],[430,690,34],[740,925,31],[735,520,36]];return pts.map(([x,y,r],i)=>`<g transform="translate(${x} ${y})"><ellipse cy="${r*.8}" rx="${r*.45}" ry="${r*.16}" fill="#486737" opacity=".22"/><rect x="-7" y="${r*.25}" width="14" height="${r*.8}" rx="5" fill="#765034"/><circle cy="0" r="${r}" fill="${i%2?'#5f9448':'#6aa34f'}" stroke="#4e7a3b" stroke-width="6"/><circle cx="-${r*.35}" cy="${-r*.08}" r="${r*.45}" fill="#80b65e" opacity=".72"/></g>`).join("")}

function currentObjective(){const title=$("#recTitle")?.textContent?.trim(),text=$("#recText")?.textContent?.trim();if(title&&title!=="Calculando…"&&title!=="Calculando...")return["🚌",title,text||"La siguiente parte de la aventura os espera."];const s=read(),q=D.quests.find(x=>!done(s,x.poi));return q?["📜",q.title,q.text]:["🐉","Aventura principal completada","Habéis conseguido todas las escamas de Wawel."]}
function ensureChrome(){const app=$(".app"),content=$(".content");if(!app||!content)return;let hud=$("#kpGameHud");if(!hud){hud=document.createElement("header");hud.id="kpGameHud";app.insertBefore(hud,content)}if(!$("#kpGameObjective")){const o=document.createElement("section");o.id="kpGameObjective";app.insertBefore(o,content)}const banner=$("#updateBanner");if(banner&&banner.parentElement!==app)app.insertBefore(banner,content)}
function renderChrome(){ensureChrome();const s=read(),player=localStorage.getItem(PLAYER)||"Ismael",hud=$("#kpGameHud");if(hud)hud.innerHTML=`<div class="kp-game-brand"><div class="kp-game-portrait">${person(player)}</div><div class="kp-game-logo"><strong>Kraków Pocket</strong><span>Aventura para dos</span></div><button class="kp-game-settings" id="kpGameSettings" aria-label="Menú de partida">⚙️</button></div><div class="kp-game-resources"><div class="kp-game-resource"><b>🐉 ${score(s)}</b><span>Escamas</span></div><div class="kp-game-resource"><b>${spent(s).toFixed(2).replace('.',',')} €</b><span>Monedas</span></div><div class="kp-game-resource"><b>${completed(s)}/${D.quests.length}</b><span>Misiones</span></div></div>`;$("#kpGameSettings")?.addEventListener("click",()=>$("#openSettings")?.click(),{once:true});const o=currentObjective(),obj=$("#kpGameObjective");if(obj)obj.innerHTML=`<div class="kp-objective-icon">${o[0]}</div><div class="kp-objective-copy"><b>${esc(o[1])}</b><span>${esc(o[2]||"")}</span></div><div class="kp-objective-count">📋 ${completed(s)}/${D.quests.length}</div>`}

function gameMessage(s){const n=completed(s);if(n>=D.quests.length)return["🐉 Dragón de Wawel","¡Habéis reunido todas las escamas! Cracovia ya es territorio de aventureros."];if(n>=9)return["🐉 Dragón de Wawel","Os quedan muy pocas escamas. Wawel empieza a considerar seriamente vuestra candidatura a leyenda."];if(n>=6)return["🧙 Guardián del viaje","Ya habéis superado la mitad. Las mejores misiones aparecen cuando miráis alrededor."];return["🐉 Dragón de Wawel",n?`Lleváis ${n} de ${D.quests.length} misiones. Hay otra escama escondida ahí fuera.`:"Toda aventura empieza con una puerta. Buscad el primer ! y empezad a mirar Cracovia como jugadores."]}
function ensureHub(){const home=$("#home");if(!home||$("#kpGameHub"))return;const h=document.createElement("section");h.id="kpGameHub";home.insertBefore(h,home.firstChild)}
function renderHub(){ensureHub();const host=$("#kpGameHub");if(!host)return;const s=read(),pending=D.quests.length-completed(s),msg=gameMessage(s);host.innerHTML=`<div class="kp-hub-frame"><div class="kp-hub-world"><div class="kp-hub-river"></div><div class="kp-hub-path h1"></div><div class="kp-hub-path h2"></div><button class="kp-hub-place base" data-go="home"><span class="building">${building("#efc77d","#9c4636")}</span><small>Base</small></button><button class="kp-hub-place quests" data-go="quests"><span class="building">${navArt("quests")}</span>${pending?'<span class="alert">!</span>':''}<small>Encargos</small></button><button class="kp-hub-place map" data-go="mapPanel"><span class="building">${navArt("mapPanel")}</span><small>Mapa</small></button><button class="kp-hub-place diary" data-go="diary"><span class="building">${navArt("diary")}</span><small>Crónica</small></button><button class="kp-hub-place budget" data-go="budget"><span class="building">${navArt("budget")}</span><small>Bolsa</small></button><div class="kp-hub-couple"><span class="kp-couple-art">${person("Ismael")}</span><span class="kp-couple-art">${person("Laura")}</span></div></div><div class="kp-hub-dialog"><div class="kp-hub-avatar">${msg[0].startsWith("🐉")?"🐉":"🧙"}</div><div><div class="kp-hub-speaker">${msg[0]}</div><div class="kp-hub-message">${msg[1]}</div><div class="kp-hub-hint">Toca un edificio para entrar · ${completed(s)}/${D.quests.length} misiones</div></div></div></div>`;host.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>document.querySelector(`.tab[data-panel="${b.dataset.go}"]`)?.click())}

function ensureQuestUI(){const panel=$("#quests");if(!panel)return;if(!$("#kpQuestWorld")){const world=document.createElement("div");world.id="kpQuestWorld";panel.insertBefore(world,panel.firstChild)}if(!$("#kpQuestDialog")){const sheet=document.createElement("div");sheet.id="kpQuestDialog";sheet.className="kp-pixel-dialog";sheet.innerHTML='<div class="kp-pixel-portrait">🐉</div><div><div class="kp-pixel-name" id="kpPixelName"></div><div class="kp-pixel-text" id="kpPixelText"></div><div class="kp-pixel-actions"><button id="kpPixelClose">Cerrar</button><button id="kpPixelContext">Contexto</button><button id="kpPixelDone">Completar</button></div></div>';document.body.appendChild(sheet);$("#kpPixelClose").onclick=()=>sheet.classList.remove("show")}if(!$("#kpQuestWin")){const win=document.createElement("div");win.id="kpQuestWin";win.className="kp-quest-win";win.innerHTML='<div class="kp-win-card"><div class="kp-win-icon" id="kpWinIcon">🐉</div><div class="kp-win-kicker">MISIÓN COMPLETADA</div><div class="kp-win-title" id="kpWinTitle"></div><div class="kp-win-text" id="kpWinText"></div><div class="kp-win-reward" id="kpWinReward"></div><div class="kp-win-milestone" id="kpWinMilestone"></div><button id="kpWinClose">Seguir la aventura</button></div>';document.body.appendChild(win);$("#kpWinClose").onclick=()=>win.classList.remove("show");win.onclick=e=>{if(e.target===win)win.classList.remove("show")}}}
function renderQuestWorld(){ensureQuestUI();const host=$("#kpQuestWorld");if(!host)return;const s=read(),finished=completed(s);host.innerHTML=`<div class="kp-world-frame"><div class="kp-world-top"><div><div class="kp-world-kicker">Kraków Quest</div><div class="kp-world-title">Las Escamas de Wawel</div></div><div class="kp-world-score"><span>🐉 ${score(s)}</span><small>${finished}/${D.quests.length} misiones</small></div></div><div class="kp-world-map" role="group" aria-label="Mapa ilustrado de encargos de Cracovia">${worldSvg()}${D.quests.map(q=>{const p=poi(q.poi),xy=POS[q.poi]||[50,50],isDone=done(s,q.poi);return `<button class="kp-world-node ${isDone?"done":""}" data-pixel-poi="${q.poi}" aria-label="${esc(p?.name||q.title)}" style="left:${xy[0]}%;top:${xy[1]}%"><span class="kp-node-icon"><span class="kp-landmark-art">${ART[q.poi]||building()}</span></span><span class="kp-node-badge">${isDone?"★":"!"}</span><small>${esc(p?.name||q.title)}</small></button>`}).join("")}</div><div class="kp-world-tip">Toca un lugar con <b>!</b> para abrir su misión. Las completadas quedan marcadas con ★.<div class="kp-world-controls"><button id="kpGameUndoMission">↩ Deshacer última</button><button id="kpGameResetMissions">Reiniciar misiones</button></div></div></div>`;host.querySelectorAll("[data-pixel-poi]").forEach(b=>b.onclick=()=>openMission(b.dataset.pixelPoi));$("#kpGameUndoMission").onclick=()=>$("#kpUndoMission")?.click();$("#kpGameResetMissions").onclick=()=>$("#kpResetMissions")?.click();$("#kpGameUndoMission").disabled=!$("#kpUndoMission");$("#kpGameResetMissions").disabled=!$("#kpResetMissions")}
function openMission(id){const q=quest(id),p=poi(id),s=read(),isDone=done(s,id),sheet=$("#kpQuestDialog");if(!q||!sheet)return;$("#kpPixelName").textContent=`${p?.name||"Cracovia"} · +${q.points} 🐉`;$("#kpPixelText").textContent=q.text;sheet.querySelector(".kp-pixel-portrait").textContent=p?.emoji||"🐉";const d=$("#kpPixelDone");d.textContent=isDone?"✓ Completada":"Completar";d.disabled=isDone;d.onclick=()=>{const b=document.querySelector(`.q-done[data-poi="${CSS.escape(id)}"]`);if(!b)return;sessionStorage.setItem("kpCelebrateMission",id);sheet.classList.remove("show");b.click()};$("#kpPixelContext").onclick=()=>{sheet.classList.remove("show");document.querySelector(`.q-context[data-poi="${CSS.escape(id)}"]`)?.click()};sheet.classList.add("show")}
function showCelebration(id){const q=quest(id),p=poi(id),s=read(),win=$("#kpQuestWin");if(!q||!win)return;const finished=completed(s),copy=CHEERS[id]||["¡Misión superada!","Cracovia acaba de entregaros otra pequeña victoria."],milestones={3:"🌱 Tres misiones. Ya no sois turistas: sois aprendices de dragón.",6:"⚔️ Mitad de la aventura. El dragón empieza a ponerse nervioso.",9:"👑 Nueve misiones. Wawel ya debería ir preparando vuestro retrato.",12:"🏆 ¡LAS 12 ESCAMAS! Cracovia completada. El Dragón de Wawel acepta la derrota."};$("#kpWinIcon").textContent=p?.emoji||"🐉";$("#kpWinTitle").textContent=copy[0];$("#kpWinText").textContent=copy[1];$("#kpWinReward").textContent=`+${q.points} 🐉 · ${score(s)} escamas · ${finished}/${D.quests.length}`;const m=$("#kpWinMilestone");m.textContent=milestones[finished]||"";m.style.display=milestones[finished]?"block":"none";win.classList.add("show");navigator.vibrate?.([35,45,35])}

function renameNav(){const labels={home:"Aldea",mapPanel:"Mapa",quests:"Encargos",diary:"Crónica",budget:"Bolsa"};for(const [id,label] of Object.entries(labels)){const t=document.querySelector(`.tab[data-panel="${id}"]`);if(!t)continue;t.innerHTML=`<b><span class="kp-nav-art">${navArt(id)}</span></b>${label}`}}
function installMapsBridge(){if(window.__kpMapsBridge)return;window.__kpMapsBridge=true;const nativeOpen=window.open.bind(window);window.open=function(url,target,features){const raw=String(url||"");if(!/google\.(com|[a-z.]+)\/maps|maps\.google\./i.test(raw))return nativeOpen(url,target,features);try{const u=new URL(raw,location.href),q=u.searchParams.get("query")||u.searchParams.get("q"),dest=u.searchParams.get("destination"),origin=u.searchParams.get("origin"),mode=u.searchParams.get("travelmode")||"walking";const scheme=q?`comgooglemaps://?q=${encodeURIComponent(q)}`:dest?`comgooglemaps://?saddr=${encodeURIComponent(origin||"")}&daddr=${encodeURIComponent(dest)}&directionsmode=${encodeURIComponent(mode)}`:null;if(!scheme)return nativeOpen(raw,target,features);let left=false;const vis=()=>{if(document.hidden)left=true};document.addEventListener("visibilitychange",vis,{once:true});location.href=scheme;setTimeout(()=>{if(!left&&document.visibilityState==="visible")location.href=raw},900);return null}catch{return nativeOpen(raw,target,features)}}}
function installUpdater(){if(!('serviceWorker' in navigator)||window.__kpUpdater)return;window.__kpUpdater=true;const banner=$("#updateBanner"),button=$("#applyUpdate");let reg=null,reloading=false;const hide=()=>{if(banner)banner.style.display="none"},show=()=>{if(banner)banner.style.display="flex";if(button){button.disabled=false;button.textContent="Actualizar"}},activate=()=>{if(!reg?.waiting)return;if(button){button.disabled=true;button.textContent="Actualizando…"}reg.waiting.postMessage({type:"SKIP_WAITING"})};button?.addEventListener("click",e=>{e.preventDefault();activate()},true);navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloading)return;reloading=true;hide();setTimeout(()=>location.reload(),100)});navigator.serviceWorker.ready.then(r=>{reg=r;const inspect=()=>reg.waiting&&navigator.serviceWorker.controller?show():hide();inspect();reg.addEventListener("updatefound",()=>{const w=reg.installing;w?.addEventListener("statechange",()=>{if(w.state==="installed")inspect()})});reg.update().catch(()=>{});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")reg.update().catch(()=>{})})}).catch(hide)}
function patchStorageForCelebrations(){if(window.__kpStoragePatched)return;window.__kpStoragePatched=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(this===localStorage&&key===STORAGE){const before=read();original.call(this,key,value);let after={};try{after=JSON.parse(value||"{}")}catch{}for(const q of D.quests){if(!done(before,q.poi)&&done(after,q.poi))sessionStorage.setItem("kpCelebrateMission",q.poi)}return}return original.call(this,key,value)}}
function auditLayout(){const selectors=["#kpGameHud","#kpGameObjective",".card",".smart-card",".bottom",".tab",".kp-world-top",".kp-world-node small"];for(const sel of selectors)for(const el of $$(sel)){el.classList.remove("kp-overflow-fix","kp-text-tight");if(el.scrollWidth>el.clientWidth+3){el.classList.add("kp-overflow-fix");if(el.matches(".tab,.kp-world-node small,.kp-game-logo"))el.classList.add("kp-text-tight")}}}
function refresh(){document.documentElement.classList.add("kp-game");renderChrome();renderHub();renderQuestWorld();renameNav();requestAnimationFrame(auditLayout);const ver=$("#settingsVersion");if(ver)ver.textContent="Kraków Pocket · v6.0"}
function bind(){patchStorageForCelebrations();installMapsBridge();installUpdater();refresh();setTimeout(refresh,250);for(const t of $$(".tab[data-panel]"))t.addEventListener("click",()=>setTimeout(refresh,30));$("#playerSelect")?.addEventListener("change",()=>setTimeout(refresh,0));window.addEventListener("storage",()=>setTimeout(refresh,0));window.addEventListener("online",refresh);window.addEventListener("offline",refresh);window.addEventListener("resize",()=>requestAnimationFrame(auditLayout),{passive:true});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refresh()});const celebrate=sessionStorage.getItem("kpCelebrateMission");if(celebrate){sessionStorage.removeItem("kpCelebrateMission");setTimeout(()=>showCelebration(celebrate),450)}setInterval(()=>{if(document.visibilityState==="visible")renderChrome()},30000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();
