(() => {
"use strict";
const STORAGE="krakowPocketCoop",nativeSet=Storage.prototype.setItem,nativeInterval=window.setInterval.bind(window);
const SUPABASE_URL="https://ahzmwkztlakejmrvgcdm.supabase.co",SUPABASE_KEY="sb_publishable_sf-RddHTp5jdFCQOfRBBsQ_PZGKOlxJ",nativeFetch=window.fetch.bind(window);
/* The restored app had a one-character typo in its publishable Supabase key. Correct the transport header before app.js runs without changing the proven pre-cleanup core. */
window.fetch=function(input,init){let next=init?{...init}:{};try{const url=typeof input==="string"?input:(input&&input.url)||"";if(url.startsWith(SUPABASE_URL)){const baseHeaders=next.headers||(typeof Request!=="undefined"&&input instanceof Request?input.headers:undefined),headers=new Headers(baseHeaders||{});headers.set("apikey",SUPABASE_KEY);next.headers=headers}}catch{}return nativeFetch(input,next)};
window.setInterval=function(fn,delay,...args){let ms=Number(delay)||0;if(ms===900)ms=30000;else if(ms===1800)ms=30000;else if(ms===4000)ms=15000;return nativeInterval(fn,ms,...args)};
window.addEventListener("load",()=>setTimeout(()=>{window.setInterval=nativeInterval},0),{once:true});
function loadCompat(){if(!document.querySelector('link[data-kp-compat]')){const l=document.createElement("link");l.rel="stylesheet";l.href="./compat.css?v=6800";l.dataset.kpCompat="1";document.head.appendChild(l)}if(!document.querySelector('script[data-kp-compat]')){const s=document.createElement("script");s.src="./compat.js?v=6800";s.async=false;s.dataset.kpCompat="1";document.head.appendChild(s)}}
loadCompat();
const safeParse=v=>{try{return JSON.parse(v||"{}")}catch{return null}};
const questIds=()=>new Set((window.KP_DATA?.quests||[]).map(q=>q.poi));
function normalizeMissionState(s){if(!s||typeof s!=="object")return s;if(!Array.isArray(s.visited))s.visited=[];if(!Array.isArray(s.expenses))s.expenses=[];if(!Array.isArray(s.memories))s.memories=[];if(!s.config||typeof s.config!=="object"||Array.isArray(s.config))s.config={};const status=s.missionStatus;if(!status||typeof status!=="object"||Array.isArray(status))return s;const valid=questIds(),v=new Set(s.visited);for(const [id,op] of Object.entries(status)){if(valid.size&&!valid.has(id))continue;if(!op||typeof op!=="object")continue;if(op.done)v.add(id);else v.delete(id)}s.visited=[...v];return s}
function sameVisited(a,b){const x=[...(a||[])].sort(),y=[...(b||[])].sort();return x.length===y.length&&x.every((v,i)=>v===y[i])}
function normalizeBootState(){const parsed=safeParse(localStorage.getItem(STORAGE));if(!parsed)return;const before=[...(parsed.visited||[])],normalized=normalizeMissionState(parsed);if(!sameVisited(before,normalized.visited))nativeSet.call(localStorage,STORAGE,JSON.stringify(normalized))}
normalizeBootState();if(window.KP_DATA)window.KP_DATA.version="6.8.1";
function emitState(detail={}){queueMicrotask(()=>{window.dispatchEvent(new CustomEvent("kp:statechange",{detail}));window.dispatchEvent(new Event("storage"))})}
Storage.prototype.setItem=function(key,value){if(this!==localStorage||key!==STORAGE)return nativeSet.call(this,key,value);const parsed=safeParse(value);if(!parsed)return nativeSet.call(this,key,value);const before=[...(parsed.visited||[])],normalized=normalizeMissionState(parsed),repaired=!sameVisited(before,normalized.visited);nativeSet.call(this,key,JSON.stringify(normalized));emitState({repaired});if(repaired&&sessionStorage.getItem("kpMissionMutation")!=="1"&&!window.__kpRepairReload){window.__kpRepairReload=true;setTimeout(()=>location.reload(),180)}return undefined};
const read=()=>normalizeMissionState(safeParse(localStorage.getItem(STORAGE))||{});
const num=n=>Number(n||0).toFixed(2).replace(".",",");
function summary(){const D=window.KP_DATA||{quests:[]},s=read(),status=s.missionStatus||{},isDone=id=>status[id]?!!status[id].done:(s.visited||[]).includes(id),done=(D.quests||[]).filter(q=>isDone(q.poi)),score=done.reduce((a,q)=>a+(+q.points||0),0),expenses=(s.expenses||[]).filter(x=>x&&!x.deletedAt),spent=expenses.reduce((a,x)=>a+(+x.amount||0),0),memories=(s.memories||[]).filter(x=>x&&!x.deletedAt).sort((a,b)=>new Date(b.ts||0)-new Date(a.ts||0)),lines=["Kraków Pocket · Ismael + Laura",`Misiones: ${done.length}/${D.quests?.length||12} · ${score} escamas`,`Gasto variable: ${num(spent)}€`,`Recuerdos guardados: ${memories.length}`];if(memories.length){lines.push("","Últimos recuerdos:");memories.slice(0,5).forEach(m=>lines.push(`• ${m.title||"Recuerdo"}${m.place?` · ${m.place}`:""}${m.note?`: ${m.note}`:""}`))}lines.push("",`${location.origin}${location.pathname}`);return lines.join("\n")}
async function share(){const text=summary();try{if(navigator.share){await navigator.share({title:"Kraków Pocket · nuestro viaje",text});return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);alert("Resumen copiado al portapapeles.");return}prompt("Copia vuestro resumen:",text)}catch(e){if(e?.name!=="AbortError")prompt("Copia vuestro resumen:",text)}}
function networkClass(){document.documentElement.classList.toggle("kp-offline-state",!navigator.onLine)}
function installToastGuard(){const t=document.getElementById("toast");if(!t||t.dataset.kpGuard)return;t.dataset.kpGuard="1";let timer=0;const hide=()=>{if(t.style.display!=="none")t.style.display="none"};const arm=()=>{clearTimeout(timer);if(t.style.display!=="none"&&t.textContent.trim())timer=setTimeout(hide,2800)};new MutationObserver(arm).observe(t,{childList:true,characterData:true,subtree:true,attributes:true,attributeFilter:["style"]});arm()}
function storageHealth(){const key="kp_runtime_probe";try{localStorage.setItem(key,"1");localStorage.removeItem(key);return true}catch{return false}}
function runAudit(){const required=["phaseLabel","heroTitle","home","mapPanel","quests","diary","budget","settingsSheet","storyDialog","toast"],missing=required.filter(id=>!document.getElementById(id));const s=read(),stateOk=Array.isArray(s.visited)&&Array.isArray(s.expenses)&&Array.isArray(s.memories)&&!!s.config;window.KP_RUNTIME_AUDIT={version:"6.8.1",timestamp:new Date().toISOString(),missing,stateOk,storageOk:storageHealth(),online:navigator.onLine,serviceWorker:"serviceWorker" in navigator,secureContext:window.isSecureContext};document.documentElement.classList.toggle("kp-runtime-warning",missing.length>0||!stateOk||!window.KP_RUNTIME_AUDIT.storageOk)}
function applyTheme(){const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content="#4e2e1d"}
document.addEventListener("click",e=>{const b=e.target.closest?.("#kpShareSummary");if(!b)return;e.preventDefault();e.stopImmediatePropagation();share()},true);
function boot(){applyTheme();installToastGuard();networkClass();runAudit();document.documentElement.dataset.kpRuntime="6.8.1"}
window.addEventListener("online",()=>{networkClass();runAudit()});window.addEventListener("offline",()=>{networkClass();runAudit()});window.addEventListener("kp:statechange",()=>setTimeout(runAudit,0));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();