(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop";
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const money=n=>Number(n||0).toFixed(2).replace(".",",");
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const poi=id=>D.pois.find(p=>p.id===id);
const maps=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p?.mapsQuery||`${p?.lat},${p?.lon}`)}`;
const now=()=>new Date();
function spentToday(s){const k=dateKey(now());return activeExpenses(s).filter(x=>dateKey(new Date(x.ts))===k).reduce((a,x)=>a+(+x.amount||0),0)}
function spentTotal(s){return activeExpenses(s).reduce((a,x)=>a+(+x.amount||0),0)}
function elapsedDays(){const n=now(),start=new Date(D.trip.start),end=new Date(D.trip.end);if(n<start)return 0;if(n>=end)return 3;const idx=D.days.findIndex(x=>x.date===dateKey(n));return idx>=0?idx+1:1}
function tripDay(){return D.days.findIndex(x=>x.date===dateKey(now()))}
function fmtLeft(ms){if(ms<=0)return"ahora";const m=Math.floor(ms/60000),d=Math.floor(m/1440),h=Math.floor((m%1440)/60),min=m%60;if(d>0)return`${d}d ${h}h`;if(h>0)return`${h}h ${min}m`;return`${min} min`}
function milestone(){const n=now(),station=new Date(D.trip.stationTarget),out=new Date(D.trip.outbound),arr=new Date(D.trip.start),back=new Date(D.trip.returnDepart),home=new Date(D.trip.returnArrive);if(n<station)return{label:"salir hacia Zachodnia",time:station,emoji:"🎒"};if(n<out)return{label:"bus a Cracovia",time:out,emoji:"🚌"};if(n<arr)return{label:"llegar a Cracovia",time:arr,emoji:"🏰"};if(n<back)return{label:"bus de vuelta",time:back,emoji:"🚌"};if(n<home)return{label:"llegar a Varsovia",time:home,emoji:"🏠"};return{label:"aventura completada",time:null,emoji:"✨"}}
function routeIds(){const idx=tripDay();if(idx===0)return["mda","w94","florian","rynek","maria","maius","wawel","dragon"];if(idx===1)return["szeroka","placnowy","bernatek","ghetto","planty"];if(idx===2)return D.pois.filter(p=>p.days?.includes(3)&&!["base","bus","shop","food"].includes(p.category)).slice(0,5).map(p=>p.id).concat("mda");return["mda","w94","florian","rynek","wawel","dragon"]}
function remainingRouteMinutes(s){const v=s.visited||[];return routeIds().map(poi).filter(Boolean).filter(p=>!v.includes(p.id)&&!["base","bus"].includes(p.category)).reduce((a,p)=>a+(+p.duration||20),0)}
function fmtMinutes(m){if(m<=0)return"hecha";if(m<60)return`${m} min`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}m`:`${h}h`}
function ensure(){
 if(!$("#kpLiveCard")){const e=document.createElement("article");e.id="kpLiveCard";e.className="card kp-live-card";const rec=$("#recommendation");rec?.insertAdjacentElement("afterend",e)}
 if(!$("#kpPlanB")){const e=document.createElement("article");e.id="kpPlanB";e.className="card kp-planb-card";const route=$("#kpRouteCard");if(route)route.insertAdjacentElement("afterend",e);else $("#home .quick-grid")?.insertAdjacentElement("afterend",e)}
 if(!$("#kpBudgetPulse")){const e=document.createElement("article");e.id="kpBudgetPulse";e.className="card kp-budget-pulse";const first=$("#budget article.card");first?.insertAdjacentElement("afterend",e)}
}
function renderLive(s){const host=$("#kpLiveCard");if(!host)return;const m=milestone(),idx=tripDay(),target=+(s.config?.dailyTarget||D.trip.dailyTarget||21),today=spentToday(s),left=target-today,mins=remainingRouteMinutes(s),phase=idx>=0?`Día ${idx+1} de 3`:(now()<new Date(D.trip.start)?"Antes de salir":"Viaje completado");host.innerHTML=`<div class="row start"><div><div class="smart-kicker">Centro de viaje · ${phase}</div><div class="kp-live-title">${m.emoji} ${m.time?fmtLeft(m.time-now()):"Cracovia guardada"}</div><div class="kp-live-sub">${m.time?`hasta ${m.label}`:"Misiones, gastos y recuerdos siguen disponibles"}</div></div><span class="pill gold"><span class="kp-status-dot"></span>en vivo</span></div><div class="kp-live-grid"><div class="kp-live-metric"><b>${m.time?m.time.toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"}):"✓"}</b><small>${m.label}</small></div><div class="kp-live-metric"><b>${left>=0?money(left):`−${money(Math.abs(left))}`}<span class="kp-unit-tight">€</span></b><small>${left>=0?"disponible hoy":"sobre objetivo hoy"}</small></div><div class="kp-live-metric"><b>${fmtMinutes(mins)}</b><small>ruta pendiente aprox.</small></div></div><div class="kp-live-actions"><button class="kp-live-action" data-go="base"><span>🏠</span>Base</button><button class="kp-live-action" data-go="mda"><span>🚌</span>MDA</button><button class="kp-live-action" data-go="rynek"><span>🏛️</span>Centro</button><button class="kp-live-action" id="kpShareLocation"><span>📍</span>Mi ubicación</button></div>`;
 host.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const p=poi(b.dataset.go==="base"?"w94":b.dataset.go);if(p)window.open(maps(p),"_blank")});$("#kpShareLocation").onclick=shareLocation}
async function shareLocation(){if(!navigator.geolocation){alert("Este navegador no permite obtener la ubicación.");return}const btn=$("#kpShareLocation");if(btn)btn.textContent="Buscando…";navigator.geolocation.getCurrentPosition(async pos=>{const url=`https://www.google.com/maps?q=${pos.coords.latitude},${pos.coords.longitude}`;const text=`Estoy aquí ahora: ${url}`;try{if(navigator.share)await navigator.share({title:"Mi ubicación · Kraków Pocket",text});else{await navigator.clipboard.writeText(text);alert("Ubicación copiada.")}}catch(e){if(e?.name!=="AbortError")prompt("Copia tu ubicación:",text)}finally{renderAll()}},()=>{alert("No he podido obtener la ubicación. Comprueba el permiso de Safari.");renderAll()},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
function planCandidates(s){const idx=tripDay(),districts=idx>=0?D.days[idx].districts:["old","wawel"];const available=D.pois.filter(p=>!['base','bus'].includes(p.category));const rank=(arr)=>arr.sort((a,b)=>(districts.includes(b.district)?1:0)-(districts.includes(a.district)?1:0));const free=rank(available.filter(p=>p.costLevel===0&&!['food','shop'].includes(p.category)))[0]||poi("planty");const rest=rank(available.filter(p=>p.category==="rest"))[0]||poi("planty");const food=rank(available.filter(p=>p.category==="food"))[0]||poi("tomasza");return[{kind:"Gratis",emoji:"✨",p:free,note:"sin tocar el presupuesto"},{kind:"Pausa",emoji:"🌿",p:rest,note:"para bajar el ritmo"},{kind:"Comer",emoji:"🍲",p:food,note:"opción sencilla"}]}
function renderPlanB(s){const host=$("#kpPlanB");if(!host)return;const items=planCandidates(s);host.innerHTML=`<div class="row"><div><div class="smart-kicker">Plan B inmediato</div><h2>Si no queréis pensar</h2></div><span class="pill blue">3 opciones</span></div><div class="kp-planb-grid">${items.map((x,i)=>`<button class="kp-planb" data-plan="${i}"><span class="emoji">${x.emoji}</span><b>${x.kind} · ${x.p.name}</b><small>${x.p.duration||20} min · ${x.note}</small></button>`).join("")}</div><div class="kp-planb-footer"><div class="kp-planb-note" id="kpPlanNote">Elegid una o dejad que Kraków Pocket decida.</div><button class="btn ghost small-btn" id="kpChooseForUs">🎲 Decide</button></div>`;host.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>window.open(maps(items[+b.dataset.plan].p),"_blank"));$("#kpChooseForUs").onclick=()=>{host.querySelectorAll(".kp-planb").forEach(x=>x.classList.remove("pick"));const i=Math.floor(Math.random()*items.length),chosen=host.querySelector(`[data-plan="${i}"]`);chosen?.classList.add("pick");$("#kpPlanNote").textContent=`Yo elegiría: ${items[i].p.name}. Tocad la tarjeta para ir.`}}
function renderBudget(s){const host=$("#kpBudgetPulse");if(!host)return;const target=+(s.config?.dailyTarget||D.trip.dailyTarget||21),whole=target*3,total=spentTotal(s),elapsed=elapsedDays(),avg=elapsed?total/elapsed:0,projection=elapsed?avg*3:0,remaining=whole-total,pct=clamp(Math.round(total/Math.max(whole,1)*100),0,100),good=remaining>=0;let headline,sub;if(!elapsed){headline=`${money(remaining)}€ de margen`;sub="La proyección empezará cuando comience el viaje."}else if(good){headline=`${money(remaining)}€ disponibles`;sub=projection<=whole?`Al ritmo actual acabaríais cerca de ${money(projection)}€.`:`El ritmo actual proyecta ${money(projection)}€; todavía podéis compensar.`}else{headline=`${money(Math.abs(remaining))}€ por encima`;sub=`El ritmo actual proyecta unos ${money(projection)}€ en tres días.`}host.innerHTML=`<div class="kp-budget-hero"><div><div class="smart-kicker">Pulso del presupuesto</div><h2>¿Cómo vais de verdad?</h2><div class="kp-budget-big ${good?"good":"warn"}">${headline}</div><p class="small" style="margin:7px 0 0">${sub}</p></div><div class="kp-budget-ring" style="--p:${pct}" data-label="${pct}%"></div></div><div class="kp-budget-stats"><div class="kp-budget-stat"><b>${money(total)}<span class="kp-unit-tight">€</span></b><small>gastado variable</small></div><div class="kp-budget-stat"><b>${elapsed?money(avg):"—"}<span class="kp-unit-tight">${elapsed?"€":""}</span></b><small>media por día</small></div><div class="kp-budget-stat"><b>${money(whole)}<span class="kp-unit-tight">€</span></b><small>objetivo 3 días</small></div></div>`}
let sig="";function renderAll(){ensure();const s=read(),nSig=JSON.stringify({v:s.visited,e:s.expenses,c:s.config,d:dateKey(now()),h:now().getHours(),m:Math.floor(now().getMinutes()/5)});if(nSig===sig)return;sig=nSig;renderLive(s);renderPlanB(s);renderBudget(s);const version=$("#settingsVersion");if(version)version.textContent="Kraków Pocket · v3.2"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",renderAll);else renderAll();window.addEventListener("storage",renderAll);setInterval(renderAll,5000);
})();
