(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const poi=id=>D.pois.find(p=>p.id===id),quest=id=>D.quests.find(q=>q.poi===id);
const maps=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p?.mapsQuery||`${p?.lat},${p?.lon}`)}`;
function effectiveDone(s,id){if(s.missionStatus?.[id])return !!s.missionStatus[id].done;return (s.visited||[]).includes(id)}
function routeIds(){const idx=D.days.findIndex(x=>x.date===dateKey(new Date()));if(idx===0)return["florian","rynek","maria","maius","wawel","dragon"];if(idx===1)return["szeroka","placnowy","bernatek","ghetto","planty"];if(idx===2)return D.pois.filter(p=>p.days?.includes(3)&&quest(p.id)).map(p=>p.id);return["florian","rynek","wawel","dragon"]}
function ensure(){if(!$("#kpToday")){const e=document.createElement("article");e.id="kpToday";e.className="card kp-today";const live=$("#kpLiveCard")||$("#recommendation");live?.insertAdjacentElement("afterend",e)}if(!$("#kpActionToast")){const e=document.createElement("div");e.id="kpActionToast";e.className="kp-action-toast";e.innerHTML='<span id="kpActionText"></span><button id="kpActionUndo">Deshacer</button>';document.body.appendChild(e)}}
let lastMissionAction=null,timer=null;
function showUndo(text,fn){lastMissionAction=fn;const box=$("#kpActionToast");if(!box)return;$("#kpActionText").textContent=text;box.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>box.classList.remove("show"),5000);$("#kpActionUndo").onclick=()=>{box.classList.remove("show");const f=lastMissionAction;lastMissionAction=null;f?.()}}
function triggerMission(id){const b=document.querySelector(`.q-done[data-poi="${CSS.escape(id)}"]`);if(!b)return false;b.click();return true}
function renderToday(){ensure();const host=$("#kpToday");if(!host)return;const s=read(),ids=routeIds(),items=ids.map(poi).filter(Boolean),pending=items.filter(p=>!effectiveDone(s,p.id)),done=items.length-pending.length,next=pending[0],pct=items.length?Math.round(done/items.length*100):0;const idx=D.days.findIndex(x=>x.date===dateKey(new Date())),dayLabel=idx>=0?`Día ${idx+1} · ${D.days[idx].title}`:"Ruta preparada";host.innerHTML=`<div class="kp-today-head"><div><div class="smart-kicker">Control de hoy</div><div class="kp-today-title">${dayLabel}</div><div class="kp-today-sub">${next?`${pending.length} paradas pendientes · siguiente: ${next.name}`:"Ruta principal completada. El resto del día es vuestro."}</div></div><span class="kp-version-pill">v3.4</span></div>${next?`<div class="kp-next"><div class="kp-next-main"><div class="kp-next-emoji">${next.emoji}</div><div><div class="kp-next-name">${next.name}</div><div class="kp-next-meta">${next.duration||20} min · ${next.cost}${quest(next.id)?` · misión +${quest(next.id).points} 🐉`:""}</div></div></div><div class="kp-next-actions"><button class="btn secondary" id="kpTodayMap">🗺️ Ver en mapa</button>${quest(next.id)?'<button class="btn" id="kpTodayDone">✓ Completar misión</button>':''}</div></div>`:`<div class="kp-next"><div class="kp-next-main"><div class="kp-next-emoji">✨</div><div><div class="kp-next-name">Ruta principal terminada</div><div class="kp-next-meta">Podéis repetir, descansar o elegir algo desde “Ahora”.</div></div></div></div>`}<div class="kp-mini-progress"><i style="width:${pct}%"></i></div><div class="kp-upcoming">${items.map(p=>`<button class="kp-upcoming-chip ${effectiveDone(s,p.id)?"done":""}" data-kp-poi="${p.id}">${p.emoji} ${p.name}</button>`).join("")}</div><div class="kp-editbar"><small>${done}/${items.length} de la ruta · ${pct}%</small><button class="kp-undo-expense" id="kpUndoLastExpense">↩ Deshacer último gasto</button></div>`;
if(next&&$("#kpTodayMap"))$("#kpTodayMap").onclick=()=>window.open(maps(next),"_blank");if(next&&quest(next.id)&&$("#kpTodayDone"))$("#kpTodayDone").onclick=()=>{if(triggerMission(next.id)){showUndo(`✓ ${quest(next.id).title}`,()=>triggerMission(next.id));setTimeout(renderToday,150)}};host.querySelectorAll("[data-kp-poi]").forEach(b=>b.onclick=()=>window.open(maps(poi(b.dataset.kpPoi)),"_blank"));const exp=activeExpenses(s).slice().sort((a,b)=>new Date(b.ts)-new Date(a.ts))[0],undo=$("#kpUndoLastExpense");if(undo){undo.disabled=!exp;undo.title=exp?`Último: ${Number(exp.amount||0).toFixed(2)} €`:"No hay gastos";undo.onclick=()=>{if(!exp)return;const del=document.querySelector(`.expense-delete[data-id="${CSS.escape(exp.id)}"]`);if(del){del.click();showUndo("Gasto eliminado",()=>restoreExpense(exp.id));setTimeout(renderToday,150)}}}}
function restoreExpense(id){const s=read(),x=(s.expenses||[]).find(e=>e.id===id);if(!x)return;x.deletedAt=null;x.updatedAt=new Date().toISOString();s.updatedAt=x.updatedAt;localStorage.setItem(STORAGE,JSON.stringify(s));window.dispatchEvent(new StorageEvent("storage",{key:STORAGE,newValue:JSON.stringify(s)}));location.reload()}
function installMissionUndo(){document.addEventListener("click",e=>{const b=e.target.closest?.(".q-done[data-poi]");if(!b)return;const id=b.dataset.poi,q=quest(id),before=effectiveDone(read(),id);setTimeout(()=>{const after=effectiveDone(read(),id);if(before!==after){showUndo(after?`✓ ${q?.title||"Misión"}`:`↩ ${q?.title||"Misión"} pendiente`,()=>triggerMission(id));renderToday()}},180)},false)}
function init(){ensure();installMissionUndo();renderToday();window.addEventListener("storage",renderToday);setInterval(renderToday,2500);const ver=$("#settingsVersion");if(ver)ver.textContent="Kraków Pocket · v3.4"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
