(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",$=s=>document.querySelector(s);
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const when=iso=>{if(!iso)return"";const d=new Date(iso),mins=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));if(mins<1)return"ahora";if(mins<60)return`hace ${mins} min`;const h=Math.floor(mins/60);if(h<24)return`hace ${h} h`;return d.toLocaleDateString("es-ES",{day:"numeric",month:"short"})};
function googleMapsScheme(raw){try{const u=new URL(raw,location.href);if(!/google\.(com|[a-z.]+)\/maps|maps\.google\./i.test(u.hostname+u.pathname))return null;const q=u.searchParams.get("query")||u.searchParams.get("q");if(q)return`comgooglemaps://?q=${encodeURIComponent(q)}`;const origin=u.searchParams.get("origin"),destination=u.searchParams.get("destination"),mode=u.searchParams.get("travelmode")||"walking";if(destination)return`comgooglemaps://?saddr=${encodeURIComponent(origin||"")}&daddr=${encodeURIComponent(destination)}&directionsmode=${encodeURIComponent(mode)}`}catch{}return null}
function openMapsSafe(raw){const url=String(raw||""),scheme=googleMapsScheme(url);if(!scheme){location.href=url;return null}let leftPage=false;const vis=()=>{if(document.hidden)leftPage=true};document.addEventListener("visibilitychange",vis);location.href=scheme;setTimeout(()=>{document.removeEventListener("visibilitychange",vis);if(!leftPage&&document.visibilityState==="visible")location.href=url},900);return null}
const nativeOpen=window.open.bind(window);window.open=function(url,target,features){const s=String(url||"");if(/google\.(com|[a-z.]+)\/maps|maps\.google\./i.test(s))return openMapsSafe(s);return nativeOpen(url,target,features)};
function ensureActivity(){if($("#kpSharedActivity"))return;const e=document.createElement("article");e.id="kpSharedActivity";e.className="card kp-shared-activity";const anchor=$("#kpToday")||$("#kpLiveCard")||$("#recommendation");anchor?.insertAdjacentElement("afterend",e)}
function events(s){const out=[];for(const [id,op] of Object.entries(s.missionStatus||{})){if(!op?.updatedAt)continue;const q=D.quests.find(x=>x.poi===id),p=D.pois.find(x=>x.id===id);out.push({ts:op.updatedAt,icon:op.done?"🧩":"↩️",title:op.done?`Misión completada: ${q?.title||p?.name||id}`:`Misión reabierta: ${q?.title||p?.name||id}`,by:"Compartido"})}for(const x of(s.expenses||[])){if(!x?.ts)continue;out.push({ts:x.updatedAt||x.ts,icon:x.deletedAt?"↩️":"💰",title:x.deletedAt?`Gasto eliminado${x.note?`: ${x.note}`:""}`:`${Number(x.amount||0).toFixed(2).replace(".",",")} €${x.note?` · ${x.note}`:""}`,by:x.by||"Ambos"})}for(const x of(s.memories||[])){if(!x?.ts)continue;out.push({ts:x.updatedAt||x.ts,icon:x.deletedAt?"↩️":"✨",title:x.deletedAt?"Recuerdo eliminado":x.title||"Recuerdo guardado",by:x.by||"Ambos"})}return out.sort((a,b)=>new Date(b.ts)-new Date(a.ts)).slice(0,4)}
function renderActivity(){const host=$("#kpSharedActivity");if(!host)return;const s=read(),items=events(s),updated=s.updatedAt;host.innerHTML=`<div class="kp-shared-head"><div><div class="smart-kicker">Ismael + Laura</div><h2>Actividad compartida</h2><p class="small">Últimos cambios de vuestra partida compartida.</p></div><span class="kp-shared-sync">☁️ ${navigator.onLine?"juntos":"offline"}</span></div>${items.length?`<div class="kp-activity-list">${items.map(x=>`<div class="kp-activity-item"><span class="kp-activity-icon">${x.icon}</span><div><b>${x.title}</b><small>${x.by} · ${when(x.ts)}</small></div></div>`).join("")}</div>`:`<div class="kp-activity-empty">Todavía no hay actividad compartida.</div>`}<div class="kp-shared-foot"><span>Último cambio: ${updated?when(updated):"sin cambios"}</span><button id="kpRefreshShared">↻ Actualizar</button></div>`;$("#kpRefreshShared").onclick=()=>location.reload()}
function addStyle(href,key){if(document.querySelector(`link[data-layer="${key}"]`)||document.querySelector(`link[href*="${key}.css"]`))return;const l=document.createElement("link");l.rel="stylesheet";l.href=href;l.dataset.layer=key;document.head.appendChild(l)}
function loadScript(src,key){return new Promise(resolve=>{if(document.querySelector(`script[data-layer="${key}"]`)||document.querySelector(`script[src*="${key}.js"]`)){resolve();return}const s=document.createElement("script");s.src=src;s.dataset.layer=key;s.onload=resolve;s.onerror=resolve;document.body.appendChild(s)})}
async function loadExperience(){addStyle("./v36.css?v=3606","v36");await loadScript("./v36.js?v=3606","v36");addStyle("./v37.css?v=3701","v37");await loadScript("./v37.js?v=3701","v37")}
function installReliableUpdater(){if(!('serviceWorker' in navigator))return;const banner=$("#updateBanner"),button=$("#applyUpdate");let reg=null,reloading=false;const hide=()=>{if(banner)banner.style.display="none"};const show=()=>{if(banner)banner.style.display="flex";if(button){button.disabled=false;button.textContent="Actualizar"}};const activate=()=>{if(!reg?.waiting)return;if(button){button.disabled=true;button.textContent="Actualizando…"}reg.waiting.postMessage({type:"SKIP_WAITING"})};if(button)button.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();activate()},true);navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloading)return;reloading=true;hide();setTimeout(()=>location.reload(),100)});navigator.serviceWorker.ready.then(r=>{reg=r;const inspect=()=>reg.waiting&&navigator.serviceWorker.controller?show():hide();inspect();reg.addEventListener("updatefound",()=>{const w=reg.installing;if(w)w.addEventListener("statechange",()=>{if(w.state==="installed")inspect()})});reg.update().catch(()=>{});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")reg.update().catch(()=>{})})}).catch(hide)}
function init(){document.documentElement.classList.add("kp-street");document.querySelector("#kpStreetBar")?.remove();ensureActivity();renderActivity();loadExperience();installReliableUpdater();window.addEventListener("storage",renderActivity);window.addEventListener("online",renderActivity);window.addEventListener("offline",renderActivity);setInterval(renderActivity,15000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();