(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",PLAYER="krakowPlayer",$=s=>document.querySelector(s);
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const totalSpent=s=>activeExpenses(s).reduce((a,x)=>a+(+x.amount||0),0);
const questDone=s=>D.quests.filter(q=>done(s,q.poi)).length;
const questScore=s=>D.quests.filter(q=>done(s,q.poi)).reduce((a,q)=>a+q.points,0);
const clickPanel=id=>{const b=document.querySelector(`.tab[data-panel="${id}"]`);if(b)b.click()};
function phase(){const title=$("#heroTitle")?.textContent?.trim()||"La aventura os espera";const label=$("#phaseLabel")?.textContent?.trim()||"Kraków Pocket";return{title,label}}
function gameMessage(s){const n=questDone(s),p=localStorage.getItem(PLAYER)||"Ismael",ph=phase();if(n>=D.quests.length)return[`🐉 Dragón de Wawel`,`¡${p}! Habéis reunido todas las escamas. Cracovia ya es territorio de aventureros.`];if(n>=9)return["🐉 Dragón de Wawel",`Os quedan muy pocas escamas. Wawel empieza a considerar seriamente vuestra candidatura a leyenda.`];if(n>=6)return["🧙 Guardián del viaje",`Ya habéis superado la mitad. No corráis: las mejores misiones siguen apareciendo cuando miráis alrededor.`];if(/bus|zachodnia/i.test(ph.title))return["🚌 Maestro de estación","Primera misión del día: llegar al bus con margen. Los héroes también miran el reloj."];
if(/prepar/i.test(ph.label))return["🎒 Posadero","Hoy toca preparar inventario: agua, batería, desayuno y ganas de caminar. Mañana empieza el mapa de verdad."];
return["🐉 Dragón de Wawel",n?`Lleváis ${n} de ${D.quests.length} misiones. Hay otra escama escondida ahí fuera.`:"Toda aventura empieza con una puerta. Buscad el primer ! y empezad a mirar Cracovia como jugadores."]}
function ensureHub(){const home=$("#home");if(!home||$("#kpGameHub"))return;const hub=document.createElement("section");hub.id="kpGameHub";hub.className="kp-game-hub";home.insertBefore(hub,home.firstChild);}
function renderHub(){ensureHub();const host=$("#kpGameHub");if(!host)return;const s=read(),score=questScore(s),missions=questDone(s),spent=totalSpent(s),msg=gameMessage(s),player=localStorage.getItem(PLAYER)||"Ismael";const pending=Math.max(0,D.quests.length-missions);host.innerHTML=`<div class="kp-game-frame"><div class="kp-game-status"><div class="kp-game-status-left"><div><div class="kp-game-day">${phase().label}</div><div class="kp-game-clock">Kraków Pocket</div></div></div><div class="kp-game-status-right"><span class="kp-game-chip">🐉 ${score}</span><span class="kp-game-chip">💰 ${spent.toFixed(2).replace('.',',')} €</span></div></div><div class="kp-village"><span class="kp-cloud c1">☁️</span><span class="kp-cloud c2">☁️</span><span class="kp-sun">☀️</span><div class="kp-rpg-river"></div><div class="kp-rpg-path p1"></div><div class="kp-rpg-path p2"></div><span class="kp-game-tree t1">🌳</span><span class="kp-game-tree t2">🌲</span><span class="kp-game-tree t3">🌳</span><span class="kp-game-tree t4">🌲</span><button class="kp-place base" data-go="home"><span class="kp-building">🏠</span><small>Base</small></button><button class="kp-place quests" data-go="quests"><span class="kp-building">📜</span>${pending?'<span class="kp-alert">!</span>':''}<small>Misiones</small></button><button class="kp-place map" data-go="mapPanel"><span class="kp-building">🗺️</span><small>Mapa</small></button><button class="kp-place diary" data-go="diary"><span class="kp-building">📖</span><small>Diario</small></button><button class="kp-place budget" data-go="budget"><span class="kp-building">💰</span><small>Bolsa</small></button><div class="kp-game-couple"><span>${player==="Laura"?"👩🏻":"🧑🏻"}</span><span>${player==="Laura"?"🧑🏻":"👩🏻"}</span></div></div><div class="kp-game-dialog"><div class="kp-game-avatar">${msg[0].startsWith("🐉")?"🐉":msg[0].startsWith("🚌")?"🚌":msg[0].startsWith("🎒")?"🎒":"🧙"}</div><div><div class="kp-game-speaker">${msg[0]}</div><div class="kp-game-message">${msg[1]} <span class="kp-game-next">▼</span></div><div class="kp-game-hint">Toca un edificio para entrar · ${missions}/${D.quests.length} misiones completadas</div></div></div></div>`;host.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>clickPanel(b.dataset.go));}
function banner(panel,icon,title,sub){const p=$(panel);if(!p||p.querySelector(":scope > .kp-panel-banner"))return;const e=document.createElement("div");e.className="kp-panel-banner";e.innerHTML=`<span>${icon}</span><div><b>${title}</b><small>${sub}</small></div>`;p.insertBefore(e,p.firstChild)}
function decoratePanels(){banner("#mapPanel","🗺️","Mapa de la comarca","El mapa real para moveros; la aventura sigue fuera de la pantalla.");banner("#quests","📜","Tablón de misiones","Elegid una pista, salid a buscarla y volved con otra escama.");banner("#diary","📖","Crónica de viaje","Historias descubiertas y recuerdos que solo tienen sentido para vosotros.");banner("#budget","💰","Bolsa de monedas","Control real en euros, presentado como el inventario económico de la aventura.")}
function renameNav(){const labels={home:["🐉","Aldea"],mapPanel:["🗺️","Mapa"],quests:["📜","Misiones"],diary:["📖","Crónica"],budget:["💰","Bolsa"]};for(const [id,[ico,txt]] of Object.entries(labels)){const b=document.querySelector(`.tab[data-panel="${id}"]`);if(!b)continue;b.innerHTML=`<b>${ico}</b>${txt}`}}
function installRpg(){document.documentElement.classList.add("kp-rpg","kp-street");ensureHub();decoratePanels();renameNav();renderHub();window.addEventListener("storage",renderHub);window.addEventListener("online",renderHub);setInterval(renderHub,3000);const ver=$("#settingsVersion");if(ver)ver.textContent="Kraków Pocket · v3.7 · RPG Edition"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",installRpg);else installRpg();
})();
