(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",PLAYER="krakowPlayer",$=s=>document.querySelector(s);
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const totalSpent=s=>activeExpenses(s).reduce((a,x)=>a+(+x.amount||0),0);
const questDone=s=>D.quests.filter(q=>done(s,q.poi)).length;
const questScore=s=>D.quests.filter(q=>done(s,q.poi)).reduce((a,q)=>a+q.points,0);
const clickPanel=id=>document.querySelector(`.tab[data-panel="${id}"]`)?.click();
function phase(){return{title:$("#heroTitle")?.textContent?.trim()||"La aventura os espera",label:$("#phaseLabel")?.textContent?.trim()||"Kraków Pocket"}}
function gameMessage(s){const n=questDone(s),p=localStorage.getItem(PLAYER)||"Ismael",ph=phase();if(n>=D.quests.length)return["🐉 Dragón de Wawel",`¡${p}! Habéis reunido todas las escamas. Cracovia ya es territorio de aventureros.`];if(n>=9)return["🐉 Dragón de Wawel","Os quedan muy pocas escamas. Wawel empieza a considerar seriamente vuestra candidatura a leyenda."];if(n>=6)return["🧙 Guardián del viaje","Ya habéis superado la mitad. No corráis: las mejores misiones aparecen cuando miráis alrededor."];if(/bus|zachodnia/i.test(ph.title))return["🚌 Maestro de estación","Primera misión del día: llegar al bus con margen. Los héroes también miran el reloj."];if(/prepar/i.test(ph.label))return["🎒 Posadero","Hoy toca preparar inventario: agua, batería, desayuno y ganas de caminar."];return["🐉 Dragón de Wawel",n?`Lleváis ${n} de ${D.quests.length} misiones. Hay otra escama escondida ahí fuera.`:"Toda aventura empieza con una puerta. Buscad el primer ! y empezad a mirar Cracovia como jugadores."]}
function ensureHub(){const home=$("#home");if(!home||$("#kpGameHub"))return;const hub=document.createElement("section");hub.id="kpGameHub";hub.className="kp-game-hub";home.insertBefore(hub,home.firstChild)}
let lastSignature="";
function signature(){const s=read(),ph=phase();return JSON.stringify([questDone(s),questScore(s),Math.round(totalSpent(s)*100),localStorage.getItem(PLAYER)||"Ismael",ph.title,ph.label])}
function renderHub(force=false){ensureHub();const host=$("#kpGameHub");if(!host)return;const sig=signature();if(!force&&sig===lastSignature)return;lastSignature=sig;const s=read(),score=questScore(s),missions=questDone(s),spent=totalSpent(s),msg=gameMessage(s),player=localStorage.getItem(PLAYER)||"Ismael",pending=Math.max(0,D.quests.length-missions);host.innerHTML=`<div class="kp-game-frame"><div class="kp-game-status"><div class="kp-game-status-left"><div><div class="kp-game-day">${phase().label}</div><div class="kp-game-clock">Kraków Pocket</div></div></div><div class="kp-game-status-right"><span class="kp-game-chip">🐉 ${score}</span><span class="kp-game-chip">💰 ${spent.toFixed(2).replace('.',',')} €</span></div></div><div class="kp-village"><span class="kp-cloud c1">☁️</span><span class="kp-cloud c2">☁️</span><span class="kp-sun">☀️</span><div class="kp-rpg-river"></div><div class="kp-rpg-path p1"></div><div class="kp-rpg-path p2"></div><span class="kp-game-tree t1">🌳</span><span class="kp-game-tree t2">🌲</span><span class="kp-game-tree t3">🌳</span><span class="kp-game-tree t4">🌲</span><button class="kp-place base" data-go="home"><span class="kp-building">🏠</span><small>Base</small></button><button class="kp-place quests" data-go="quests"><span class="kp-building">📜</span>${pending?'<span class="kp-alert">!</span>':''}<small>Misiones</small></button><button class="kp-place map" data-go="mapPanel"><span class="kp-building">🗺️</span><small>Mapa</small></button><button class="kp-place diary" data-go="diary"><span class="kp-building">📖</span><small>Crónica</small></button><button class="kp-place budget" data-go="budget"><span class="kp-building">💰</span><small>Bolsa</small></button><div class="kp-game-couple"><span>${player==="Laura"?"👩🏻":"🧑🏻"}</span><span>${player==="Laura"?"🧑🏻":"👩🏻"}</span></div></div><div class="kp-game-dialog"><div class="kp-game-avatar">${msg[0].startsWith("🐉")?"🐉":msg[0].startsWith("🚌")?"🚌":msg[0].startsWith("🎒")?"🎒":"🧙"}</div><div><div class="kp-game-speaker">${msg[0]}</div><div class="kp-game-message">${msg[1]} <span class="kp-game-next">▼</span></div><div class="kp-game-hint">Toca un edificio para entrar · ${missions}/${D.quests.length} misiones completadas</div></div></div></div>`;host.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>clickPanel(b.dataset.go))}
function banner(panel,icon,title,sub){const p=$(panel);if(!p||p.querySelector(":scope > .kp-panel-banner"))return;const e=document.createElement("div");e.className="kp-panel-banner";e.innerHTML=`<span>${icon}</span><div><b>${title}</b><small>${sub}</small></div>`;p.insertBefore(e,p.firstChild)}
function decoratePanels(){banner("#mapPanel","🗺️","Mapa de la comarca","Mapa real para moveros sin perder el espíritu de la aventura.");banner("#quests","📜","Tablón de misiones","Elegid una pista, salid a buscarla y volved con otra escama.");banner("#diary","📖","Crónica de viaje","Historias y recuerdos que vais desbloqueando juntos.");banner("#budget","💰","Bolsa de monedas","Euros reales, presentados como el inventario económico del viaje.")}
function renameNav(){const labels={home:["🐉","Aldea"],mapPanel:["🗺️","Mapa"],quests:["📜","Misiones"],diary:["📖","Crónica"],budget:["💰","Bolsa"]};for(const [id,[ico,txt]] of Object.entries(labels)){const b=document.querySelector(`.tab[data-panel="${id}"]`);if(b)b.innerHTML=`<b>${ico}</b>${txt}`}}
function loadV38(){if(!document.querySelector('link[href*="v38.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="./v38.css?v=3801";document.head.appendChild(l)}if(!document.querySelector('script[src*="v38.js"]')){const s=document.createElement("script");s.src="./v38.js?v=3801";document.body.appendChild(s)}}
function installRpg(){document.documentElement.classList.add("kp-rpg","kp-street");ensureHub();decoratePanels();renameNav();renderHub(true);loadV38();window.addEventListener("storage",()=>renderHub(true));window.addEventListener("online",()=>renderHub(true));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")renderHub(true)});$("#playerSelect")?.addEventListener("change",()=>setTimeout(()=>renderHub(true),0));const ver=$("#settingsVersion");if(ver)ver.textContent="Kraków Pocket · v3.9 · RPG estable"}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",installRpg);else installRpg();
})();