(() => {
"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function removeLegacyFloat(){const bar=$("#kpStreetBar");if(bar)bar.remove()}
function decorateHome(){const rec=$("#recommendation");if(rec){rec.classList.add("kp-rpg-board");const k=rec.querySelector(".smart-kicker");if(k&&k.dataset.rpgDone!=="1"){k.textContent="📜 Consejo del gremio";k.dataset.rpgDone="1"}}const today=$("#kpToday");if(today){today.classList.add("kp-rpg-route");const pill=today.querySelector(".kp-version-pill");if(pill)pill.textContent="RUTA"}const live=$("#kpLiveCard");if(live)live.classList.add("kp-rpg-travel-center");const quick=$("#home > .quick-grid");if(quick){quick.classList.add("kp-rpg-actions");const labels=[["#quickMap","🗺️ Explorar","Abrir el mapa real"],["#quickExpense","🪙 Registrar gasto","Guardar en la bolsa"],["#quickMemory","📖 Guardar recuerdo","Añadir a la crónica"],["#quickRest","🌿 Descansar","Buscar algo tranquilo"]];labels.forEach(([sel,title,sub])=>{const b=$(sel);if(!b||b.dataset.rpgDone==="1")return;const strong=b.querySelector("strong"),span=b.querySelector("span");if(strong)strong.textContent=title;if(span)span.textContent=sub;b.dataset.rpgDone="1"})}}
function decoratePanels(){const map=$("#mapPanel");if(map)map.classList.add("kp-rpg-panel-map");const quests=$("#quests");if(quests)quests.classList.add("kp-rpg-panel-quests");const diary=$("#diary");if(diary)diary.classList.add("kp-rpg-panel-diary");const budget=$("#budget");if(budget)budget.classList.add("kp-rpg-panel-budget");const qtop=$("#quests > .card");if(qtop){const k=qtop.querySelector(".smart-kicker");if(k)k.textContent="🐉 Libro de encargos"}const budgetTop=$("#budget > .card");if(budgetTop){const k=budgetTop.querySelector(".smart-kicker");if(k)k.textContent="🪙 Bolsa compartida"}const storyIntro=$("#diary-stories > .card .smart-kicker");if(storyIntro)storyIntro.textContent="📜 Crónica desbloqueable"}
function addVillageShortcuts(){const hub=$("#kpGameHub .kp-village");if(!hub||hub.querySelector(".kp-village-shortcuts"))return false;const wrap=document.createElement("div");wrap.className="kp-village-shortcuts";wrap.innerHTML='<button id="kpVillageBase">🏠<span>Base</span></button><button id="kpVillageMda">🚌<span>MDA</span></button>';hub.appendChild(wrap);$("#kpVillageBase").onclick=()=>$("#homeMapBtn")?.click();$("#kpVillageMda").onclick=()=>$("#zachodniaBtn")?.click();return true}
function mobileAudit(){document.documentElement.classList.add("kp-rpg-v38");$$('button,input,select,textarea').forEach(el=>el.classList.add('kp-touch-safe'))}
function updateVersion(){const v=$("#settingsVersion");if(v)v.textContent="Kraków Pocket · v3.9 · RPG estable"}
function run(){removeLegacyFloat();decorateHome();decoratePanels();mobileAudit();updateVersion();if(!addVillageShortcuts()){let tries=0;const id=setInterval(()=>{tries++;if(addVillageShortcuts()||tries>=12)clearInterval(id)},250)}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",run,{once:true});else run();
window.addEventListener("storage",()=>{decorateHome();decoratePanels()});
})();