(() => {
"use strict";
const D=window.KP_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE="krakowPocketCoop";
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
const missions=s=>D?.quests?.filter(q=>done(s,q.poi)).length||0;
const score=s=>D?.quests?.filter(q=>done(s,q.poi)).reduce((a,q)=>a+(+q.points||0),0)||0;
const activeExpenses=s=>(s.expenses||[]).filter(x=>x&&!x.deletedAt);
const spent=s=>activeExpenses(s).reduce((a,x)=>a+(+x.amount||0),0);
const panelNames={home:["Aldea","Centro de la aventura"],mapPanel:["Mapa del mundo","Cracovia"],quests:["Tablón de encargos","Escamas de Wawel"],diary:["Crónica","Historias y recuerdos"],budget:["Bolsa","Inventario compartido"]};
function tripDay(){const now=new Date(),dates=(D?.days||[]).map(x=>x.date);const key=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;const i=dates.indexOf(key);if(i>=0)return `Día ${i+1}`;if(dates.length&&key<dates[0])return"Antes";if(dates.length&&key>dates[dates.length-1])return"Final";return"Viaje"}
function ensureHud(){if($("#kpMasterHud"))return;const hud=document.createElement("div");hud.id="kpMasterHud";hud.innerHTML='<div class="kp-master-top"><div class="kp-master-day"><b id="kpHudDay">Viaje</b><span id="kpHudTime">--:--</span></div><div class="kp-master-place"><b id="kpHudPlace">Aldea</b><span id="kpHudSub">Centro de la aventura</span></div><button class="kp-master-settings" id="kpHudSettings" aria-label="Menú de partida">⚙️</button></div><div class="kp-master-stats"><div class="kp-master-stat"><b id="kpHudScore">🐉 0</b><small>escamas</small></div><div class="kp-master-stat"><b id="kpHudMissions">0/12</b><small>encargos</small></div><div class="kp-master-stat"><b id="kpHudMoney">0,00 €</b><small>gastado</small></div><div class="kp-master-stat sync"><b id="kpHudSync">☁️ ...</b><small>partida</small></div></div>';const app=$(".app");document.body.insertBefore(hud,app||document.body.firstChild);$("#kpHudSettings").onclick=()=>$("#openSettings")?.click()}
function currentPanel(){return $(".tab.active[data-panel]")?.dataset.panel||"home"}
function updateHud(){ensureHud();const s=read(),p=currentPanel(),info=panelNames[p]||panelNames.home,now=new Date();const day=$("#kpHudDay"),time=$("#kpHudTime"),place=$("#kpHudPlace"),sub=$("#kpHudSub"),sc=$("#kpHudScore"),mi=$("#kpHudMissions"),money=$("#kpHudMoney"),sy=$("#kpHudSync");if(day)day.textContent=tripDay();if(time)time.textContent=now.toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"});if(place)place.textContent=info[0];if(sub)sub.textContent=info[1];if(sc)sc.textContent=`🐉 ${score(s)}`;if(mi)mi.textContent=`${missions(s)}/${D?.quests?.length||12}`;if(money)money.textContent=`${spent(s).toFixed(2).replace('.',',')} €`;const sync=$("#heroSync")?.textContent?.trim()||"☁️ partida";if(sy)sy.textContent=sync.replace(/conectando/i,"...")}
function ensureTitlebars(){for(const [id,[title,sub]] of Object.entries(panelNames)){const p=$(`#${id}`);if(!p||p.querySelector(":scope > .panel-titlebar"))continue;const bar=document.createElement("div");bar.className="panel-titlebar";bar.innerHTML=`<span>${title}</span><span>${sub}</span>`;p.insertBefore(bar,p.firstChild)}}
function integrateLabels(){const labels={home:["🐉","Aldea"],mapPanel:["🗺️","Mapa"],quests:["📜","Encargos"],diary:["📖","Crónica"],budget:["🎒","Bolsa"]};for(const [id,[ico,txt]] of Object.entries(labels)){const t=$(`.tab[data-panel="${id}"]`);if(!t)continue;const b=t.querySelector("b");if(b)b.textContent=ico;for(const n of [...t.childNodes])if(n.nodeType===3&&n.textContent.trim())n.textContent=txt}const st=$("#settingsSheet .sheet-head strong");if(st)st.textContent="⚙️ Menú de partida";const ss=$("#settingsSheet .sheet-head .small");if(ss)ss.textContent="Jugador, objetivo y sincronización";const ver=$("#settingsVersion");if(ver)ver.textContent="Kraków Pocket · partida compartida"}
function bindTabs(){$$(".tab[data-panel]").forEach(t=>{if(t.dataset.v44Bound)return;t.dataset.v44Bound="1";t.addEventListener("click",()=>setTimeout(updateHud,0))})}
function loadV45(){if(!document.querySelector('link[href*="v45.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="./v45.css?v=4500";document.head.appendChild(l)}if(!document.querySelector('script[src*="v45.js"]')){const s=document.createElement("script");s.src="./v45.js?v=4500";document.body.appendChild(s)}}
function gameify(){document.documentElement.classList.add("kp-rpg-v44");ensureHud();ensureTitlebars();integrateLabels();bindTabs();updateHud();loadV45()}
function run(){gameify();setTimeout(gameify,250);setTimeout(gameify,900)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",run,{once:true});else run();
window.addEventListener("storage",updateHud);window.addEventListener("online",updateHud);window.addEventListener("offline",updateHud);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){updateHud();gameify()}});setInterval(updateHud,30000);
})();
