(()=>{"use strict";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LONG=16;
function markLabels(){for(const n of $$('[data-pixel-poi]')){const label=n.querySelector('small');if(!label)continue;n.classList.toggle('kp51-long',(label.textContent||'').trim().length>LONG);label.removeAttribute('style')}}
function hideLegacy(){for(const el of $$('.kp45-compat,.kp-rpg-statusline,.kp-rpg-hud,.kp-panel-banner'))el.setAttribute('aria-hidden','true')}
function auditOverflow(){const targets=['#kpMasterHud','.kp45-logo','.kp45-resource','#kp45QuestStrip','.kp45-questcopy','.kp-world-top','.kp-world-title','.card','.smart-card','.bottom','.tab','.update-banner'];for(const sel of targets){for(const el of $$(sel)){el.classList.remove('kp51-tight','kp51-overflow-fix');if(el.scrollWidth>el.clientWidth+3){el.classList.add('kp51-overflow-fix');if(el.matches('.kp45-logo,.kp45-resource,.kp-world-title,.tab'))el.classList.add('kp51-tight')}}}}
function cleanInlineRegressions(){for(const el of $$('.kp-world-node small')){el.style.removeProperty('width');el.style.removeProperty('max-width');el.style.removeProperty('font-size')}for(const el of $$('.kp-world-node')){el.style.removeProperty('width');el.style.removeProperty('min-width')}}
function enhanceSemantics(){const world=$('#kpQuestWorld .kp-world-map');if(world&&!world.getAttribute('role')){world.setAttribute('role','group');world.setAttribute('aria-label','Mapa ilustrado de encargos de Cracovia')}for(const n of $$('[data-pixel-poi]')){const label=n.querySelector('small')?.textContent?.trim();if(label&&!n.getAttribute('aria-label'))n.setAttribute('aria-label',label)}}
function install(){document.documentElement.classList.add('kp-rpg-v51');hideLegacy();cleanInlineRegressions();markLabels();enhanceSemantics();requestAnimationFrame(auditOverflow);const ver=$('#settingsVersion');if(ver)ver.textContent='Kraków Pocket · v5.1 auditado'}
function schedule(){install();setTimeout(install,180);setTimeout(auditOverflow,500)}
function bind(){schedule();for(const t of $$('.tab[data-panel]')){if(t.dataset.v51Bound)return;t.dataset.v51Bound='1';t.addEventListener('click',()=>setTimeout(schedule,40))}window.addEventListener('resize',()=>requestAnimationFrame(auditOverflow),{passive:true});const world=$('#kpQuestWorld');if(world&&!world.dataset.v51Observed){world.dataset.v51Observed='1';let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;markLabels();auditOverflow()})}).observe(world,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule()});window.addEventListener('storage',()=>setTimeout(schedule,0));})();