(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",PLAYER="krakowPlayer",ASSET="./assets/game-art.svg",CHARACTER_ASSET="./assets/characters.svg";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
const iconId={home:"nav-home",mapPanel:"nav-map",quests:"nav-quests",diary:"nav-diary",budget:"nav-budget"};
const CHAR={ismaelPortrait:"char-ismael-v4-portrait",lauraPortrait:"char-laura-v4-portrait",ismaelWorld:"char-ismael-v4-world",lauraWorld:"char-laura-v4-world",dragon:"npc-dragon-v4",guardian:"npc-guardian-v1"};
let frame=0,navRO=null,started=false;
const art=(id,cls="kp-asset-svg")=>`<svg class="${cls}" viewBox="0 0 180 180" aria-hidden="true" focusable="false"><use href="${ASSET}#${id}"></use></svg>`;
const characterArt=(id,cls="kp-character-asset")=>`<svg class="${cls}" data-kp-character="${id}" viewBox="0 0 180 180" aria-hidden="true" focusable="false"><use href="${CHARACTER_ASSET}#${id}"></use></svg>`;
const navArt=id=>`<svg class="kp-asset-svg" viewBox="0 0 120 120" aria-hidden="true" focusable="false"><use href="${ASSET}#${iconId[id]||"nav-home"}"></use></svg>`;
function dayPart(){const h=new Date().getHours(),html=document.documentElement;html.classList.remove("kp-morning","kp-afternoon","kp-evening","kp-night");html.classList.add(h<11?"kp-morning":h<18?"kp-afternoon":h<22?"kp-evening":"kp-night")}
function decorateHub(){const world=$("#kpGameHub .kp-hub-world");if(!world)return;if(!world.querySelector(".kp-hub-vfx")){const layer=document.createElement("div");layer.className="kp-vfx-layer kp-hub-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<span class="kp-vfx-sun"></span><span class="kp-vfx-cloud c1"></span><span class="kp-vfx-cloud c2"></span><span class="kp-vfx-bird"></span><span class="kp-vfx-bird b2"></span><span class="kp-vfx-grass"></span><i class="kp-pollen p1"></i><i class="kp-pollen p2"></i><i class="kp-pollen p3"></i><i class="kp-leaf-fall l1"></i><i class="kp-leaf-fall l2"></i>';world.appendChild(layer)}world.classList.add("kp-illustrated-scene")}
function decorateQuest(){const map=$("#kpQuestWorld .kp-world-map");if(!map)return;if(!map.querySelector(".kp-world-vfx")){const layer=document.createElement("div");layer.className="kp-vfx-layer kp-world-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<i class="kp-world-sparkle s1"></i><i class="kp-world-sparkle s2"></i><i class="kp-world-sparkle s3"></i><i class="kp-world-sparkle s4"></i><i class="kp-river-glint g1"></i><i class="kp-river-glint g2"></i>';map.appendChild(layer)}map.classList.add("kp-illustrated-map")}
function setCharacter(host,id,label,cls="kp-character-asset"){if(!host)return;if(host.dataset.asset===id&&host.querySelector(`svg[data-kp-character="${id}"],svg[data-kp-inline="${id}"]`))return;host.dataset.asset=id;if(label)host.setAttribute("aria-label",label);if(document.documentElement.classList.contains("kp-inline-art-ready")){host.querySelectorAll('svg:not([data-kp-inline])').forEach(svg=>svg.remove());return}host.innerHTML=characterArt(id,cls)}
function speakerCharacter(){const text=$("#kpGameHub .kp-hub-speaker")?.textContent||"";return/Guardián/i.test(text)?{id:CHAR.guardian,label:"Guardián del viaje"}:{id:CHAR.dragon,label:"Dragón de Wawel"}}
function upgradeCharacters(){const player=localStorage.getItem(PLAYER)==="Laura"?"Laura":"Ismael",portraitId=player==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait;setCharacter($("#kpGameHud .kp-game-portrait"),portraitId,player);const couple=$$("#kpGameHub .kp-couple-art");setCharacter(couple[0],CHAR.ismaelWorld,"Ismael");setCharacter(couple[1],CHAR.lauraWorld,"Laura");const npc=speakerCharacter();setCharacter($("#kpGameHub .kp-hub-avatar"),npc.id,npc.label,"kp-npc-asset")}
function upgradeLandmarks(){$$('#kpQuestWorld .kp-world-node[data-pixel-poi]').forEach(node=>{const id=node.dataset.pixelPoi,target=node.querySelector(".kp-landmark-art");if(!target||target.dataset.asset===id)return;target.innerHTML=art(`landmark-${id}`,"kp-landmark-svg");target.dataset.asset=id})}
function upgradeNavigation(){$$('.tab[data-panel]').forEach(t=>{const id=t.dataset.panel,b=t.querySelector("b");if(!b||b.dataset.asset===id)return;b.innerHTML=`<span class="kp-nav-art">${navArt(id)}</span>`;b.dataset.asset=id});$$('#kpGameHub .kp-hub-place[data-go]').forEach(b=>{const id=b.dataset.go,target=b.querySelector(".building");if(!target||target.dataset.asset===id)return;target.innerHTML=navArt(id);target.dataset.asset=id})}
function markNextMission(){const s=read(),next=D.quests.find(q=>!done(s,q.poi)),nextId=next?.poi||"";$$('#kpQuestWorld .kp-world-node').forEach(node=>{const active=node.dataset.pixelPoi===nextId,was=node.classList.contains("kp-next-mission");if(active&&!was)node.classList.add("kp-next-mission");if(!active&&was)node.classList.remove("kp-next-mission");if(active)node.setAttribute("aria-current","step");else node.removeAttribute("aria-current");const label=node.querySelector("small")?.textContent?.trim();if(label&&node.title!==label)node.title=label;const arrow=node.querySelector(".kp-next-arrow");if(active&&!arrow){const a=document.createElement("span");a.className="kp-next-arrow";a.textContent="⌄";a.setAttribute("aria-hidden","true");node.appendChild(a)}else if(!active&&arrow)arrow.remove()})}
function auditNav(){$$('.tab[data-panel]').forEach(t=>{if(t.classList.contains("active"))t.setAttribute("aria-current","page");else t.removeAttribute("aria-current")})}
function auditOverflow(){const containers=["#kpGameHud","#kpGameObjective",".kp-world-top",".kp-hub-dialog",".card",".smart-card",".sheet-head",".kp-route-step",".metric"],texts=[".kp-game-logo strong",".tab",".kp-world-node small",".metric .value"];let hits=0;for(const sel of [...containers,...texts])for(const el of $$(sel)){el.classList.remove("kp-visual-overflow","kp-visual-tight");if(el.scrollWidth>el.clientWidth+3){hits++;el.classList.add("kp-visual-overflow");if(texts.some(t=>el.matches(t)))el.classList.add("kp-visual-tight")}}return hits}
function auditNodeCollisions(){const nodes=$$('#kpQuestWorld .kp-world-node');nodes.forEach(n=>{n.classList.remove("kp-crowded","kp-label-left","kp-label-right","kp-label-up");const left=parseFloat(n.style.left||"50"),top=parseFloat(n.style.top||"50");if(left<17)n.classList.add("kp-label-right");else if(left>83)n.classList.add("kp-label-left");if(top>87)n.classList.add("kp-label-up")});let hits=0;for(let i=0;i<nodes.length;i++){const la=nodes[i].querySelector("small");if(!la)continue;const a=la.getBoundingClientRect();for(let j=i+1;j<nodes.length;j++){const lb=nodes[j].querySelector("small");if(!lb)continue;const b=lb.getBoundingClientRect(),pad=3,overlap=!(a.right+pad<b.left||b.right+pad<a.left||a.bottom+pad<b.top||b.bottom+pad<a.top);if(!overlap)continue;hits++;nodes[i].classList.add("kp-crowded");nodes[j].classList.add("kp-crowded");const ai=parseFloat(nodes[i].style.left||"50"),bj=parseFloat(nodes[j].style.left||"50");if(ai<=bj){nodes[i].classList.add("kp-label-left");nodes[j].classList.add("kp-label-right")}else{nodes[i].classList.add("kp-label-right");nodes[j].classList.add("kp-label-left")}}}return hits}
function auditTouchTargets(){let fixed=0;for(const el of $$('button,.tab,input,select,textarea')){el.classList.remove("kp-touch-fix");const r=el.getBoundingClientRect();if(r.width>0&&r.height>0&&(r.height<42||r.width<36)){el.classList.add("kp-touch-fix");fixed++}}return fixed}
function auditDialogs(){const outer=$("#storyDialog"),inner=outer?.querySelector(".dialog-body");if(!outer||!inner)return false;const ob=parseFloat(getComputedStyle(outer).borderTopWidth)||0,ib=parseFloat(getComputedStyle(inner).borderTopWidth)||0;return ob>0&&ib>0}
function characterId(host){if(!host)return"";const svg=host.querySelector("svg");return svg?.dataset.kpInline||svg?.dataset.kpCharacter||host.dataset.asset||""}
function rectanglesOverlap(a,b,pad=4){return!!a&&!!b&&!(a.right+pad<b.left||b.right+pad<a.left||a.bottom+pad<b.top||b.bottom+pad<a.top)}
function auditCharacters(){const selected=localStorage.getItem(PLAYER)==="Laura"?"Laura":"Ismael",expectedPortrait=selected==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait,portraitHost=$("#kpGameHud .kp-game-portrait"),couple=$$("#kpGameHub .kp-couple-art"),npcHost=$("#kpGameHub .kp-hub-avatar"),npcExpected=speakerCharacter().id;const portrait=portraitHost?.querySelector("svg"),blankPortrait=!portrait||portrait.getBoundingClientRect().width<20||portrait.getBoundingClientRect().height<20,missingCouple=couple.length<2||couple.some(el=>{const s=el.querySelector("svg");return!s||s.getBoundingClientRect().width<20||s.getBoundingClientRect().height<20}),identityMismatch=characterId(portraitHost)!==expectedPortrait||characterId(couple[0])!==CHAR.ismaelWorld||characterId(couple[1])!==CHAR.lauraWorld||characterId(npcHost)!==npcExpected;const coupleRect=$("#kpGameHub .kp-hub-couple")?.getBoundingClientRect(),labels=$$("#kpGameHub .kp-hub-place small"),collision=labels.some(l=>rectanglesOverlap(coupleRect,l.getBoundingClientRect(),2));document.documentElement.classList.toggle("kp-character-warning",blankPortrait||missingCouple||identityMismatch);document.documentElement.classList.toggle("kp-character-collision",collision);return{blankPortrait,missingCouple,identityMismatch,collision,selected,portrait:characterId(portraitHost),ismael:characterId(couple[0]),laura:characterId(couple[1]),npc:characterId(npcHost)}}
function measureBottom(){const nav=$(".bottom");if(!nav)return 0;const h=Math.ceil(nav.getBoundingClientRect().height);if(h>0)document.documentElement.style.setProperty("--kp-nav-h",`${h}px`);return h}
function runDiagnostics(crowded,touchFixed,navHeight,overflowHits){const required=["#kpGameHud","#kpGameObjective","#kpGameHub",".bottom","#map","#questList"],missing=required.filter(s=>!$(s));const dataOk=Array.isArray(D.quests)&&D.quests.length>0&&Array.isArray(D.pois)&&D.pois.length>0,horizontalOverflow=Math.max(0,document.documentElement.scrollWidth-innerWidth),doubleDialogFrame=auditDialogs(),characters=auditCharacters();window.KP_VISUAL_AUDIT={version:"6.8",timestamp:new Date().toISOString(),missing,crowded,touchFixed,navHeight,overflowHits,horizontalOverflow,doubleDialogFrame,characters,dataOk,viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio||1}};document.documentElement.classList.toggle("kp-audit-warning",missing.length>0||!dataOk||horizontalOverflow>3||doubleDialogFrame||characters.blankPortrait||characters.missingCouple||characters.identityMismatch)}
function version(){const v=$("#settingsVersion");if(v&&v.textContent!=="Kraków Pocket · v6.8")v.textContent="Kraków Pocket · v6.8"}
function enhance(){frame=0;dayPart();decorateHub();decorateQuest();upgradeCharacters();upgradeLandmarks();upgradeNavigation();markNextMission();auditNav();const navHeight=measureBottom(),overflowHits=auditOverflow(),crowded=auditNodeCollisions(),touchFixed=auditTouchTargets();runDiagnostics(crowded,touchFixed,navHeight,overflowHits);version()}
function schedule(){if(frame)return;frame=requestAnimationFrame(enhance)}
function watchHost(selector){const host=$(selector);if(!host||host.dataset.kpVisualWatch)return;host.dataset.kpVisualWatch="1";new MutationObserver(schedule).observe(host,{childList:true,subtree:true})}
function watchVersion(){const v=$("#settingsVersion");if(!v||v.dataset.kpVersionWatch)return;v.dataset.kpVersionWatch="1";new MutationObserver(()=>{if(v.textContent!=="Kraków Pocket · v6.8")v.textContent="Kraków Pocket · v6.8"}).observe(v,{childList:true,characterData:true,subtree:true})}
function mapRepair(){setTimeout(()=>window.dispatchEvent(new Event("resize")),80);setTimeout(()=>window.dispatchEvent(new Event("resize")),260)}
function installNavObserver(){const nav=$(".bottom");if(!nav||!window.ResizeObserver)return;navRO?.disconnect();navRO=new ResizeObserver(()=>{measureBottom();schedule()});navRO.observe(nav)}
function bind(){if(started)return;started=true;enhance();watchHost("#kpGameHud");watchHost("#kpGameHub");watchHost("#kpQuestWorld");watchHost(".bottom");watchVersion();installNavObserver();document.addEventListener("click",e=>{const tab=e.target.closest?.('.tab[data-panel]');if(tab){setTimeout(schedule,25);if(tab.dataset.panel==="mapPanel")mapRepair()}},true);window.addEventListener("storage",schedule);window.addEventListener("kp:statechange",schedule);window.addEventListener("resize",schedule,{passive:true});window.addEventListener("orientationchange",()=>setTimeout(schedule,120),{passive:true});document.addEventListener("visibilitychange",()=>{document.documentElement.classList.toggle("kp-paused",document.hidden);if(!document.hidden){dayPart();schedule()}});document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;$("#kpQuestDialog.show")?.classList.remove("show");$("#kpQuestWin.show")?.classList.remove("show")});setInterval(()=>{dayPart();version()},300000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();