(() => {
"use strict";
const D=window.KP_DATA,APP=window.KP_APP;if(!D||!APP)return;
const GAME_URL="./assets/game-art.svg",CHAR_URL="./assets/characters.svg";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CHAR={ismaelPortrait:"char-ismael-v4-portrait",lauraPortrait:"char-laura-v4-portrait",ismaelWorld:"char-ismael-v4-world",lauraWorld:"char-laura-v4-world",dragon:"npc-dragon-v4",guardian:"npc-guardian-v1"};
const NAV={home:"nav-home",mapPanel:"nav-map",quests:"nav-quests",diary:"nav-diary",budget:"nav-budget"};
const NAV_FALLBACK={home:"🏠",mapPanel:"🗺️",quests:"📜",diary:"📖",budget:"🎒"};
let game=null,chars=null,ready=false,frame=0,navRO=null,started=false;

function parseSprite(text){const doc=new DOMParser().parseFromString(text,"image/svg+xml"),defs=doc.querySelector("defs")?.innerHTML||"",symbols=new Map();doc.querySelectorAll("symbol[id]").forEach(s=>symbols.set(s.id,{viewBox:s.getAttribute("viewBox")||"0 0 180 180",html:s.innerHTML}));return{defs,symbols}}
async function load(url){const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw new Error(`${url}: ${r.status}`);return parseSprite(await r.text())}
function inline(pack,id,cls){const s=pack?.symbols.get(id);if(!s)return"";return `<svg data-kp-inline="${id}" data-kp-character="${id}" class="${cls}" viewBox="${s.viewBox}" aria-hidden="true" focusable="false"><defs>${pack.defs}</defs>${s.html}</svg>`}
function setArt(host,pack,id,cls,label){if(!host||!id)return false;if(host.dataset.asset===id&&host.querySelector(`svg[data-kp-inline="${CSS.escape(id)}"]`))return true;const html=inline(pack,id,cls);if(!html)return false;host.innerHTML=html;host.dataset.asset=id;if(label)host.setAttribute("aria-label",label);return true}
function speakerCharacter(){return/Guardián/i.test($("#kpGameHub .kp-hub-speaker")?.textContent||"")?{id:CHAR.guardian,label:"Guardián del viaje"}:{id:CHAR.dragon,label:"Dragón de Wawel"}}
function patchCharacters(){const player=APP.getPlayer(),portraitId=player==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait;setArt($("#kpGameHud .kp-game-portrait"),chars,portraitId,"kp-character-asset",player);const couple=$$("#kpGameHub .kp-couple-art");setArt(couple[0],chars,CHAR.ismaelWorld,"kp-character-asset","Ismael");setArt(couple[1],chars,CHAR.lauraWorld,"kp-character-asset","Laura");const npc=speakerCharacter();setArt($("#kpGameHub .kp-hub-avatar"),chars,npc.id,"kp-npc-asset",npc.label)}
function patchLandmarks(){$$('#kpQuestWorld .kp-landmark-art[data-landmark]').forEach(host=>{const id=host.dataset.landmark;setArt(host,game,`landmark-${id}`,"kp-landmark-svg")})}
function patchNavigation(){$$('.tab[data-panel]').forEach(tab=>{const id=tab.dataset.panel,b=tab.querySelector("b");if(!b)return;if(!setArt(b,game,NAV[id],"kp-asset-svg"))b.textContent=NAV_FALLBACK[id]||"•"});$$('#kpGameHub .kp-hub-place[data-go]').forEach(btn=>{const id=btn.dataset.go,target=btn.querySelector('.building');if(!target)return;if(!setArt(target,game,NAV[id],"kp-asset-svg"))target.textContent=NAV_FALLBACK[id]||"•"})}
function fallbackCharacters(){const p=$("#kpGameHud .kp-game-portrait"),couple=$$("#kpGameHub .kp-couple-art"),npc=$("#kpGameHub .kp-hub-avatar");if(p&&!p.children.length)p.textContent=APP.getPlayer()==="Laura"?"L":"I";if(couple[0]&&!couple[0].children.length)couple[0].textContent="I";if(couple[1]&&!couple[1].children.length)couple[1].textContent="L";if(npc&&!npc.children.length)npc.textContent=/Guardián/i.test($("#kpGameHub .kp-hub-speaker")?.textContent||"")?"🧙":"🐉"}

function dayPart(){const h=new Date().getHours(),html=document.documentElement;html.classList.remove("kp-morning","kp-afternoon","kp-evening","kp-night");html.classList.add(h<11?"kp-morning":h<18?"kp-afternoon":h<22?"kp-evening":"kp-night")}
function decorateHub(){const world=$("#kpGameHub .kp-hub-world");if(!world)return;if(!world.querySelector(".kp-hub-vfx")){const layer=document.createElement("div");layer.className="kp-vfx-layer kp-hub-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<span class="kp-vfx-sun"></span><span class="kp-vfx-cloud c1"></span><span class="kp-vfx-cloud c2"></span><span class="kp-vfx-bird"></span><span class="kp-vfx-bird b2"></span><i class="kp-pollen p1"></i><i class="kp-pollen p2"></i><i class="kp-pollen p3"></i><i class="kp-leaf-fall l1"></i><i class="kp-leaf-fall l2"></i>';world.appendChild(layer)}world.classList.add("kp-illustrated-scene")}
function decorateQuest(){const map=$("#kpQuestWorld .kp-world-map");if(!map)return;if(!map.querySelector(".kp-world-vfx")){const layer=document.createElement("div");layer.className="kp-vfx-layer kp-world-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<i class="kp-world-sparkle s1"></i><i class="kp-world-sparkle s2"></i><i class="kp-world-sparkle s3"></i><i class="kp-river-glint g1"></i><i class="kp-river-glint g2"></i>';map.appendChild(layer)}map.classList.add("kp-illustrated-map")}
function markNextMission(){const next=D.quests.find(q=>!APP.isMissionDone(q.poi)),id=next?.poi||"";$$('#kpQuestWorld .kp-world-node').forEach(node=>{const active=node.dataset.pixelPoi===id;node.classList.toggle("kp-next-mission",active);if(active)node.setAttribute("aria-current","step");else node.removeAttribute("aria-current");const old=node.querySelector(".kp-next-arrow");if(active&&!old){const a=document.createElement("span");a.className="kp-next-arrow";a.textContent="⌄";a.setAttribute("aria-hidden","true");node.appendChild(a)}else if(!active&&old)old.remove()})}
function auditNavState(){$$('.tab[data-panel]').forEach(t=>{if(t.classList.contains("active"))t.setAttribute("aria-current","page");else t.removeAttribute("aria-current")})}
function auditOverflow(){const selectors=["#kpGameHud","#kpGameObjective",".kp-world-top",".kp-hub-dialog",".card",".smart-card",".sheet-head",".metric",".expense",".timeline-day"],textSelectors=[".kp-game-logo strong",".tab",".kp-world-node small",".metric .value"];let hits=0;for(const sel of [...selectors,...textSelectors])for(const el of $$(sel)){el.classList.remove("kp-visual-overflow","kp-visual-tight");if(el.scrollWidth>el.clientWidth+3){hits++;el.classList.add("kp-visual-overflow");if(textSelectors.some(s=>el.matches(s)))el.classList.add("kp-visual-tight")}}return hits}
function auditTouchTargets(){let fixed=0;for(const el of $$('button,input,select,textarea')){el.classList.remove("kp-touch-fix");const r=el.getBoundingClientRect();if(r.width>0&&r.height>0&&(r.height<42||r.width<36)){el.classList.add("kp-touch-fix");fixed++}}return fixed}
function auditNodeCollisions(){const nodes=$$('#kpQuestWorld .kp-world-node');nodes.forEach(n=>{n.classList.remove("kp-crowded","kp-label-left","kp-label-right","kp-label-up");const left=parseFloat(n.style.left||"50"),top=parseFloat(n.style.top||"50");if(left<17)n.classList.add("kp-label-right");else if(left>83)n.classList.add("kp-label-left");if(top>87)n.classList.add("kp-label-up")});let hits=0;for(let i=0;i<nodes.length;i++){const a=nodes[i].querySelector("small")?.getBoundingClientRect();if(!a)continue;for(let j=i+1;j<nodes.length;j++){const b=nodes[j].querySelector("small")?.getBoundingClientRect();if(!b)continue;const overlap=!(a.right+3<b.left||b.right+3<a.left||a.bottom+3<b.top||b.bottom+3<a.top);if(!overlap)continue;hits++;nodes[i].classList.add("kp-crowded",parseFloat(nodes[i].style.left||"50")<=parseFloat(nodes[j].style.left||"50")?"kp-label-left":"kp-label-right");nodes[j].classList.add("kp-crowded",parseFloat(nodes[j].style.left||"50")>=parseFloat(nodes[i].style.left||"50")?"kp-label-right":"kp-label-left")}}return hits}
function rectOverlap(a,b,pad=2){return a&&b&&!(a.right+pad<b.left||b.right+pad<a.left||a.bottom+pad<b.top||b.bottom+pad<a.top)}
function characterId(host){const svg=host?.querySelector("svg");return svg?.dataset.kpInline||host?.dataset.asset||""}
function auditCharacters(){const selected=APP.getPlayer(),expected=selected==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait,portrait=$("#kpGameHud .kp-game-portrait"),couple=$$("#kpGameHub .kp-couple-art"),npc=$("#kpGameHub .kp-hub-avatar"),speaker=speakerCharacter().id;const blankPortrait=!portrait?.querySelector("svg"),missingCouple=couple.length<2||couple.some(x=>!x.querySelector("svg")),identityMismatch=characterId(portrait)!==expected||characterId(couple[0])!==CHAR.ismaelWorld||characterId(couple[1])!==CHAR.lauraWorld||characterId(npc)!==speaker,coupleRect=$("#kpGameHub .kp-hub-couple")?.getBoundingClientRect(),collision=$$("#kpGameHub .kp-hub-place small").some(l=>rectOverlap(coupleRect,l.getBoundingClientRect()));document.documentElement.classList.toggle("kp-character-warning",blankPortrait||missingCouple||identityMismatch);document.documentElement.classList.toggle("kp-character-collision",collision);return{blankPortrait,missingCouple,identityMismatch,collision,selected,portrait:characterId(portrait),ismael:characterId(couple[0]),laura:characterId(couple[1]),npc:characterId(npc)}}
function auditDialogs(){const checks=[];for(const d of $$("dialog")){const r=d.getBoundingClientRect();if(d.open&&((r.width>innerWidth+2)||(r.height>innerHeight+2)))checks.push(d.id||d.className)}return checks}
function measureBottom(){const nav=$(".bottom");if(!nav)return 0;const h=Math.ceil(nav.getBoundingClientRect().height);if(h>0)document.documentElement.style.setProperty("--kp-nav-h",`${h}px`);return h}
function runDiagnostics(){const required=["#kpGameHud","#kpGameObjective","#kpGameHub",".bottom","#map","#questList"],missing=required.filter(s=>!$(s)),navHeight=measureBottom(),overflowHits=auditOverflow(),touchFixed=auditTouchTargets(),crowded=auditNodeCollisions(),characters=auditCharacters(),dialogs=auditDialogs(),horizontalOverflow=Math.max(0,document.documentElement.scrollWidth-innerWidth),dataOk=Array.isArray(D.quests)&&D.quests.length===12&&Array.isArray(D.pois)&&D.pois.length>0;window.KP_VISUAL_AUDIT={version:"7.0",timestamp:new Date().toISOString(),missing,navHeight,overflowHits,touchFixed,crowded,characters,dialogs,horizontalOverflow,dataOk,assets:{game:!!game,characters:!!chars},viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio||1}};document.documentElement.classList.toggle("kp-audit-warning",missing.length>0||!dataOk||horizontalOverflow>3||dialogs.length>0||characters.identityMismatch||characters.blankPortrait||characters.missingCouple)}
function patch(){frame=0;dayPart();decorateHub();decorateQuest();if(ready){patchCharacters();patchLandmarks();patchNavigation();document.documentElement.classList.add("kp-inline-art-ready");document.documentElement.classList.remove("kp-inline-art-failed")}else fallbackCharacters();markNextMission();auditNavState();runDiagnostics()}
function schedule(){if(!frame)frame=requestAnimationFrame(patch)}
function installNavObserver(){const nav=$(".bottom");if(!nav||!window.ResizeObserver)return;navRO?.disconnect();navRO=new ResizeObserver(schedule);navRO.observe(nav)}
function bind(){if(started)return;started=true;patch();installNavObserver();window.addEventListener("kp:game-render",schedule);window.addEventListener("kp:render",schedule);window.addEventListener("resize",schedule,{passive:true});window.addEventListener("orientationchange",()=>setTimeout(schedule,120),{passive:true});window.addEventListener("pageshow",schedule);document.addEventListener("visibilitychange",()=>{document.documentElement.classList.toggle("kp-paused",document.hidden);if(!document.hidden)schedule()});Promise.all([load(GAME_URL),load(CHAR_URL)]).then(([g,c])=>{game=g;chars=c;ready=true;schedule()}).catch(err=>{console.warn("Kraków Pocket art load",err);document.documentElement.classList.add("kp-inline-art-failed");schedule()});setInterval(()=>{dayPart();if(!document.hidden)schedule()},600000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();