(() => {
"use strict";
const D=window.KP_DATA;if(!D)return;
const STORAGE="krakowPocketCoop",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch{return{}}};
const done=(s,id)=>s.missionStatus?.[id]?!!s.missionStatus[id].done:(s.visited||[]).includes(id);
let frame=0,observers=[];
function dayPart(){const h=new Date().getHours(),html=document.documentElement;html.classList.remove("kp-morning","kp-afternoon","kp-evening","kp-night");html.classList.add(h<11?"kp-morning":h<18?"kp-afternoon":h<22?"kp-evening":"kp-night")}
function decorateHub(){const world=$("#kpGameHub .kp-hub-world");if(!world||world.querySelector(".kp-hub-vfx"))return;const layer=document.createElement("div");layer.className="kp-vfx-layer kp-hub-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<span class="kp-vfx-sun"></span><span class="kp-vfx-cloud c1"></span><span class="kp-vfx-cloud c2"></span><span class="kp-vfx-bird"></span><span class="kp-vfx-bird b2"></span><span class="kp-vfx-grass"></span>';world.appendChild(layer)}
function decorateQuest(){const map=$("#kpQuestWorld .kp-world-map");if(!map)return;if(!map.querySelector(".kp-world-vfx")){const layer=document.createElement("div");layer.className="kp-vfx-layer kp-world-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<i class="kp-world-sparkle s1"></i><i class="kp-world-sparkle s2"></i><i class="kp-world-sparkle s3"></i><i class="kp-world-sparkle s4"></i>';map.appendChild(layer)}const s=read(),next=D.quests.find(q=>!done(s,q.poi));$$('#kpQuestWorld .kp-world-node').forEach(n=>{n.classList.remove("kp-next-mission");n.removeAttribute("aria-current");n.querySelector(".kp-next-arrow")?.remove();const label=n.querySelector("small")?.textContent?.trim();if(label)n.title=label});if(next){const node=$(`#kpQuestWorld .kp-world-node[data-pixel-poi="${CSS.escape(next.poi)}"]`);if(node){node.classList.add("kp-next-mission");node.setAttribute("aria-current","step");const a=document.createElement("span");a.className="kp-next-arrow";a.textContent="⌄";a.setAttribute("aria-hidden","true");node.appendChild(a)}}}
function auditNav(){$$('.tab[data-panel]').forEach(t=>{const active=t.classList.contains("active");if(active)t.setAttribute("aria-current","page");else t.removeAttribute("aria-current")})}
function auditOverflow(){const candidates=["#kpGameHud","#kpGameObjective",".kp-world-top",".kp-hub-dialog",".card",".smart-card",".sheet-head",".tab",".kp-world-node small"];for(const sel of candidates)for(const el of $$(sel)){el.classList.remove("kp-visual-overflow","kp-visual-tight");if(el.scrollWidth>el.clientWidth+3){el.classList.add("kp-visual-overflow");if(el.matches(".tab,.kp-world-node small,.kp-game-logo strong"))el.classList.add("kp-visual-tight")}}}
function version(){const v=$("#settingsVersion");if(v)v.textContent="Kraków Pocket · v6.1"}
function enhance(){frame=0;dayPart();decorateHub();decorateQuest();auditNav();auditOverflow();version()}
function schedule(){if(frame)return;frame=requestAnimationFrame(enhance)}
function watchHost(selector){const host=$(selector);if(!host||host.dataset.kpVisualWatch)return;host.dataset.kpVisualWatch="1";const obs=new MutationObserver(schedule);obs.observe(host,{childList:true,subtree:true});observers.push(obs)}
function mapRepair(){setTimeout(()=>window.dispatchEvent(new Event("resize")),70);setTimeout(()=>window.dispatchEvent(new Event("resize")),260)}
function bind(){enhance();watchHost("#kpGameHub");watchHost("#kpQuestWorld");document.addEventListener("click",e=>{const tab=e.target.closest?.('.tab[data-panel]');if(tab){setTimeout(schedule,20);if(tab.dataset.panel==="mapPanel")mapRepair()}},true);window.addEventListener("storage",schedule);window.addEventListener("resize",schedule,{passive:true});document.addEventListener("visibilitychange",()=>{document.documentElement.classList.toggle("kp-paused",document.hidden);if(!document.hidden){dayPart();schedule()}});document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;$("#kpQuestDialog.show")?.classList.remove("show");$("#kpQuestWin.show")?.classList.remove("show")});setInterval(()=>{dayPart();version()},60000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();
