(() => {
"use strict";
const D=window.KP_DATA,APP=window.KP_APP;if(!D||!APP)return;
const GAME_URL="./assets/game-art.svg?v=710",CHAR_URL="./assets/characters.svg?v=710";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CHAR={ismaelPortrait:"char-ismael-v4-portrait",lauraPortrait:"char-laura-v4-portrait",ismaelWorld:"char-ismael-v4-world",lauraWorld:"char-laura-v4-world",dragon:"npc-dragon-v4",guardian:"npc-guardian-v1"};
const NAV={home:"nav-home",mapPanel:"nav-map",quests:"nav-quests",diary:"nav-diary",budget:"nav-budget"};
const NAV_FALLBACK={home:"🏠",mapPanel:"🗺️",quests:"📜",diary:"📖",budget:"🎒"};
let game=null,chars=null,ready=false,frame=0,navRO=null,started=false,lastAudit=0,auditTimer=0;

function resolveUses(html,doc){let out=html;for(let pass=0;pass<3;pass++){let changed=false;out=out.replace(/<use\b[^>]*href=["']#([^"']+)["'][^>]*\/?>(?:<\/use>)?/gi,(match,id)=>{const target=doc.getElementById(id);if(!target)return match;const clone=target.cloneNode(true);clone.removeAttribute("id");changed=true;return clone.outerHTML});if(!changed)break}return out}
function rewriteRefs(html,prefix){return html.replace(/url\(#([^)]+)\)/g,(_,id)=>`url(#${prefix}-${id})`).replace(/\b(href|xlink:href)=["']#([^"']+)["']/g,(_,attr,id)=>`${attr}="#${prefix}-${id}"`)}
function parseSprite(text,prefix){const doc=new DOMParser().parseFromString(text,"image/svg+xml");if(doc.querySelector("parsererror"))throw new Error("SVG inválido");const defsEl=doc.querySelector("defs"),rawDefs=[...(defsEl?.children||[])].filter(el=>!String(el.id||"").startsWith("art-")).map(el=>el.outerHTML).join(""),defs=rewriteRefs(rawDefs.replace(/\bid=["']([^"']+)["']/g,(_,id)=>`id="${prefix}-${id}"`),prefix),symbols=new Map();doc.querySelectorAll("symbol[id]").forEach(s=>symbols.set(s.id,{viewBox:s.getAttribute("viewBox")||"0 0 180 180",html:rewriteRefs(resolveUses(s.innerHTML,doc),prefix)}));return{prefix,defs,symbols}}
async function load(url,prefix){const r=await fetch(url,{cache:"no-cache"});if(!r.ok)throw new Error(`${url}: ${r.status}`);return parseSprite(await r.text(),prefix)}
function ensureGlobalDefs(pack){if(!pack?.defs)return;let root=$("#kpGlobalSvgDefs");if(!root){root=document.createElementNS("http://www.w3.org/2000/svg","svg");root.id="kpGlobalSvgDefs";root.setAttribute("aria-hidden","true");root.setAttribute("focusable","false");root.style.cssText="position:absolute;width:0;height:0;overflow:hidden;pointer-events:none";root.innerHTML="<defs></defs>";document.body.prepend(root)}const key=`pack${pack.prefix}`;if(root.dataset[key])return;root.querySelector("defs").insertAdjacentHTML("beforeend",pack.defs);root.dataset[key]="1"}
function inline(pack,id,cls){const s=pack?.symbols.get(id);if(!s)return"";ensureGlobalDefs(pack);return `<svg data-kp-inline="${id}" class="${cls}" viewBox="${s.viewBox}" aria-hidden="true" focusable="false">${s.html}</svg>`}
function setArt(host,pack,id,cls,label){if(!host||!id)return false;const current=host.querySelector("svg[data-kp-inline]");if(host.dataset.asset===id&&current?.dataset.kpInline===id)return true;const html=inline(pack,id,cls);if(!html)return false;host.innerHTML=html;host.dataset.asset=id;if(label)host.setAttribute("aria-label",label);return true}
function speaker(){return/Guardián/i.test($("#kpGameHub .kp-hub-speaker")?.textContent||"")?{id:CHAR.guardian,label:"Guardián del viaje"}:{id:CHAR.dragon,label:"Dragón de Wawel"}}
function patchCharacters(){const player=APP.getPlayer(),portraitId=player==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait,portrait=$("#kpGameHud .kp-game-portrait"),pair=$$("#kpGameHub .kp-couple-art"),npc=speaker(),npcHost=$("#kpGameHub .kp-hub-avatar");if(!setArt(portrait,chars,portraitId,"kp-character-asset",player)&&portrait)portrait.textContent=player==="Laura"?"L":"I";if(!setArt(pair[0],chars,CHAR.ismaelWorld,"kp-character-asset","Ismael")&&pair[0])pair[0].textContent="I";if(!setArt(pair[1],chars,CHAR.lauraWorld,"kp-character-asset","Laura")&&pair[1])pair[1].textContent="L";if(!setArt(npcHost,chars,npc.id,"kp-npc-asset",npc.label)&&npcHost)npcHost.textContent=npc.id===CHAR.guardian?"🧙":"🐉"}
function patchLandmarks(){$$('#kpQuestWorld .kp-landmark-art[data-landmark]').forEach(host=>{const id=host.dataset.landmark,p=D.pois.find(x=>x.id===id),ok=id==="dragon"?setArt(host,chars,CHAR.dragon,"kp-landmark-svg"):setArt(host,game,`landmark-${id}`,"kp-landmark-svg");if(!ok&&!host.children.length)host.textContent=p?.emoji||"•"})}
function patchNavigation(){$$('.tab[data-panel]').forEach(tab=>{const id=tab.dataset.panel,b=tab.querySelector("b");if(b&&!setArt(b,game,NAV[id],"kp-asset-svg"))b.textContent=NAV_FALLBACK[id]||"•"});$$('#kpGameHub .kp-hub-place[data-go]').forEach(btn=>{const id=btn.dataset.go,target=btn.querySelector('.building');if(target&&!setArt(target,game,NAV[id],"kp-asset-svg"))target.textContent=NAV_FALLBACK[id]||"•"})}
function fallbackArt(){const p=$("#kpGameHud .kp-game-portrait"),pair=$$("#kpGameHub .kp-couple-art"),npc=$("#kpGameHub .kp-hub-avatar");if(p&&!p.children.length)p.textContent=APP.getPlayer()==="Laura"?"L":"I";if(pair[0]&&!pair[0].children.length)pair[0].textContent="I";if(pair[1]&&!pair[1].children.length)pair[1].textContent="L";if(npc&&!npc.children.length)npc.textContent=/Guardián/i.test($("#kpGameHub .kp-hub-speaker")?.textContent||"")?"🧙":"🐉";patchNavigation()}

function dayPart(){const h=new Date().getHours(),root=document.documentElement,next=h<11?"kp-morning":h<18?"kp-afternoon":h<22?"kp-evening":"kp-night";for(const c of ["kp-morning","kp-afternoon","kp-evening","kp-night"])root.classList.toggle(c,c===next)}
function decorateHub(){const world=$("#kpGameHub .kp-hub-world");if(!world)return;world.classList.add("kp-illustrated-scene");if(world.querySelector(".kp-hub-vfx"))return;const layer=document.createElement("div");layer.className="kp-vfx-layer kp-hub-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<span class="kp-vfx-sun"></span><span class="kp-vfx-cloud c1"></span><span class="kp-vfx-cloud c2"></span><span class="kp-vfx-bird"></span><span class="kp-vfx-bird b2"></span><i class="kp-pollen p1"></i><i class="kp-pollen p2"></i><i class="kp-pollen p3"></i><i class="kp-leaf-fall l1"></i><i class="kp-leaf-fall l2"></i>';world.appendChild(layer)}
function decorateQuest(){const map=$("#kpQuestWorld .kp-world-map");if(!map)return;map.classList.add("kp-illustrated-map");if(map.querySelector(".kp-world-vfx"))return;const layer=document.createElement("div");layer.className="kp-vfx-layer kp-world-vfx";layer.setAttribute("aria-hidden","true");layer.innerHTML='<i class="kp-world-sparkle s1"></i><i class="kp-world-sparkle s2"></i><i class="kp-world-sparkle s3"></i><i class="kp-river-glint g1"></i><i class="kp-river-glint g2"></i>';map.appendChild(layer)}
function markNextMission(){const next=D.quests.find(q=>!APP.isMissionDone(q.poi)),id=next?.poi||"";$$('#kpQuestWorld .kp-world-node').forEach(node=>{const active=node.dataset.pixelPoi===id;node.classList.toggle("kp-next-mission",active);if(active)node.setAttribute("aria-current","step");else node.removeAttribute("aria-current");const arrow=node.querySelector(".kp-next-arrow");if(active&&!arrow){const a=document.createElement("span");a.className="kp-next-arrow";a.textContent="⌄";a.setAttribute("aria-hidden","true");node.appendChild(a)}else if(!active&&arrow)arrow.remove()})}
function syncAria(){$$('.tab[data-panel]').forEach(t=>{if(t.classList.contains("active"))t.setAttribute("aria-current","page");else t.removeAttribute("aria-current")})}
function measureNav(){const nav=$(".bottom");if(!nav)return 0;const h=Math.ceil(nav.getBoundingClientRect().height);if(h>0)document.documentElement.style.setProperty("--kp-nav-h",`${h}px`);return h}

function rectOverlap(a,b,pad=2){return!!a&&!!b&&!(a.right+pad<b.left||b.right+pad<a.left||a.bottom+pad<b.top||b.bottom+pad<a.top)}
function characterId(host){return host?.querySelector("svg")?.dataset.kpInline||host?.dataset.asset||""}
function auditCharacters(){const player=APP.getPlayer(),expected=player==="Laura"?CHAR.lauraPortrait:CHAR.ismaelPortrait,portrait=$("#kpGameHud .kp-game-portrait"),pair=$$("#kpGameHub .kp-couple-art"),npc=$("#kpGameHub .kp-hub-avatar"),npcExpected=speaker().id,coupleRect=$("#kpGameHub .kp-hub-couple")?.getBoundingClientRect(),obstacles=$$("#kpGameHub .kp-hub-place small,#kpGameHub .kp-hub-place .building");const blankPortrait=!portrait?.querySelector("svg"),missingPair=pair.length<2||pair.some(x=>!x.querySelector("svg")),identityMismatch=ready&&(characterId(portrait)!==expected||characterId(pair[0])!==CHAR.ismaelWorld||characterId(pair[1])!==CHAR.lauraWorld||characterId(npc)!==npcExpected),collision=obstacles.some(el=>rectOverlap(coupleRect,el.getBoundingClientRect(),1));document.documentElement.classList.toggle("kp-character-warning",blankPortrait||missingPair||identityMismatch);document.documentElement.classList.toggle("kp-character-collision",collision);return{player,blankPortrait,missingPair,identityMismatch,collision,portrait:characterId(portrait),ismael:characterId(pair[0]),laura:characterId(pair[1]),npc:characterId(npc)}}
function auditQuestLabels(){const nodes=$$('#kpQuestWorld .kp-world-node');nodes.forEach(n=>{n.classList.remove("kp-crowded","kp-label-left","kp-label-right","kp-label-up");const left=parseFloat(n.style.left||"50"),top=parseFloat(n.style.top||"50");if(left<17)n.classList.add("kp-label-right");else if(left>83)n.classList.add("kp-label-left");if(top>87)n.classList.add("kp-label-up")});let hits=0;for(let i=0;i<nodes.length;i++){const a=nodes[i].querySelector("small")?.getBoundingClientRect();if(!a)continue;for(let j=i+1;j<nodes.length;j++){const b=nodes[j].querySelector("small")?.getBoundingClientRect();if(!b||!rectOverlap(a,b,3))continue;hits++;const li=parseFloat(nodes[i].style.left||"50"),lj=parseFloat(nodes[j].style.left||"50");nodes[i].classList.add("kp-crowded",li<=lj?"kp-label-left":"kp-label-right");nodes[j].classList.add("kp-crowded",lj>=li?"kp-label-right":"kp-label-left")}}return hits}
function auditTouch(){let hits=0;for(const el of $$('button,input,select,textarea')){el.classList.remove("kp-touch-fix");const r=el.getBoundingClientRect();if(r.width>0&&r.height>0&&(r.height<44||r.width<44)){el.classList.add("kp-touch-fix");hits++}}return hits}
function auditOverflow(){const selectors=["#kpGameHud","#kpGameObjective",".kp-world-top",".kp-hub-dialog",".card",".smart-card",".sheet-head",".metric",".expense",".timeline-day",".tab"],tight=[".kp-game-logo strong",".tab",".kp-world-node small",".metric .value"];let hits=0;for(const sel of selectors)for(const el of $$(sel)){el.classList.remove("kp-visual-overflow","kp-visual-tight");if(el.clientWidth&&el.scrollWidth>el.clientWidth+3){hits++;el.classList.add("kp-visual-overflow");if(tight.some(s=>el.matches(s)))el.classList.add("kp-visual-tight")}}return hits}
function auditDialogs(){return $$("dialog").filter(d=>{if(!d.open)return false;const r=d.getBoundingClientRect();return r.width>innerWidth+2||r.height>innerHeight+2}).map(d=>d.id||d.className)}
function auditAssets(){const gameRequired=[...Object.values(NAV),...D.quests.filter(q=>q.poi!=="dragon").map(q=>`landmark-${q.poi}`)],charRequired=[...Object.values(CHAR)],missingGame=gameRequired.filter(id=>!game?.symbols.has(id)),missingCharacters=charRequired.filter(id=>!chars?.symbols.has(id));return{missingGame,missingCharacters,ok:ready&&!missingGame.length&&!missingCharacters.length}}
function auditDuplicateIds(){const seen=new Set(),dup=[];for(const el of $$('[id]')){if(seen.has(el.id)&&!dup.includes(el.id))dup.push(el.id);seen.add(el.id)}return dup}
function auditControls(){return $$('button,[role="button"]').filter(el=>{const r=el.getBoundingClientRect();if(!r.width||!r.height)return false;return!(el.getAttribute("aria-label")||el.getAttribute("aria-labelledby")||el.textContent.trim())}).map(el=>el.id||el.className||el.tagName)}
function auditData(){const poiIds=new Set(D.pois.map(p=>p.id)),questIds=D.quests.map(q=>q.id),questPois=D.quests.map(q=>q.poi),duplicates=a=>a.filter((v,i)=>a.indexOf(v)!==i).filter((v,i,a)=>a.indexOf(v)===i),duplicateQuestIds=duplicates(questIds),duplicateQuestPois=duplicates(questPois),orphanQuests=D.quests.filter(q=>!poiIds.has(q.poi)).map(q=>q.id);return{ok:D.quests.length===12&&D.pois.length>0&&!duplicateQuestIds.length&&!duplicateQuestPois.length&&!orphanQuests.length,duplicateQuestIds,duplicateQuestPois,orphanQuests}}
function runAudit(){lastAudit=Date.now();clearTimeout(auditTimer);auditTimer=0;const state=APP.getState(),required=["#kpGameHud","#kpGameObjective","#kpGameHub","#kpQuestWorld","#map",".bottom","#settingsSheet","#storyDialog","#kpGlobalSvgDefs"],missing=required.filter(s=>!$(s)),activePanels=$$(".panel.active").length,activeTabs=$$(".tab.active").length,tabs=$$(".tab[data-panel]").length,navHeight=measureNav(),touchFixes=auditTouch(),overflowHits=auditOverflow(),questCollisions=auditQuestLabels(),characters=auditCharacters(),dialogs=auditDialogs(),assets=auditAssets(),duplicateIds=auditDuplicateIds(),unnamedControls=auditControls(),horizontalOverflow=Math.max(0,document.documentElement.scrollWidth-innerWidth),stateOk=Array.isArray(state.visited)&&Array.isArray(state.expenses)&&Array.isArray(state.memories)&&!!state.config&&!!state.missionStatus&&Number.isFinite(+state.config.dailyTarget)&&Number.isFinite(+state.config.fixedPaid)&&typeof state.configUpdatedAt==="string",data=auditData(),issues=[];if(missing.length)issues.push(`missing:${missing.join(",")}`);if(activePanels!==1)issues.push(`activePanels:${activePanels}`);if(activeTabs!==1)issues.push(`activeTabs:${activeTabs}`);if(tabs!==5)issues.push(`tabs:${tabs}`);if(horizontalOverflow>3)issues.push(`horizontalOverflow:${horizontalOverflow}`);if(dialogs.length)issues.push(`dialogs:${dialogs.join(",")}`);if(!stateOk)issues.push("state");if(!data.ok)issues.push("data");if(!assets.ok)issues.push("assets");if(characters.identityMismatch||characters.blankPortrait||characters.missingPair)issues.push("characters");if(duplicateIds.length)issues.push(`duplicateIds:${duplicateIds.join(",")}`);if(unnamedControls.length)issues.push(`unnamedControls:${unnamedControls.join(",")}`);window.KP_AUDIT={version:"7.1",timestamp:new Date().toISOString(),issues,missing,stateOk,data,activePanels,activeTabs,tabs,navHeight,overflowHits,touchFixes,questCollisions,characters,dialogs,horizontalOverflow,assets,duplicateIds,unnamedControls,pwa:{serviceWorker:"serviceWorker" in navigator,secureContext:window.isSecureContext,online:navigator.onLine},viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio||1}};window.KP_VISUAL_AUDIT=window.KP_AUDIT;document.documentElement.classList.toggle("kp-audit-warning",issues.length>0)}
function requestAudit(force=false){const wait=force?0:Math.max(0,15000-(Date.now()-lastAudit));if(!wait){requestAnimationFrame(runAudit);return}if(!auditTimer)auditTimer=setTimeout(()=>requestAnimationFrame(runAudit),wait)}
function patch(audit=false){frame=0;dayPart();decorateHub();decorateQuest();if(ready){ensureGlobalDefs(game);ensureGlobalDefs(chars);patchCharacters();patchLandmarks();patchNavigation();document.documentElement.classList.add("kp-inline-art-ready");document.documentElement.classList.remove("kp-inline-art-failed")}else fallbackArt();markNextMission();syncAria();measureNav();requestAudit(audit)}
function schedule(audit=false){if(frame)return;frame=requestAnimationFrame(()=>patch(audit))}
function bind(){if(started)return;started=true;patch(true);const nav=$(".bottom");if(nav&&window.ResizeObserver){navRO=new ResizeObserver(()=>schedule(true));navRO.observe(nav)}window.addEventListener("kp:game-render",()=>schedule(false));window.addEventListener("resize",()=>schedule(true),{passive:true});window.addEventListener("orientationchange",()=>setTimeout(()=>schedule(true),120),{passive:true});window.addEventListener("pageshow",()=>schedule(true));document.addEventListener("visibilitychange",()=>{document.documentElement.classList.toggle("kp-paused",document.hidden);if(!document.hidden)schedule(true)});Promise.all([load(GAME_URL,"game"),load(CHAR_URL,"char")]).then(([g,c])=>{game=g;chars=c;ready=true;schedule(true)}).catch(err=>{console.warn("Kraków Pocket art load",err);document.documentElement.classList.add("kp-inline-art-failed");schedule(true)});setInterval(()=>{dayPart();if(!document.hidden)requestAudit(false)},600000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
})();